### ISSUE TITLE
Cannot use flags in freeimage plugin

### ISSUE THREAD

**Issue by letmaik** [scikit-image/scikit-image#1195]
The freeimage plugin has many flags usable via its `read` and `write` methods. But the `imread` and `imwrite` methods don't allow to pass these flags, so with the main entry point `skimage.io.imwrite` for example you cannot specify the JPEG quality.

**Comment by jni** [comment]
@soupault thanks for the ping, but @stefanv I don't know anything about freeimage. There's talk elsewhere about deprecating its use? CC @blink1073 

In general, though, I do suggest that we either:

- ensure our IO is Insanely Great (TM), because that is the first port of contact for beginners. If we can't even get that right they are not going to trust us with their pipeline. *Or,*
- offload all IO responsibility to ImageIO, add it as a dependency/vendor it, and then contribute there. Last I checked (a while ago), it was not at the Insanely Great stage.

What do we do when we don't use freeimage? Pillow? Is that reasonably feature-complete?

**Comment by soupault** [comment]
@jni there is discussion removal of `freeimage` in https://github.com/scikit-image/scikit-image/issues/1463 .

**Comment by soupault** [comment]
This is not relevant anymore (see https://github.com/scikit-image/scikit-image/pull/1933). Closing.
