### ISSUE TITLE
cannot import name find_contours

### ISSUE THREAD

**Issue by jegpeek** [scikit-image/scikit-image#1335]
Perhaps this is a totally newbie problem, or something with my local install, but after running the usual pip install I always get

"cannot import name find_contours"

whenever I import a module that includes find_contours. For instance, these four commands run without error:

from skimage import color
from skimage import data
from skimage import draw
from skimage import exposure

but this one crashes with "cannot import name find_contours"

from skimage import feature

same with transform:

http://nbviewer.ipython.org/gist/jegpeek/61878eacae6404e692d6

Ideas?

**Comment by jegpeek** [comment]
Note: When I build from source this doesn't happen.

**Comment by blink1073** [comment]
@jegpeek, can you try deleting `skimage` from your `site-packages` folder, and then trying a `pip install`?

**Comment by jegpeek** [comment]
I have it working now from source. Should I try to de-install it from source and reinstall via pip? Happy to try to help, but, well, now that it works i'd prefer to not blow it up.

**Comment by stefanv** [comment]
The pip install is supposed to just be a build from source.  If you'd like
to help us debug the problem, easiest is to set up a new virtual
environment (that way you don't break your other, working installation) and
re-attempt the pip install.

**Comment by blink1073** [comment]
for example (assuming Windows and Anaconda):

```python
conda create -n test scipy pillow
activate test
pip install skimage
```

**Comment by jegpeek** [comment]
Running with anaconda, but on a mac. Please advise!

-Josh

**Comment by blink1073** [comment]
Updated my comment.

**Comment by blink1073** [comment]
And when you're done: `conda remove -n test--all`

**Comment by jegpeek** [comment]
will give it a shot tonight!

**Comment by blink1073** [comment]
(after trying `python -c "from skimage import feature"` of course.

**Comment by blink1073** [comment]
@jegpeek, have you had a chance to look at this?

**Comment by mhejrati** [comment]
I could fix it by removing the scikit folder and reinstalling. The package installer does not clean up completely when you uninstall.
So here is how I did it:
rm -rf Enthought/Canopy_64bit/User/lib/python2.7/site-packages/skimage
pip install scikit-image
and it worked.

**Comment by JDWarner** [comment]
This is something that rarely happens when upgrading from specific older versions. At one point we had a couple Python function names which now map to a Cython function of the same name or vice versa, or where a Cython `*.pyx` or `*.pyd` file was moved. Upgrading drops new, correct files in all the proper places, but old compiled files may hang around. Sometimes they get searched first, and then the import can stumble in an odd way.

If you experience this, please try the solution posted above by @mhejrati summarized by:

``` bash
rm -rf path/to/python/site-packages/skimage
pip install scikit-image
```

which nukes your entire skimage directory so you can start fresh. As there is a known solution, I'm closing the issue.

I want to reiterate though: this was always a rare problem and our current naming conventions make it unlikely to happen again. I have only experienced it once while developing between major versions.
