### ISSUE TITLE
Crop returns zero-array

### ISSUE THREAD

**Issue by yankov** [scikit-image/scikit-image#1525]
Scikit-image 0.11.3

```python
from skimage import data  
from skimage.util import crop
im = data.lena()  
im.shape
=> (512, 512, 3)

im = crop(im, 300)
im.shape
=> (0, 0, 0)

**Comment by JDWarner** [comment]
This is expected behavior. The second argument to `crop` is the amount you want to crop; it shares identical conventions with the `pad_width` argument to `pad`. When you pass a single value to that argument, it is interpreted as the amount you want to trim symmetrically from _all axes_.

With a (512, 512, 3) image, the most you could meaningfully crop would be 255. Beyond that, you'll get a size-zero array of the same rank as your input.

For completeness, with multichannel/color images a single integer will almost never be correct, as the implicit assumption is that all axes are spatial. You will need to spare the dimension denoting channel/color information from cropping. This can be done, e.g., by 

``` python
# Assuming sample data is imported and named `im`
crop_amt = ((25, 25), (25, 25), (0, 0))
im = crop(im, crop_amt)
```

which will preserve your color channels.

Finally, in any places you previously used the `lena` test image please consider using `astronaut` instead. The image is the same size, but of much higher quality and a more positive provenance.
