### ISSUE TITLE
Future-protect functions against positional argument use

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#1581]
Write a decorator that ensures that function parameters are passed in as image + keywords.

**Comment by ahojnnes** [comment]
Can you give an example?

**Comment by jni** [comment]
I'm :-1: on this, with some minor exceptions (e.g. functions with tons of args). Python supports positional arguments, and we should support Python. (More strongly: positional arguments are not unpythonic.)

**Comment by stefanv** [comment]
Yet, we have a lot of problems with deprecations. The only reason this has
to be a decorator is for Python 2. In three we have syntax for enforcing
the same.

**Comment by ahojnnes** [comment]
I don't think we should enforce kwargs. Even though it might make our
life easier for deprecations...

**Comment by JDWarner** [comment]
As previously articulated, I'll play the devil's advocate here. What if,
instead of deprecating so long for kwarg changes or enforcing how users do
things, we simply implement the change - in such a way that we can detect
the old behavior - and raise an informative error message telling users
what changed and how to get it working again.

This seems like the most Pythonic path. Fail gracefully is the unofficial
mantra of Python, after all. From the user perspective, this may be
superior to ignored deprecation warnings.

**Comment by jni** [comment]
@stefanv the deprecation issue is really not that huge, imho. A bit of extra effort in the PR.

As I suggested at the time of the last one, I think we should make big sweeping changes to make the API consistent throughout the library in time for 1.0. Breaking changes are allowed in moving from 0.x to 1.x. In the future, we can be careful about the API for new functionality, and, if we're not fully satisfied with it, stick it in skimage.future, where we reserve the right to break APIs.

When we do break APIs in .future, I'll be happy taking @JDWarner's suggested approach.

**Comment by blink1073** [comment]
My vote is for a 1.0 that includes a signature cleanup, switching to imageio, and the IPython widget framework for the viewer.

**Comment by blink1073** [comment]
About imageio, I have added the tifffile, gdal, simpleitk and fits plugins, and I think it is ready for integration.

**Comment by stefanv** [comment]
Excellent, let's go ahead with the replacement.
