### ISSUE TITLE
`imsave` handles bool images incorrectly

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#1623]
```
import numpy as np
from skimage import io

image = np.random.random((100, 100)) > 0.5

io.imsave('/tmp/foo.jpg', image, plugin='pil')
```

results in a black image

**Comment by JDWarner** [comment]
It appears the original values are being maintained while the dtype is converted to uint8, resulting in an almost-black-on-true-black image if one views without an automatic window. Or,almost maintained; since JPEG is lossy there are a few inaccuracies in the roundtrip. With a PNG file the roundtrip is exact.

What to do here is fraught with peril, as a user might want and expect saved values of 1 through a roundtrip, not 255.

There is no "low-contrast image" warning raised. That would be the lightest fix.

**Comment by stefanv** [comment]
The behavior is broken from a user perspective, though, since they pass in a valid image, and get an image on disk that displays differently.  Even when loading back in, the data type is wrong.

**Comment by JDWarner** [comment]
It's not ideal, but since (afaik) PNG and JPEG don't support Boolean format this issue may be beyond our ability to address.

When I ran your example with JPEG (or other lossy formats) I got a few scattered values that were **2**, not just 0 and 1, so "convert 1-bit contrast image to bool on load" is perilous. Even disregarding this, scientists may have ultra-low contrast images after background subtraction that need to remain ultra-low contrast.

Emitting a always-warning when saving a boolean array stating the data will be upconverted to uint8 in the file, or adding a kwarg to control the specific case of boolean arrays are the only good options I can see. I'd favor the former.

**Comment by stefanv** [comment]
A bool array should be converted to uint8 before saved to a format that only supports uint8, no?  We do the same for float images.

**Comment by jni** [comment]
@stefanv isn't this the observed behaviour? 

```python
In [1]: from skimage import io

In [2]: import numpy as np

In [3]: im = np.random.rand(512, 512) > 0.5

In [4]: im.dtype
Out[4]: dtype('bool')

In [5]: io.imsave('Desktop/im.png', im)

In [6]: imload = io.imread('Desktop/im.png')

In [7]: imload.dtype
Out[7]: dtype('uint8')

In [8]: imload.max()
Out[8]: 1
```

As @JDWarner notes, I don't think we can do anything sensible with jpg, but with png, the observed behaviour is the most correct, I think.

Ah, you're probably thinking of using `img_as_ubyte`, which results in values in {0, 255}. Maybe. @JDWarner what do you think about this?

**Comment by stefanv** [comment]
I guess since we have ``img_as_bool`` I presumed it is a fully supported image type.  But I notice that the docs does not state that.  What is our position?

**Comment by JDWarner** [comment]
The definition of "fully supported" isn't locked down, which is probably the main issue.

I'd say we fully support boolean images as Python objects. However, because the common image formats don't support this dtype, we're left with compromises any time they have to touch the disk.

Automatically bouncing such images to full-range [0, 255] on save makes me uncomfortable. We'd be changing users' data. People working with those may well have considered them like labeled images, since `img.astype(bool) == 1` resolves, and there could be (a lot of) code out there which assumes `img = io.imread('./path/to/img.png') == 1` is going to preserve their data "values" like it always has. We're used to playing fast and loose with types in Python for better or worse and this workflow, well, works.

I noticed this a long time ago, back in around version 0.9, but thought it was working as intended. My assumption was that this was a deliberate design decision along the lines of what Cython does with `bint` - use the next largest supported dtype where necessary. With any viewer supporting an automatic window, the saved images appear just fine. Is it really a bug?

**Comment by stefanv** [comment]
This often bites me when I'm trying to save binary masks.  I guess
having a warning is the best we can do.

**Comment by wenzhexue** [comment]
@stefanv Warning would be good. I run into similar situation when saving a multiple label mask image in uint8 last month. ImageJ shows "total" black. I spent quite some time to debug until realizing it's not the code.

**Comment by WarrenWeckesser** [comment]
> It's not ideal, but since (afaik) PNG and JPEG don't support Boolean format this issue may be beyond our ability to address.

FYI: PNG supports a bit depth of 1, which could be used when saving a boolean image.  But then what data type and values would you expect to get when reading such an image?  I recently had to deal with this issue in scipy (https://github.com/scipy/scipy/pull/5289).  When reading a 1-bit PNG file, `scipy.misc.imread` now returns an array with dtype `np.uint8` containing the values 0 and 255.  (That's what `skimage.io.imread` does, too--at least with the 'pil' plugin.)  This behavior is consistent with how it handles 2-bit and 4-bit files, where the values are scaled up to the 8-bit range.  For example, when reading a 2-bit file, the array that is returned contains the values 0, 85, 170 and 255.  *That* behavior is inherited from Pillow.  (It is also the behavior suggested in the PNG specification.)

**Comment by OrkoHunter** [comment]
Faced the issue today myself. Would love to see a warning being raised. :)

**Comment by stefanv** [comment]
@OrkoHunter Looking forward to that PR :)

**Comment by alvinzz** [comment]
Myself and @Bernwang will be working on this over the next week

**Comment by stefanv** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Foo](https://trello.com/c/xCaFvTHj/1-foo)

**Comment by adius** [comment]
Oh boy. Just waisted to so much time until I figured that this is the problem 😭

**Comment by onobruno** [comment]
I was facing the same problem and saved the image using the "misc.imsave" instead "io" module. This way I am not getting the black images.

**Comment by cipri-tom** [comment]
Would it be possible to also use the `matplotlib` plugin for `imsave` ? It would have the "desired" behaviour for users used to MPL.

This way, users can `io.use_plugin('matplotlib')` once and then do all their operations with `skimage` library. Otherwise, now I `io.imread` an image, but `plt.imsave` the binarised result

**Comment by akshaylamba** [comment]
i solved it by the below code 
lbs is a bool array
```
y=lbs[i].astype(int)
    plt.imsave("/home/ubuntu/seg/data/labels/"+ name + ".png", np.array(y).reshape(640,640), cmap=cm.gray)
```

**Comment by stefanv** [comment]
@cipri-tom We do support matplotlib for imsave.
@scikit-image/core PR https://github.com/scikit-image/scikit-image/pull/2356 needs a new owner; it's trivial, is anyone willing to pick it up?

**Comment by johnphill** [comment]
Exporting the PNG as 8bpcRGB in Gimp solves the issue. I find this solution to be applicable to many API's that issue errors about "array size mismatch" (because it is supposed to be [width,height,3] but it is either [width,height] or [width,height,4]), or "array not integer". If you replace the image by JPG and the code works, it is an indication that the PNG is not in the correct format, therefore opening the image in Gimp and exporting as 8bpcRGB or other should do the trick.
