### ISSUE TITLE
Unexpected requirement for floating point images

### ISSUE THREAD

**Issue by r-atwood** [scikit-image/scikit-image#1627]
I don't think this is reasonable, to require floating point images to lie between [-1,1] and I don't see why this should be necessary particularly for sobel edge finding.

> > >   edges = sobel(image_filtered)
> > >   File "/dls_sw/apps/python/anaconda/1.7.0/64/lib/python2.7/site-
> > > packages/skimage/filter/edges.py", line 83, in sobel
> > >     return np.sqrt(hsobel(image, mask)**2 + vsobel(image, mask)**2)
> > >   File "/dls_sw/apps/python/anaconda/1.7.0/64/lib/python2.7/site-
> > > packages/skimage/filter/edges.py", line 113, in hsobel
> > >     image = img_as_float(image)
> > >   File "/dls_sw/apps/python/anaconda/1.7.0/64/lib/python2.7/site-
> > > packages/skimage/util/dtype.py", line 287, in img_as_float
> > >     return convert(image, np.float64, force_copy)
> > >   File "/dls_sw/apps/python/anaconda/1.7.0/64/lib/python2.7/site-
> > > packages/skimage/util/dtype.py", line 191, in convert
> > >     raise ValueError("Images of type float must be between -1 and
> > > 1.")
> > > ValueError: Images of type float must be between -1 and 1.
> > > ________________________________________

**Comment by jni** [comment]
@r-atwood I agree. I'm currently on holiday, but PRs are always welcome. Otherwise this might be something good to tackle at the sprints at EuroSciPy... =)

**Comment by derfuzzle** [comment]
this appears to be fixed in current master

**Comment by jni** [comment]
@r-atwood I've verified with @derfuzzle that all Sobel functions work with arbitrary range floats in the current master. What version of scikit-image are you using? Updating should fix it, I think!

```python
>>> from skimage import filters
>>> from skimage import data
>>> im = data.camera()
>>> im.dtype
dtype('uint8')
>>> imf = im.astype(float)
>>> s = filters.sobel(imf)
>>> s = filters.sobel_v(imf)
>>> s = filters.sobel_h(imf)
```

**Comment by jni** [comment]
@r-atwood reopen the issue if updating doesn't fix it! Thanks for reporting!

**Comment by ycartwhelen** [comment]
@refelix and @jni  - Why do you say this issue seems to be fixed in the master version?

I'm trying to run a float32 type raster with values outside of -1 to +1 through the slic segmentation function, and it's giving me the same error that originates in skimage\util\dtype.py of "ValueError: Images of type float must be between -1 and 1." When I check the code for dtype.py (either v. 0.11.3 or v. 0.12) I find that for any float input it checks that the values are between -1 and +1 (line 193), and if not raises the above error.

Can you suggest any solutions to this issue? I'm reluctant to convert my images to a -1 to +1 scale prior to this step in processing because I will need to full range of values in later processing steps.

**Comment by jni** [comment]
@ycartwhelen 

> why do you say this issue seems to be fixed

Because you reported an issue with Sobel filters, not SLIC. =)

Unfortunately, the requirement is there for both historical reasons and because it's useful to know the range of images based on data types for pipelining. See our [documentation on dtypes](http://scikit-image.org/docs/dev/user_guide/data_types.html).

Here's the rationale: when converting between image types, for example float to uint8, we need to know what the range of the images is, so that, for example, a low-brightness image remains low-brightness throughout its conversion, rather than get rescaled. So it makes sense to map [0, 1] in float to [0, 255] in uint8, and vice versa.

In your case, for SLIC, we need to ensure that the input image is of type float, which apparently we have equated with `float64`. So, when you pass in a `float64` image, the converter does nothing, while passing in a `float32` image triggers a conversion and subsequent error.

We could of course say, "hey, if it's a float32 to float64, don't mess with the range", but the way the conversion machinery is set up, we look at the input and output types separately, because otherwise you would have ntypes ^ 2 conditions to test, instead of 2 * ntypes conditions.

Either way, this problem comes up fairly often, see e.g. #1234.

I've opened a new issue that should fix this specific behaviour, `float32` causing an error in SLIC: #1737.

**Comment by r-atwood** [comment]
As OP, i must say I didn't mean that the problem is WITH sobel edge filtering. I mean I disagree with the notion of requiring normalized float for anything, and sobel edge filtering is just one example of where it is especially unsuitable since the output of the filter can take on pretty much any value , but this may be true for many other filters too.

**Comment by jni** [comment]
@r-atwood I generally agree with you and was the author of "we aim to preserve the data range and type of input images" in the [above-linked](http://scikit-image.org/docs/dev/user_guide/data_types.html) page on data types. But some functions *do* require or at least benefit from an assumed data range (e.g. display, or any function whose parameters depend on the color space — which includes SLIC, btw). So we have to fix bugs with specific functions as they come along...

**Comment by habi** [comment]
I stumbled over this error while using the `skimage.filters.rank.maximum`-filter.
The above-linked page on data types throws a 404 error...

**Comment by stefanv** [comment]
Yikes, it looks like our docs build broke.  Thanks for noticing.

**Comment by stefanv** [comment]
For now, please refer to: http://scikit-image.org/docs/stable/user_guide/data_types.html

**Comment by habi** [comment]
> For now, please refer to: http://scikit-image.org/docs/stable/user_guide/data_types.html

Thanks, I already found that out :)
