### ISSUE TITLE
``segmentation.find_boundaries`` and ``segmentation.mark_boundaries`` do not support boolean types

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#1645]
It would be nice to be able to pass a boolean binary image to these two functions. Testing for boolean type and converting to int is straigthforward.

**Comment by kshitij10496** [comment]
I was thinking of using either `img_as_ubyte()` or `astype()` for converting the boolean image to int type.  
On using `img_as_ubyte`, the boolean value `True` corresponds to `255` in int, 
while `astype()` sets `True` to `1`.  
We have to choose either implementation depending upon the convention. 
Since, I am new here,  I would need some help with this.

**Comment by stefanv** [comment]
I don't think it matters which method you use in this case, since the boundaries are clear either way.  Just try both options and see which works!  And remember to write a test along the way.

**Comment by kshitij10496** [comment]
@stefanv Thanks.
I am working on it.

**Comment by jni** [comment]
Closed by #1794
