### ISSUE TITLE
Flattening histogram into a feature vector in scikit-image/skimage/feature/_hog.py is redundant.

### ISSUE THREAD

**Issue by ekremney** [scikit-image/scikit-image#1646]
In return statements of scikit-image/skimage/feature/_hog.py, ravel() is used to flatten histogram into a vector. It is redundant as last user can add ravel function if it is needed.

In my case, I needed histogram not flattened; so I had to modify in source code.

**Comment by emmanuelle** [comment]
It's true that I don't really understand the interest of flattening the histogram...

**Comment by emmanuelle** [comment]
@scikit-image/core

**Comment by ivoflipse** [comment]
I suspect because the resulting histogram can be directly fed into a classifier when it's a feature vector, which is how the Dalal paper uses it. 

While correct that in that way it doesn't represent a histogram and uses can get the vector out by calling ravel, the opposite is also true. You can get the shape back by reshaping the vector, since it's shape is defined by parameters you passed in yourself:

```
sy, sx = image.shape
cx, cy = pixels_per_cell
bx, by = cells_per_block

n_cellsx = int(np.floor(sx // cx))  # number of cells in x
n_cellsy = int(np.floor(sy // cy))  # number of cells in y

n_blocksx = (n_cellsx - bx) + 1
n_blocksy = (n_cellsy - by) + 1
normalised_blocks = np.zeros((n_blocksy, n_blocksx, by, bx, orientations))
```

Though obviously that's a lot more work than simply having to call ravel.

Couldn't we just add a parameter which returns the histogram as is?

**Comment by Korijn** [comment]
I've added a parameter `feature_vector` in #1783 which is `True` by default (retaining current behaviour). You can set it to `False` to prevent the call to `.ravel()`.

**Comment by ekremney** [comment]
@Korijn That is the best solution.
