### ISSUE TITLE
Using google analytics for scikit-image website

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#1649]
At the moment we do not have a lot of information about the way users browse our website: which are the most viewed pages? What are the typical navigation patterns? Where do visitors come from? 

Using google analytics would be a simple way to gain more insights about website usage. If we decide that we want to use it, it's just a few lines of code to add to doc/source/themes/scikit-image/layout.html

**Comment by sciunto** [comment]
I'm sorry but I have to say that I'm against, to protect the privacy of our visitors. A self-hosted tool can do the same job without sending information to GAFAM.

**Comment by tacaswell** [comment]
We have GA setup on matplotlib.org and it is working out well.

**Comment by emmanuelle** [comment]
@sciunto @tacaswell thank you for your input. There are indeeed pros and cons about using GA. As François is mentioning it, the main argument against it might be to give the data to Google. As for the pros, the main reason that I can see would be to improve the website using a better understanding of how people use it, which is a big deal in my opinion.

In addition to matplotlib, scikit-learn is also using GA.

What kind of alternatives to GA were you suggesting, @sciunto ?

**Comment by ahojnnes** [comment]
We also provide "Like" buttons on our websites, use Google fonts, etc. I am
not an expert on this, but I think adding Google Analytics wouldn't
increase Google's ability to track our users - it is already there.

+1 on including GA - but I generally agree with @sciunto about the
tracking, even though we would have to be consequent about it and exclude
all of the other features as well.

**Comment by sciunto** [comment]
Piwik can do a similar job as GA. Fonts can be installed on the server as well.

In short, I have difficulties to understand how we can promote free/libre softwares (python, scipy and scikits) in one hand and in the other hand we can rely proprietary softwares or components that we cannot trust (either in terms for privacy (GA) or control and perennity (travis-ci, google mailing lists)). I'm really disappointed that those questions are almost never addressed in the community, but it's not the right place to argue further.

**Comment by tacaswell** [comment]
Sorry to drag this conversation out, but I want to respond to @sciunto s comment.

I view this as a practicality vs purity thing (we are also a BSD not a GPL community).  There are open / self hosted ways to do all of these things, but getting those setup, working, and maintained takes developer effort.  I think it is a much better use of our (very limited) resources work on the code we care about rather than to take on ever more system administration tasks.  I have no problem accepting support-in-kind from companies that are built on top of open tools (github/travis) or exploiting loss leader / advertisement services if it makes it easier to work on the projects we care about.

Related to mailing lists, mpl has (just) moved to PSF hosted lists.

**Comment by ahojnnes** [comment]
Agreed with Thomas.

**Comment by sciunto** [comment]
> I view this as a practicality vs purity thing (we are also a BSD not a
> GPL community). There are open / self hosted ways to do all of these
> things, but getting those setup, working, and maintained takes
> developer effort. I think it is a much better use of our (very
> limited) resources work on the code we care about rather than to take
> on ever more system administration tasks. I have no problem accepting
> support-in-kind from companies that are built on top of open tools
> (github/travis) or exploiting loss leader / advertisement services if
> it makes it easier to work on the projects we care about.
>
BSD and GPL are both free/libre licenses, one gives more permissions,
but still, they both relies on sharing. As GPL softwares, BSD softwares
are getting better only if people are willing to give. So each time I
have a choice, I prefer to make things that promotes sharing.

About the developer effort, my calculation does not give me the same
result. What I see is a fragile situation relying on the wish of people
we do not have any indenpendence. Each project is small or medium, but
the sum of all projects represents a large community, we can put things
in common (build tools, documentation hosting...) and the time to manage
all this as well. As a user, I'm also ready to participate financially
to PSF (or equivalent) to pay hardware and working time so that
developpers can focus on coding and helping activities. I'm aware that
freedom is not free of charge and I donate a little each month to
developers who provide me tremendous and useful tools. It's just a
matter of responsability and acknowledgement.

As an example, right now, each project is dealing with the rules of
travis-ci, trying to optimize through an API and today it just takes
forever to check a commit to scikit-image. I do not consider this as an
optimized developer effort.
When sourceforge injects code in released software, I do not consider
this as an optimized developer effort (you can discuss with some devs
from the gimp project). When google code decides to shutdown their
service within 6 months, I do not consider this as an optimized
developer effort too :)


> Related to mailing lists, mpl has (just) moved to PSF hosted lists.
>
>

Excellent news! I thank people who pushed that way.

**Comment by pratapvardhan** [comment]
Not really sure if we are using an external web-server to host content, apart from github pages.

But, we are using one, then to get for access logs, we could use ngnix or apace server. That shall give the data to answer - "Which are the most viewed pages? What are the typical navigation patterns? Where do visitors come from?"

Sample conf file for NGINX Reverse proxy settings to Github pages - https://gist.github.com/taddev/8872330

**Comment by tacaswell** [comment]
I would point out we have now spent more effort discussing this than it would to set up and deploy GA on the documentation website.

@sciunto I fully agree that it would be better if all of the projects pooled resources and we had our 'own' VC/CI/web hosting (and the logical organization to run this through is [NumFOCUS]( http://numfocus.org/) ) and that doing so may be more efficient and stable in the long term.  But in the short there is a lot of legwork, both technically and organizationally, that needs to be done to make that happen and those resources are not online _right now_.  In the typical maintainer passive-aggressive way I ask: Are you volunteering to lead the effort to get these resources organized, stood up, and maintained?

**Comment by emmanuelle** [comment]
@tacaswell sure, discussing takes a little time, but on the other hand it's important to get everyone's point of view as well, all the more when discussions are constructive as they seem to be!

**Comment by tacaswell** [comment]
Gah, sorry, that is not how I meant that!  I was trying to make the point that leveraging these tools saves tremendous amounts of time _in the short term_, not to shut down the discussion.

**Comment by emmanuelle** [comment]
He he sorry I misunderstood you!

**Comment by emmanuelle** [comment]
Coming back to this issue, since nobody volunteered to administrate an alternative solution to Google Analytics, I propose to move forward and to open a Google Analytics account for scikit-image's website.

By the way, GA is the most exact way that scikit-learn devs found to estimate the number of active users: by counting how many people read the online doc on a regular basis. I think that this can be really useful for us as well.

**Comment by stefanv** [comment]
Has someone checked whether we are using GA already?

**Comment by emmanuelle** [comment]
Good point, but I think we don't. For using GA on all pages of the doc, we should put some code in ``doc/source/themes/scikit-image/layout.html``, as for example in https://github.com/scikit-learn/scikit-learn/blob/master/doc/themes/scikit-learn/layout.html#L324. I'll take car of a PR handling GA. I was thinking of opening a new google account that could be shared among the core team for obtaining a GA code and then looking at the results, how does it sound?

**Comment by tacaswell** [comment]
@emmanuelle You don't actually need to make a new account as you can give access to GA to any google account.

**Comment by emmanuelle** [comment]
@tacaswell oh yes, thanks.

**Comment by stefanv** [comment]
I would like to hear @sciunto 's current take on the effort.  Are you happy if we move along with GA until we can come up with a better alternative?  Would you like to spearhead such an effort?

**Comment by sciunto** [comment]
@stefanv @emmanuelle I installed piwik on my server for tests purpose in the meantime and I'm running some tests with my main website. It looks nice so far, working well and user friendly.

If you are interested, we can put the small piece of javascript code and I can give the an access to those who are interested (just to avoid the give login/password to the universe).

**Comment by emmanuelle** [comment]
great news, thanks @sciunto ! Looking forward to your PR then :-).

**Comment by sciunto** [comment]
@emmanuelle Do you have recommendations for the file in which the javascript snippet can be added?

**Comment by emmanuelle** [comment]
@sciunto In order to track analytics for all pages, I think the code snippet must be defined in doc/source/themes/scikit-image/layout.html, so that it's present in all html pages. See for exemple what scikit-learn folks did in https://github.com/scikit-learn/scikit-learn/blob/master/doc/themes/scikit-learn/layout.html#L324

**Comment by emmanuelle** [comment]
Addressed by #1746, closing.
