### ISSUE TITLE
X-axis values on histogram equalized image

### ISSUE THREAD

**Issue by paulvija** [scikit-image/scikit-image#1698]
Hi there, 

This is not an issue but would like to know the reason behind. 
When an image with 0-255 colours is equalized I get x-axis values as 0.0-1.0 , however this is different to image's x-axis in http://www.tutorialspoint.com/dip/Histogram_Equalization.htm , which is 0-255.

Is the values shown in x-axis represents CDF?

Thanks,
Vijay

**Comment by JDWarner** [comment]
This is because, to retain accuracy during equalization, your image has been converted from an unsigned 8-bit representation to a floating point image. Float images are defined on the range [0, 1].

If you multiplied it by 255 you would have your original range, with some values lying between the original integers. If you want these rounded back and returned as uint8, use img_as_ubyte on the result.

Closing as answered.

**Comment by paulvija** [comment]
Cool, thanks for the well detailed explanation.
