### ISSUE TITLE
skimage.morphology.watershed bug?

### ISSUE THREAD

**Issue by rmsouza01** [scikit-image/scikit-image#1754]
Hi,

I was using skimage to perform watershed segmentation, but the results were strange. I compared skimage implementation with my own  watershed implementation, and they don't agree. I looked at skimage code at https://github.com/scikit-image/scikit-image/blob/master/skimage/morphology/watershed.py#L35. 

I saw there is a pedagogical purely python implementation, and I analyzed the algorithm, and it seemed correct, so I compared the pedagogical implementation against mine. This time the results were the same. 

I believe there is a bug in the current Cython implementation. Attached are the results I got using the skimage code and my own.

![img](https://cloud.githubusercontent.com/assets/6681255/10651778/b1365fd2-780e-11e5-8176-e21847ac70b9.png)
![markers](https://cloud.githubusercontent.com/assets/6681255/10651775/ae0aab92-780e-11e5-8ac4-842f05c5879e.png)
![ws1](https://cloud.githubusercontent.com/assets/6681255/10651102/adb4ef94-780a-11e5-95a1-d0e26517a01c.png)
![ws2](https://cloud.githubusercontent.com/assets/6681255/10651104/b1a766b8-780a-11e5-875f-f830241e24d2.png)

**Comment by jni** [comment]
Hi @rmsouza01!

Thanks for reporting this and sorry for the delay in responding!

What version of scikit-image are you using? There is indeed a bug in v0.11 and earlier, but it is fixed in master. See #1530. Version 0.12 should be out in a few weeks.

If you are referring to master, can you please:
- provide sample code
- include the plotting commands
- label the images

In particular, the third image looks correct to me, and it's what I get (approximately) with scikit-image master.

**Comment by stefanv** [comment]
No follow-up.  Closing.
