### ISSUE TITLE
is there an easy option to silence the precision_loss message ?

### ISSUE THREAD

**Issue by stonebig** [scikit-image/scikit-image#1760]
````
def prec_loss():
        warn("Possible precision loss when converting from "
             "%s to %s" % (dtypeobj_in, dtypeobj)
````
It does put a bad cloud over my cup of coffee

![ipywidgets_1](https://cloud.githubusercontent.com/assets/4312421/10716350/508bc750-7b36-11e5-82f4-76725abb7f2c.GIF)

**Comment by JDWarner** [comment]
The best solution is to filter specific warnings using the `with warnings.catch_warnings():` context manager, but if you want global silencing, this should do the trick at the top of a notebook:

``` python
import warnings
warnings.filterwarnings("ignore", message='Possible precision loss', append=True)
```

You can omit `append=True` if this is your only filter, but I note it here so you can run this command multiple times with different `message=` strings to build up a list of specific warnings you wish to silence. 

The second answer [here](http://stackoverflow.com/questions/14463277/how-to-disable-python-warnings) is useful if you want more info.

I'm closing this, but feel free to reopen if this doesn't answer your question!

**Comment by stonebig** [comment]
Is this warning usefull to some use case ?

**Comment by JDWarner** [comment]
Because information is being lost, it's an important warning. When it is returned, our datatype conversion routine was called in a way such that the conversion will be (or at least has the potential to be) lossy.

A lot of users will encounter this warning, because many if not most of our algorithms operate using floating-point images. Usually for output/saving, these images must be converted back into integer formats. At that point the warning is raised, because all of the decimal values had to be compressed into 255 bins.

That said, the majority of the time people see this and either know what's going on - so the warning is just annoying and they'd prefer never to see it again - or fear something went wrong, when everything is fine and we really just wanted to give the user a FYI. Right now we probably warn a little too much.
