### ISSUE TITLE
Infinite loop in exposure.equalize_adapthist()

### ISSUE THREAD

**Issue by mjharte** [scikit-image/scikit-image#1761]
The `equalize_adapthist()` function can hang, caused by the following:

When using a very small clip_limit parameter (e.g. 0.001) on a grayscale image with low contrast, the function `clip_histogram()` in `_adapthist.py` hangs in an infinite loop because the `n_excess` variable is not being lowered in the `while n_excess > 0` loop.

**Comment by blink1073** [comment]
Thanks for the heads up!  See #1762 for a fix.

**Comment by JDWarner** [comment]
Thanks for the report, @mjharte. Just so I'm understanding what is going on here, does such a problematic floating-point image not have any zero values? Also, is the original image 8-bit or greater? 

Mainly asking since 1/255 is 0.0039 and the image does get thresholded with `clip_limit` early on. I wonder if the non-terminating loop is a symptom and `clip_limit` should be checked to ensure it is greater than the lowest value in the input.

**Comment by mjharte** [comment]
Correct, the image has a minimum value of 1 and it's 8-bit.

> Josh Warner <mailto:notifications@github.com>
> 25October, 2015 21:34
>
> Thanks for the report, @mjharte <https://github.com/mjharte>. Just so 
> I'm understanding what is going on here, does such a problematic 
> floating-point image not have any zero values? Also, is the original 
> image 8-bit or greater?
>
> Mainly asking since 1/255 is 0.0039 and the image does get thresholded 
> with |clip_limit| early on. I wonder if the non-terminating loop is a 
> symptom and |clip_limit| should be checked to ensure it is greater 
> than the lowest value in the input.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/scikit-image/scikit-image/issues/1761#issuecomment-150966856>.
>

-- 
Sent from Postbox 
<https://www.postbox-inc.com/?utm_source=email&utm_medium=siglink&utm_campaign=reach>
