### ISSUE TITLE
binary_blobs, not sure if this is a bug

### ISSUE THREAD

**Issue by mbirdi** [scikit-image/scikit-image#1767]
I got some errors when trying to run code with binary blobs.  I have gotten it working now, but I am not sure if what I have done is correct.

When trying to create a binary_blobs object, I run this code:

import skimage as sk
from skimage import data
blob = data.binary_blobs(length=5, blob_size_fraction=0.2, seed=1)

Which generates the following attribute error:
AttributeError: 'module' object has no attribute 'binary_blobs'

I then went to the API:
http://scikit-image.org/docs/dev/api/skimage.data.html#binary-blobs
which took me to the source code:
https://github.com/scikit-image/scikit-image/blob/master/skimage/data/_binary_blobs.py#L5

After downloading that source code I changed the code from

import numpy as np
from ..filters import gaussian

to this:

import numpy as np
from skimage import filters
#from np.filters import gaussian

gaussian = filters.gaussian_filter

When I get rid of the relative import, I was able to create a binary_blob object.  Is it a bug to have a relative import in binary_blobs?  I want to use binary_blobs but my workaround seems kind of cumbersome.

thanks!

**Comment by emmanuelle** [comment]
Hello, ``data.binary_blobs`` is only available in the development version, not in the stable release. Can you confirm that you are using a stable release of scikit-image like 0.11? ``skimage.__version__`` will give you the version you are using.

If you want to use ``binary_blobs``, you can download the development version from https://github.com/scikit-image/scikit-image/archive/master.zip and build the package using the instructions in https://github.com/scikit-image/scikit-image/archive/master.zip

But I hope that we can have a new release in a few weeks, that will include ``binary_blobs``!

The relative import is used since the Python file you're using is part of a submodule of ``scikit-image``. If you're using this file as a separate module, you have to modify it indeed.

**Comment by mbirdi** [comment]
Thanks for the feedback!  I am using skimage version 0.11.3
