### ISSUE TITLE
Large whitespace in doc examples

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#1773]
- [x] http://scikit-image.org/docs/dev/auto_examples/plot_blob.html

**Comment by JDWarner** [comment]
Similar problems with excessive whitespace:
http://scikit-image.org/docs/dev/auto_examples/plot_censure.html
http://scikit-image.org/docs/dev/auto_examples/plot_convex_hull.html
http://scikit-image.org/docs/dev/auto_examples/plot_edge_filter.html (despite `tight_layout`)
http://scikit-image.org/docs/dev/auto_examples/plot_label.html
http://scikit-image.org/docs/dev/auto_examples/plot_line_hough_transform.html (second plot)
http://scikit-image.org/docs/dev/auto_examples/plot_rank_mean.html
http://scikit-image.org/docs/dev/auto_examples/plot_ssim.html
http://scikit-image.org/docs/dev/auto_examples/applications/plot_rank_filters.html

May be unrelated, due to 3d matplotlib plotting
http://scikit-image.org/docs/dev/auto_examples/plot_marching_cubes.html

These are likely just due to extremely simple visualizations which could be enhanced, possibly in a separate PR or with `tight_layout`
http://scikit-image.org/docs/dev/auto_examples/plot_ncut.html
http://scikit-image.org/docs/dev/auto_examples/plot_rag_draw.html
http://scikit-image.org/docs/dev/auto_examples/plot_rag_mean_color.html
http://scikit-image.org/docs/dev/auto_examples/plot_rag_merge.html
http://scikit-image.org/docs/dev/auto_examples/plot_windowed_histogram.html
http://scikit-image.org/docs/dev/auto_examples/applications/plot_geometric.html (first figure needs better `figsize`)

For completeness, these have too _little_ whitespace and would benefit from a more concise `tight_layout`:
http://scikit-image.org/docs/dev/auto_examples/plot_watershed.html
http://scikit-image.org/docs/dev/auto_examples/plot_medial_transform.html


Many of these seem related to the recent change to use shared x/y axes. However, some with that functionality look fine (like Otsu http://scikit-image.org/docs/dev/auto_examples/plot_local_otsu.html and morphological filtering http://scikit-image.org/docs/dev/auto_examples/applications/plot_geometric.html), so I'm not entirely sure what is going on. Reverting that PR would probably fix a lot of this, though.

**Comment by JDWarner** [comment]
Many of these may be related to #1704. However, some with that functionality look fine (like Otsu http://scikit-image.org/docs/dev/auto_examples/plot_local_otsu.html, and morphological filtering http://scikit-image.org/docs/dev/auto_examples/applications/plot_geometric.html), so I'm not entirely sure what is going on. 

Reverting that PR would probably fix a lot of this, though.

**Comment by alexandrejaguar** [comment]
Hi @stefanv and @JDWarner,
I tried to solve the issue on one of these files on #1810, with a certain success. This space appears on that file because of the third subplot; I think this example need to be rewritten. I'll check that later.

**Comment by yash14123** [comment]
Can I create a new issue for the other visualization change links suggested by @JDWarner so a new PR can be created? Then I can work on this. :)

**Comment by stefanv** [comment]
Sure, go for it.
