### ISSUE TITLE
Travis latex error

### ISSUE THREAD

**Issue by blink1073** [scikit-image/scikit-image#1835]
Warning, treated as error:
WARNING: LaTeX command 'latex' cannot be run (needed for math display), check the pngmath_latex setting

**Comment by emmanuelle** [comment]
Is it a warning that has been seen in recent pull requests?

**Comment by blink1073** [comment]
This is the first I've seen of it.

**Comment by soupault** [comment]
@blink1073 I'd suggest to close the issue. Reasons:
- `pngmath` has evolved into [`imgmath`](https://github.com/sphinx-doc/sphinx/commit/355fe2a2334aac1e44acb502c68a51555e76162c);
- We hadn't seen this error again since the time this issue was reported;
- Travis build for PR #1603 cannot be successfully re-run to check the repeatibility.

**Comment by blink1073** [comment]
Sounds good, thanks @soupault.
