### ISSUE TITLE
Alpha Blending: Converter function from RGBA to RGB

### ISSUE THREAD

**Issue by AbdealiJK** [scikit-image/scikit-image#2174]
## Description
This is a feature request. It would be nice to have a rgba to rgb converter which can take in a RGBA image, and convert it into a RGB image based on some logic. The method to do this is called Alpha blending (according to wikipedia).

So, when we have RGBA images, frequently some algos can't handle 4 channels, and we need to convert it to RGB. The naive method to convert it to RGB is by simply stripping out the Alpha channel, but that's not a good idea, as that may not visually be similar to the image. The method to do this is to alpha blend it with the background.

I'm thinking there would be a function `skimage.transform.rgba2rgb(rgba, background=(255, 255, 255))` where `background` is the color of the background which is RGB.

SO post describing method to use: http://stackoverflow.com/questions/2049230/convert-rgba-color-to-rgb
Wiki page describing alpha blending: https://en.wikipedia.org/wiki/Alpha_compositing#Alpha_blending

**Comment by soupault** [comment]
@AbdealiJK thanks, that is a very nice proposal!
Both of my hands up to add this :raised_hands:.

**Comment by AbdealiJK** [comment]
I've made https://github.com/AbdealiJK/scikit-image/commit/864fd512b49d9f064f26a2d35dfc674dcfca5c88 but I don't seem to be able to complete it because I can't run the tests.

I tried to do `nosetests --exe skimage` I get a lot of errors like:
 - ImportError: No module named backend_qt5
 - ImportError: No module named _skeletonize_3d_cy
 - ImportError: No module named _hough_transform

Here's the complete output: http://pastebin.com/2gCwFRUE

I tried `make coverage` based on http://scikit-image.org/docs/stable/contribute.html#test-coverage too and it did the same.

Could someone help in figuring out how to run tests locally ?

**Comment by JDWarner** [comment]
Sounds like your issue is the Cython must be compiled. There are two options:

1. If you want to use the development version as you work on it, run `python setup.py develop` first. This builds everything, then modifies your PYTHONPATH so your interpreter looks in the repo as it loads packages. It doesn't formally install the package, but it will affect other uses of scikit-image.

2. If you want to develop in a sandbox, with your other work (production, etc.) outside the Git repo still using version 0.12 stable, run `python setup.py build_ext --inplace` first. This builds the Cython only, after which `nosetests` will work. Everywhere else outside the package root, `import skimage` will use your stable installed scikit-image.

Which to use depends on your preferences and situation.

**Comment by AbdealiJK** [comment]
@JDWarner Thanks a lot, got it working :+1: and made the PR https://github.com/scikit-image/scikit-image/pull/2181
