### ISSUE TITLE
Docs: Use compare_ssim instead of deprecated structural_similarity

### ISSUE THREAD

**Issue by AbdealiJK** [scikit-image/scikit-image#2200]
## Description
In the current documentation at http://scikit-image.org/docs/dev/auto_examples/plot_ssim.html the function being used is `structural_similarity` (`from skimage.measure import structural_similarity as ssim`) although the docmentation at http://scikit-image.org/docs/dev/api/skimage.measure.html#structural-similarity says that the function is deprecated in favor of `compare_ssim`. 

Hence, as the function is deprecated, the doc should be importing `compare_ssim`.

**Comment by jni** [comment]
@AbdealiJK right again! =D

**Comment by kjacks21** [comment]
I can take care of this today or tomorrow.

**Comment by kjacks21** [comment]
Since [scikit-image/doc/examples/transform/plot_ssim.py ](https://github.com/scikit-image/scikit-image/blob/master/doc/examples/transform/plot_ssim.py) was already updated to import `compare_ssim`, does that mean this should be closed? Or is there another step to update http://scikit-image.org/docs/dev/auto_examples/plot_ssim.html ?

**Comment by soupault** [comment]
@kjacks21 thanks for pointing this out!
http://scikit-image.org/docs/dev/auto_examples/plot_ssim.html is a leftover example and is no longer available for updates (see https://github.com/scikit-image/scikit-image/issues/2059).

Closing as fixed.
