### ISSUE TITLE
Use `filters.gaussian` in place of deprecated `gaussian_filter`

### ISSUE THREAD

**Issue by JDWarner** [scikit-image/scikit-image#2206]
Per deprecation warnings in the test suite, this call is made in `skimage.segmentation` by the active contour function. It may also crop up in other places.

Fixing the problem should be a simple redirect to `skimage.filters.gaussian`.

**Comment by kjacks21** [comment]
@JDWarner If you think this is feasible for a novice contributor, mind if I take this up?

**Comment by JDWarner** [comment]
Go for it, @kjacks21!

**Comment by kjacks21** [comment]
Just to be clear, are we looking to have the two instances of `gaussian_filter` in [skimage/segmentation/active_contour_model.py](https://github.com/scikit-image/scikit-image/blob/6d0a94930ca81bed416db8286c737b8da2d80bdd/skimage/segmentation/active_contour_model.py) changed to `gaussian`? Or by "simple redirect" do you mean a more blanketed solution? I ask since `gaussian_filter` appears in numerous [locations](https://github.com/scikit-image/scikit-image/search?p=2&q=gaussian_filter&utf8=%E2%9C%93).

**Comment by JDWarner** [comment]
When following the test logs I noticed the warning in relation to the active contour tests, but figured it was also in use elsewhere.

Yes, all uses in the package should be converted to gaussian.

Essentially, we should follow our own deprecation warnings! During the course of using any public function, users should not get deprecation warnings related to a different internally used function.

**Comment by kjacks21** [comment]
Makes sense. I intend to make a separate PR for each file that I change unless there are any objections.

**Comment by soupault** [comment]
@kjacks21 I'd actually recommend to create a single PR with several commits.

**Comment by kjacks21** [comment]
@soupault I'll follow your recommendation!

**Comment by soupault** [comment]
Haven't found any usage besides `active_contours`. Should be fixed now.
