### ISSUE TITLE
cannot import name 'try_all_threshold'

### ISSUE THREAD

**Issue by GeekMe93** [scikit-image/scikit-image#2244]
I use example code provided by skimage in this [link](http://scikit-image.org/docs/dev/auto_examples/xx_applications/plot_thresholding.html#sphx-glr-auto-examples-xx-applications-plot-thresholding-py) in Anaconda.

But I have an error:

`ImportError: cannot import name 'try_all_threshold'`

Other modules in `skimage.filters` have no problems.

Python 3.5.2 |Anaconda custom (x86_64)
skimage 0.12.3

**Comment by JDWarner** [comment]
This is a new function which was recently added, slated to be released with version 0.13. The default docs are the dev branch, which are updated automatically with new features.

If you need this functionality, you can install scikit-image from source by cloning this repository and running `python setup.py develop` in the root directory. As you are using Anaconda, everything should be set up (Cython, compilers, etc.) so that should do it. Afterward you should see the version listed as `skimage 0.13dev`.

Closing as expected/solved with workaround.

**Comment by GeekMe93** [comment]
Thanks for your reply, I just found that:)

**Comment by GeekMe93** [comment]
@JDWarner Can you give me more info about how to upgrade to dev version in anaconda? I tried  ways mentioned in stackoverflow, they just did not work. I really need these new functionalities. Thanks:)

**Comment by jni** [comment]
@GeekMe93 what is your operating system? (Windows, Mac, Linux?)

**Comment by GeekMe93** [comment]
@jni  Sorry for the very late reply, I am busy with other stuff. My OS is Mac
