### ISSUE TITLE
Error in ssim equation in skimage.measure compare_ssim ?

### ISSUE THREAD

**Issue by ceg22** [scikit-image/scikit-image#2520]
Hi,
inside the source code for the compare_ssim function (https://github.com/scikit-image/scikit-image/blob/master/skimage/measure/_structural_similarity.py#L189-L204) I think there is an error in the equation for the SSIM.

Currently in _structural_similarity.py the equation is defined (lines 201 onwards): 
```
A1, A2, B1, B2 = ((2 * ux * uy + C1,
                       2 * vxy + C2,
                       ux ** 2 + uy ** 2 + C1,
                       vx + vy + C2))

D = B1 * B2
S = (A1 * A2) / D

# to avoid edge effects will ignore filter radius strip around edges
    pad = (win_size - 1) // 2
# compute (weighted) mean of ssim
    mssim = crop(S, pad).mean()
```

But I think B2 has been defined incorrectly (by comparing to Wang 2004).
currently `B2 =vx + vy + C2`
But comparing back to Wang 2004 shouldn't it be: `B2=vx**2 + vy**2 + C2` ?

This makes a small different in the resulting MSSIM.

**Comment by grlee77** [comment]
Thanks for looking into this, but I believe it is correct as-is.  I spent some time a while back updating/validating this function to make sure it is an exact match to the original author's implementation.

`vx` and `vy` in term `B2` are variances rather than the standard deviations listed in the equation used in the publication  (i.e. they are already squared)

Additional support for the correctness of the present implementation is independent validation of the results of this function compared to a result obtained from Wang et. al.'s Matlab code as well as from a 3rd party implementation from the IPOL journal.  see:
https://github.com/scikit-image/scikit-image/blob/d26cda0ab5a75482ce049ba962b092a275942eba/skimage/measure/tests/test_structural_similarity.py#L172-L194

**Comment by JDWarner** [comment]
Thanks for looking over our shoulders, @ceg22 - always good to double check.

Much appreciated verification and explanation, @grlee77.

Closing as current implementation is correct to the best of our knowledge.
