### ISSUE TITLE
PyPI Wheel for Python 3.6

### ISSUE THREAD

**Issue by jonasrauber** [scikit-image/scikit-image#2541]
There is no wheel for python 3.6. available at https://pypi.python.org/pypi/scikit-image
It would be nice to have one :-)

**Comment by soupault** [comment]
@jonasrauber We do not officially support Python 3.6 in any skimage versions released so far.
The support and testing for Python 3.6 has been finalized quite recently (in https://github.com/scikit-image/scikit-image/pull/2511), and will enabled (including pre-built wheels) with the release of 0.13.

**Comment by stefanv** [comment]
I'll retrigger a build; if the tests pass on 3.6, wheels should then appear at: http://wheels.scipy.org/ for 0.13dev0.

**Comment by stefanv** [comment]
Also, with the release (3 blocking issues away), these will be uploaded to PyPi.

**Comment by soupault** [comment]
@stefanv 
>wheels should then appear at: http://wheels.scipy.org/ for 0.13dev0.

Doesn't seem to be configured for 3.6. Tests were green on the merge.

**Comment by matthew-brett** [comment]
@stefanv - the retriggered build, built commit 851a614 - see https://travis-ci.org/scikit-image/scikit-image-wheels/jobs/203631060#L150.  This is the current submodule commit.  I think you want `master` instead of `HEAD` as the commit to build in `.travis.yml`, if you want to build latest scikit-image master...

**Comment by stefanv** [comment]
@matthew-brett Thanks for the hint! We spoke about this briefly before, but is there a 'latest-tag' option, and if not would that be a useful addition?

**Comment by matthew-brett** [comment]
Well - no `latest-tag` code in multibuild I'm afraid.  As you remember, this code is in its predecessor, but I was finding that, in practice, I nearly always found myself setting the tag by hand, because:

* I want to be specific about which tag I'm building;
* it's harder to make latest-tag work for Windows;
* I usually want a new commit for a new build rather than clicking the `restart build` button, so I have a record of the previous builds.

What I'm now starting to do, is have a couple of branches in the wheel-building repository, one called `daily` on which I have a cron job running, that builds the latest master, and `master`, which I use for building the releases.
