### ISSUE TITLE
skimage.transform.warp silently maps uint8 images to float

### ISSUE THREAD

**Issue by cancan101** [scikit-image/scikit-image#2609]
skimage.transform.warp silently maps uint8 images to float.

```python
tform = SimilarityTransform()
warp(127*np.ones((3,3), np.uint8), tform
```
```
array([[ 0.49803922,  0.49803922,  0.49803922],
       [ 0.49803922,  0.49803922,  0.49803922],
       [ 0.49803922,  0.49803922,  0.49803922]])
```

There is a flag `preserve_range`, but that does not quite do what is desired:
1. Type still converted to float
2. Range not capped in output at 0-255.

- [x] Python version
2.7
- [x] scikit-image version (run `skimage.__version__`)
`0.12.3`

**Comment by jni** [comment]
@cancan101 This is by design because:
- warping needs float output in order to do interpolation without precision loss
- you might need to chain warping with other operation. In order to not compound rounding errors, you want to work with float images as long as possible, until output time.

We detail these policies here:
http://scikit-image.org/docs/dev/user_guide/data_types.html

In order to get uint8 back, use (optionally) `np.clip` and `skimage.img_as_ubyte` on the output.

**Comment by jni** [comment]
@cancan101 I'm going to close for now, but please reopen if you want to discuss other solutions.

**Comment by cancan101** [comment]
I would say that the current API is no ideal (I would say it violates the "principle of least astonishment"). I think any of the following would be an improvement.
1. Accept uint8 and return float (as is now), but print a warning
2. Deprecate accepting uint8 and eventually only take float->float
3. Change so that uint8 in results in uint8 out (potentially with a warning about loss of precision).

I think that if a user care about loss of precision, then he should explicitly be working with float rather than uint8. I don't think it should be the responsibility of the library to leave the (intermediate) result in float.
