### ISSUE TITLE
Weird result of resize function

### ISSUE THREAD

**Issue by PrimozGodec** [scikit-image/scikit-image#2672]
## Description

I am trying to resize a `.jpg` image with `skimage.transform.resize function`. Function returns me weird result (see image below). I am not sure if it is a bug or just wrong use of the function. 

## Way to reproduce

    import numpy as np
    from skimage import io, color
    from skimage.transform import resize

    rgb = io.imread("../../small_dataset/" + file)
    rgb = resize(rgb, (256, 256))
    img = Image.fromarray(rgb, 'RGB')
    img.show()

Original image:

![original](https://cloud.githubusercontent.com/assets/6421558/26575793/eb2306be-4526-11e7-8f83-81caff32e37d.jpg)

Resized image:

![resized](https://cloud.githubusercontent.com/assets/6421558/26575806/f4281c72-4526-11e7-9ff2-9c9d13ec5540.jpg)

- [ ] Operating system: Ubuntu 16.04
- [ ] Python version: 3.5
- [ ] scikit-image version: 0.13.0

**Comment by sciunto** [comment]
What's `Image` module?

**Comment by jni** [comment]
@PrimozGodec Use `matplotlib.pyplot.imshow` to display an image, not the `Image` or `Pillow` library. 

```python
import numpy as np
from skimage import io, color
from skimage.transform import resize
import matplotlib.pyplot as plt

rgb = io.imread("../../small_dataset/" + file)
rgb = resize(rgb, (256, 256))
plt.imshow(rgb)
```

The problem is that the order of pixels/channels expected by `Image` is different from the order expected by scikit-image/matplotlib. See here for more info:

http://scikit-image.org/docs/dev/user_guide/numpy_images.html

Please feel free to comment on this issue if you have further questions!

**Comment by jni** [comment]
(And btw use `skimage.io.imsave` or `imageio.imsave` to save the image!)
