### ISSUE TITLE
Broken math formatting in documentation

### ISSUE THREAD

**Issue by ahojnnes** [scikit-image/scikit-image#2814]
See http://scikit-image.org/docs/stable/api/skimage.transform.html#projectivetransform

**Comment by jni** [comment]
My bad. I've "partly" fixed it, but can't get my LaTeX build to work correctly. If anyone can (a) checkout and install `upstream/v0.13.1` (tag), and (b) try the build process as detailed [here](https://github.com/scikit-image/scikit-image/blob/master/RELEASE.txt#L38-L45), perhaps you'll have better luck. If so, please upload!

In the future, we should consider moving to MathJAX.

In the nearer future, I'll submit a PR to update the release process to include checks for math formatting as well as gallery formatting (what I screwed up last time but actually checked this time). We probably also want to build the docs on a travis machine instead of the release manager's machine.

**Comment by stefanv** [comment]
The dev docs are being built on Travis-CI already, so we just have to extend that to the release tags.

**Comment by stefanv** [comment]
Fixed and uploaded.

**Comment by ahojnnes** [comment]
Looks good. Thanks! I’ll keep this open as a reminder to build the docs with Travis.
