### ISSUE TITLE
remove_small_objects with single label

### ISSUE THREAD

**Issue by Phlya** [scikit-image/scikit-image#2825]
When applied to a labelled image with only one label `skimage.morphology.remove_small_objects` treats all of pixels with the one label as a single object. It does show a warning, that perhaps a boolean array was intended to be used, where the behaviour is different, where it treats all connected components separately.

First of all, the documentation is a bit vague about this - the description of the method just says it removes connected components, and only in the description of the `ar` variable it says "If the array type is int, it is assumed that it contains already-labeled objects" - which also doesn't directly say that the behaviour is then different.
http://scikit-image.org/docs/stable/api/skimage.morphology.html#skimage.morphology.remove_small_objects

Second of all, this inconsistency creates a problem during batch processing of many images, when after labelling you don't know how many objects you will actually have, and just a warning is not very helpful - for a long time I was just thinking it was related to efficiency (i.e. with a single label it's more efficient to use boolean arrays) and completely ignored it until I discovered it actually wasn't doing what I expected it to.

Therefore, I think, at the very least the documentation should be more explicit about this, and ideally the behaviour should be changed. I am not sure what would be the best solution here, perhaps adding a keyword to define which behaviour is desired? Or splitting this method into to, with different behaviours?

Thanks!

**Comment by jni** [comment]
Hi @Phlya, thanks for the report!

I agree 100% that the documentation should be updated. Would you like to submit a PR to that effect? Otherwise we'll get to it, but it's hard to predict when. =)

Regarding the change in behaviour, we'd have to be careful. Right now, other than the confusing warning, the function can be used both with connected-components labelling, and with user labelling (which allows for disjoint objects, which I can imagine in many scenarios). The behaviour will be consistent across a batch, so the user just needs to decide whether to convert their images to int or to bool.

What is your use case? Perhaps you want to add a flag that would silence the warnings? Lastly, whenever people ask for another flag, I always show them this page to make them ponder the costs and whether they are really necessary:

http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html

Note that temporarily suppressing warnings is quite easy:

https://github.com/scikit-image/scikit-image/blob/b9e6a69a839bc65b3c70e0aad7b8e0ff06f81740/skimage/_shared/_warnings.py#L76-L105

We should probably expose that utility, I often find myself rummaging for it...

**Comment by Phlya** [comment]
Thanks for the reply @jni! I can try to submit a PR for this, yes.

My use case is I am doing batch segmentation of many 3D microscopy images, and need to remove small objects which are noise or otherwise useless. And simply converting to int or bool doesn't necessarily work - sometimes I have a labelled image, and I don't know how many labels I actually have, since I am processing many images - especially complicated since my images are 3D and sometimes I want to apply this method to each z-plane separately, while the whole image is labelled in 3D...

I don't think suppressing a warning is useful - what I mean is a flag about whether to use the labels, if the array is int, or to just remove connected components as if it was a bool array. Or a flag that does the same, if there is only one label present...

Also, I think this is the only morphology function which behaves differently for bool and 0-and-1 arrays?..

**Comment by jni** [comment]
> I think this is the only morphology function which behaves differently for bool and 0-and-1 arrays?

Damn. Touché. =P

I don't think not knowing the number of labels is an issue... For your use-case, I would do as follows:

```python
cells3d_segments = super_fancy_segmentation(cells3d_image)
for pln in cells3d_segments:
    pln *= remove_small_objects(pln.astype(bool))
```

Does that work?

Either way, I suggest we continue to discuss the API here (@scikit-image/core) and in the meantime update the docs.

My humble initial suggestion for a possible new parameter name is `relabel_objects=False`. Except relabel is the wrong word since presumably you want the original label(s) back, right?

**Comment by Phlya** [comment]
OK, this is a good workaround, should work - thanks! Somehow didn't think of such an easy solution.

Maybe, `labelled_objects`? If `True`, the array should be int and the labels are used (if it is not int, perhaps raise an error or a warning?), and if `False` - it should be bool, and if it is int, your suggestion above is used? Not sure which one should be the default though.

**Comment by Phlya** [comment]
See the PR with more clear explanation in the documentation.

**Comment by coderforlife** [comment]
Note that this warning occurs even if you give `remove_small_objects` a boolean array that only has one connected component! The warning should definitely never be emitted when giving a boolean array.

**Comment by jni** [comment]
@coderforlife good point! This was just fixed in master recently: https://github.com/scikit-image/scikit-image/pull/2930 We'll be releasing 0.14 soon with the fix!

**Comment by coderforlife** [comment]
@jni Thanks for the update!

As a side note, when using `remove_small_objects` with pre-labelled images I do the following which may be useful to others:

```
x = morphology.remove_small_objects(lbls) if lbls.max() > 1 else lbls
```

**Comment by stefanv** [comment]
Closed by https://github.com/scikit-image/scikit-image/pull/2830
