### ISSUE TITLE
Add flood fill algorithm

### ISSUE THREAD

**Issue by soupault** [scikit-image/scikit-image#2876]
## Description
https://en.wikipedia.org/wiki/Flood_fill

## References
Old mailing list thread - https://groups.google.com/forum/#!topic/scikit-image/n8lO2b_a3DQ.
Inspired by the discussion in https://stackoverflow.com/questions/47213246.

Please, share your thoughts.

**Comment by JDWarner** [comment]
I've got a basic implementation of a stack-based flood fill for uint8 images I'll toss up as a PR, if nothing else as a starting point.

**Comment by lagru** [comment]
I hope I'm not completely misjudging this but I basically implemented this already in #3022. It is essentially a queue based flood fill with a few additions to determine if a plateau is a maximum. I think that could be easily adapted to satisfy this request.

What do you think?

**Comment by JDWarner** [comment]
@lagru looks like you're right, didn't see that as part of the peak changes.  I don't necessarily want to rope you into things out of the scope of your existing PR, but if there is the possibility to take some of that algorithm into, e.g., `skimage._shared` and re-use it in a directly exposed flood fill, that would definitely be better than redundancy!

**Comment by lagru** [comment]
I would love to to that however I don't think reusing the same flood fill is possible in this case. The inner queue-consuming loop of my function has more logic than necessary for a basic flood-fill and I don't see an elegant way to move that logic outside. So I don't think a shared Cython function is the answer here. There are some Python parts that were adapted from the watershed algorithm so it might be possible to generalize and re-use those.

I mentioned this because it would be easy to take the basic skeleton of my code and with a few modifications use it as a basis for a n-dimensional flood-fill. I'm currently focused on #3022 but after that one is ready I'd be happy to do the work myself. Of course only if you agree and you haven't already gone ahead and solved this need with your own already working suggestion. :slightly_smiling_face:

**Comment by jni** [comment]
@lagru 

> has more logic than necessary for a basic flood-fill and I don't see an elegant way to move that logic outside. So I don't think a shared Cython function is the answer here. 

Actually I think it *is*. Let's be ambitious here: what is a general floodfill? 

- initial position
- definition of neighbourhood
- predicate about each point (and its neighbours) defining whether to add it to the fill or stop

I'm pretty sure your "extra logic" is a predicate that can be abstracted away into a function. (Are the neighbours the same height as this value?) Now, doing that in Cython instead of Python is hard, but not impossible. Can we leverage the LowLevelCallable machinery from SciPy to provide this option? That would be super exciting!

**Comment by JDWarner** [comment]
I will put up a basic but serviceable 2D flood fill in Cython by tomorrow, so improvements can be back ported into 0.14.

**Comment by stefanv** [comment]
@JDWarner Would you be able to base this off of @lagru's version, so we don't do the entirely naive uint8 `==` check?
