### ISSUE TITLE
[RFC] CI tests examples in travis

### ISSUE THREAD

**Issue by glemaitre** [scikit-image/scikit-image#2894]
Isn't an overkill to always run the examples for all travis build.
When building the documentation, sphinx-gallery will anyway run the different examples and this build will fail for sure if there is any issue the same way that the other builds are failing nowadays.
It would also reduce the testing time I think on the CI. And it would also avoid some issue with the requirement as discussed at https://github.com/scikit-image/scikit-image/pull/2848#issuecomment-346581618

WDYT?

**Comment by stefanv** [comment]
Problem is, you really need to run these examples on all the various 
platforms, because users copy and paste from the gallery into all versions 
of Python. We can't rely on a 3.6 pass to make it work elsewhere.

But, no problem for your PR, we can just install  the docs dependencies for 
each matrix entry.

**Comment by glemaitre** [comment]
Ok thanks for the clarification
