### ISSUE TITLE
Which is the best folder to place a new file containing a custom data structure implementation?

### ISSUE THREAD

**Issue by xavecoder** [scikit-image/scikit-image#2901]
Hello, everyone.
Actually, this is a question, not an issue.

I'm a PhD student at medical image processing and I'm too excited in contributing to skimage.
I intend to implement some new graph-based techniques for image processing and analysis, then I'm gonna to implement (in Cython) a priority queue optimized for image processing.

**Which is the best folder to place a new file containing a data structure?**

**Comment by JDWarner** [comment]
Welcome!  In general, if the support files are specific to the new feature without likely re-use they can live in that directory (seems like you would be targeting `skimage.graph` at least in part) and simply not be exposed publicly.  Consider `skimage._shared` if they might be useful to multiple submodules but not exposed for general use.  If helper functions would also be useful as public functions, either `skimage.util` or `skimage.graph` could be appropriate depending on their generality.

**Comment by emmanuelle** [comment]
Hello @xavecoder welcome! Also, before preparing your pull request I'd recommend that you discuss the new feature here on GitHub (for example in the current issue). In order to keep the API short and simple, we tend to limit the number of new algorithms, so that the added value of a new feature must be clear and well documented/discussed.
