### ISSUE TITLE
Can denoise_wavelet be used to 1D time series?

### ISSUE THREAD

**Issue by Landau1908** [scikit-image/scikit-image#2974]
Hi,

Can denoise_wavelet be used to 1D time series?
When I denoise a time series, the returned is all zeros. What happened?

Thanks

**Comment by Landau1908** [comment]
Sample code.
```python
from skimage.restoration import denoise_wavelet
import pywt
ecg = pywt.data.ecg()
ecg_skimage = denoise_wavelet(ecg, sigma=2.86, wavelet='sym5', wavelet_levels=6)
```

**Comment by jni** [comment]
Hi @Landau1908!

It is indeed possible! In fact if you `plt.plot(ecg_skimage)`, you'll see that you don't have all zeros at all, just very tiny numbers.

You've been bitten, as so many have, by scikit-image's implicit type conversions:

http://scikit-image.org/docs/dev/user_guide/data_types.html

We convert your input data, which is int32, to float, by dividing by the maximum int32, which is `2**31 - 1`. That's why your resulting array has such tiny values.

Here's what I get when I try:

```python
In [13]: plt.plot(ecg)
Out[13]: [<matplotlib.lines.Line2D at 0x1324afb00>]

In [14]: plt.plot(ecg_skimage * (2**31 - 1))
Out[14]: [<matplotlib.lines.Line2D at 0x12b5848d0>]
```
![figure_1](https://user-images.githubusercontent.com/492549/36769723-4181b74e-1c9a-11e8-8886-4aab645638e4.png)

Not sure that's very good denoising, but you can tweak the parameters now instead of trying to figure out what went wrong. =)

We definitely need to figure out how to make our data type conversions friendlier. If you have any ideas, please add them to this issue, or raise a new one:

https://github.com/scikit-image/scikit-image/issues/1234

In the meantime I'll close this one. Thanks! (And thank you very much for the sample code, I would have been unable to debug your problem without it!)
