### ISSUE TITLE
Loading truncated images (difference between repl and script)

### ISSUE THREAD

**Issue by CMCDragonkai** [scikit-image/scikit-image#2989]
## Description

When loading a big geotiff. I noticed that in a python script `skimage.io.imread` would fail with:

```
OSError: image file is truncated (55156 bytes not processed)
ValueError: Could not load "/home/cmcdragonkai/Projects/image-numpy-conversion/images/2.tif" 
Reason: "image file is truncated (55156 bytes not processed)"
Please see documentation at: http://pillow.readthedocs.org/en/latest/installation.html#external-libraries
```

However the same code works when just using the python repl.

The solution was to use:

```
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
```

Which is sort of a leaky abstraction. My dependency is on `scikit-image` not pillow. Perhaps this code should be put into `scikit-image`?

But also I'm wondering why there's a difference in behaviour between repl and script.

Scikit version: 0.12.3 Python 3.6

**Comment by stefanv** [comment]
skimage supports various plugins for loading images, of which PIL is one.  Can you try `io.imread(..., plugin='imageio')` and see whether that helps?

**Comment by soupault** [comment]
@CMCDragonkai do you have any updates on this matter?

In my opinion, it would be quite cumbersome for `skimage` to expose all configuration option of all the underlying image I/O libraries. At least, we currently do not have enough manpower to maintain this extensive abstraction layer. If you need something specific, it is better to have a direct control over I/O process by using the corresponding libs.
In addition to the above, we are planning to switch completely to `imageio` in several releases - https://github.com/scikit-image/scikit-image/issues/1605.

**Comment by emmanuelle** [comment]
Could you please
- try with a newer version of scikit-image
- and if it still does not work, upload the image and a snippet of code so that we can reproduce the problem?

**Comment by stefanv** [comment]
I suspect that the original image was malformed, which is why the PIL flag helped.

**Comment by CMCDragonkai** [comment]
Apologies, I cannot share the image due to licensing. My main concern was leaky abstractions. Usually this could be resolved by capturing underlying exceptions and also exposing the config via some explicit plugin parameters.

**Comment by stefanv** [comment]
We don't want to enable loading of truncated images by default, and while we have the capability to pass arguments to the underlying image I/O library, I don't think that is a good general API to imread either. The option exists to use PIL directly, which in this case may be warranted; we ingest NumPy arrays for exactly this reason, that you don't have to be tied to the library (which hopefully has sensible defaults!) when there are special requirements. Another factor to consider here is that we may soon be switching to imageio as a backend, where reading truncated images may not be supported at all.

Wrt the script vs repl difference: that should never be the case. If you can reliably reproduce that, I'd like to hear more. 

Since there was a sensible error message, and the situation cannot easily be improved, I'm opting to close. But I am appreciative of your opening the issue, instead of simply accepting the library's behavior as a given.
