### ISSUE TITLE
Appveyor doesn't test `--doctest-modules`

### ISSUE THREAD

**Issue by hmaarrfk** [scikit-image/scikit-image#3094]
## Description
Appveyor doesn't run pytest with `--doctest-modules`. This skips certain tests that we check against for Linux and Mac.

**Comment by soupault** [comment]
This is going to be addressed in #3854

**Comment by hmaarrfk** [comment]
The reason is that windows does a bad job at finding the conftest file.

I feel like it is an appropriate compromise

**Comment by soupault** [comment]
>The reason is that windows does a bad job at finding the conftest file.

Whoa! Could you elaborate on that? I feel that I'm facing the same issue in https://github.com/scikit-image/scikit-image/pull/3854. It seems that pytest must be able to find the file (as it is in the package root), but somehow it doesn't happen.

**Comment by hmaarrfk** [comment]
This is definitely the issue. Basically don't bother running doctests on windows.

Or documentation. Just do all that on linux, the same kind of machines that the devs of the doc tools use.

**Comment by soupault** [comment]
xref #3873

**Comment by soupault** [comment]
Due to this formatting issue in `numpy` - https://github.com/numpy/numpy/issues/13468, a decision has been made not to complicate the examples for the sake of additional testability - https://github.com/scikit-image/scikit-image/pull/3873#issuecomment-488633647, https://github.com/scikit-image/scikit-image/pull/3873#issuecomment-488771578.

`--doctest-modules` will not be used for Windows builds.
