### ISSUE TITLE
basic error

### ISSUE THREAD

**Issue by vimal-honest** [scikit-image/scikit-image#3101]
Hi,
     i'm new to programming and getting this error, help me to rectify.

Type Error: must be real number, not str

example; 
from sklearn import svm
from sklearn import datasets
clf = svm.SVC(gamma='scale')
iris = datasets.load_iris()
X, y = iris.data, iris.target
clf.fit (X, y)

vimalrajm@ssn.edu.in

**Comment by jni** [comment]
Hi @vimal-honest,

Note that this is the scikit-image project, while you are asking about the scikit-learn project. They are different.

Anyway, usually Python also provides the line where the error happened. In your case it's in `clf = svm.SVC(gamma='scale')`. If you look at the documentation for `svm.SVC` (you can do this with Google or by typing `help(svm.SVC)` in Python), you will see that `gamma` must be a number, not a string. (The string 'auto' is allowed, but only because it has special meaning for this particular function.)

**Comment by vimal-honest** [comment]
thank you @jni

**Comment by adhishnanda** [comment]
I changed the Gamma from 'Scale' to 'Auto' and it worked. Thanks @jni .
