### ISSUE TITLE
Morphological Chan-Vese inverts foreground to background relationship

### ISSUE THREAD

**Issue by derekthirstrup** [scikit-image/scikit-image#3183]
## Description
The morphological chan-vese module appears to swap the foreground object to background relationship with some image stacks. I have not been able to track down the root cause of this issue.  It appear to be related to checkerboard initial level set size but changing this parameter does not resolve this issue for all 3D image stacks. @AetherUnbound

[If reporting a bug, attach the entire traceback from Python.]
[If proposing an enhancement/new feature, provide links to related articles, reference examples, etc.]

## Way to reproduce
[If reporting a bug, please include the following important information:]
- [ ] Code example
- [X] Relevant images (if any)
- [ ] Operating system and version
- [ ] Python version
- [X] scikit-image version 14 (run `skimage.__version__`)

![image](https://user-images.githubusercontent.com/20077409/41309701-58552e9c-6e34-11e8-91cd-35d88a934479.png)

**Comment by soupault** [comment]
\cc @pmneila

**Comment by emmanuelle** [comment]
The screenshot is from CellProfiler, is it using scikit-image's morphological Chan-Vese? Could you please post a minimal code example showing the problem, so that we can reproduce it? Thanks!

**Comment by pmneila** [comment]
If I understood correctly, the problem here is that sometimes the inside area of an object is segmented as `background` and the outside as `foreground`. In that case, this is expected behavior. The concepts of _inside_ and _outside_ are completely arbitrary and interchangeable in this task.

What determines which parts of the image will be _inside_ and _outside_ is the initialization of the contour. It is expected that the user will provide a _good_ initialization with a large proportion of the inside area in the `foreground` part of the level-set and vice versa. The checkerboard initialization pattern is not a _good_ initialization in this sense, and you might get inverted foreground/background depending on the distribution of objects in the image.

Does this solve the issue? Did I understand the question correctly?

**Comment by AetherUnbound** [comment]
Thank you both for the explanations! I think that does sufficiently answer our questions about this algorithm :) Neither of us were aware of the interchangeability of `foreground`/`background` - this is very helpful to know moving forward.

This issue can be closed (@derekthirstrup can confirm if you'd like)
