### ISSUE TITLE
Missing cval parameter in threshold_local

### ISSUE THREAD

**Issue by ggirelli** [scikit-image/scikit-image#3230]
## Description
Maybe I am missing something, but I cannot set the `cval` parameter when using mode `constant` with `threshold_local`.

`TypeError: threshold_local() got an unexpected keyword argument 'cval'`

## Way to reproduce
Tried with both v0.13.1 and v0.14.0. It is missing also from the API documentation of 0.15dev so I am not sure if it got fixed yet (if a bug at all) and it does not appear in the source code either.

Thanks! :)

**Comment by jni** [comment]
You are absolutely right, we don't currently allow passing cval through to the underlying padding function!

Incidentally, you can infer what arguments are allowed from the documentation:
http://scikit-image.org/docs/dev/api/skimage.filters.html#threshold-local

If you look at the function signature, there is no mention of cval.

Would you like to submit a pull request adding the argument? Otherwise we will get to this eventually, but I don't know when.

**Comment by ggirelli** [comment]
Good to know. If I have time to work on this over the weekend I will set up a pull request. Thanks for the prompt reply! :)
