### ISSUE TITLE
memory leak? transform.resiz and rgb2gray

### ISSUE THREAD

**Issue by drag1flye** [scikit-image/scikit-image#3232]
## Description
[Please provide a general introduction to the issue/proposal.]
I believe 2 functions, transform.resize and rgb2gray, may have memory leaks.
[If reporting a bug, attach the entire traceback from Python.]
My  code:
def all_gray_all_same_size( images):
    # Rescale the images in the `images` array
    images28 = [transform.resize(image, (400, 400)) for image in images]

    images28 = np.array(images28)
    # Convert `images28` to grayscale
    images28 = rgb2gray(images28)
    return images28

It worked fine for a small data set. For a data set of 24000 jpg images (approx. 4 GB of data), it ended up using all 128 GB of RAM and crashing. I could watch the RAM usage going up and up and up over several minutes. The output was OOM (out of memory). I am running on a Linux supercomputer node with 28 processors and 128 GB of RAM.

Here's the relevant info:
Software
python/3.6 cuda/8.0.44
Hardware:
Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
OS:
Linux 3.10.0-693.25.7.el7.x86_64
scikit image version: 0.13.0
## Way to reproduce
[If reporting a bug, please include the following important information:]
- [ ] Code example
- [ ] Relevant images (if any)
- [ ] Operating system and version
- [ ] Python version
- [ ] scikit-image version (run `skimage.__version__`)

**Comment by jni** [comment]
Hi @drag1flye!

Is it 4GB on disk or 4GB uncompressed? (Uncompressed would imply that your images are of size 120 x 120 x 3 channels.) If it's on disk, then that's the mystery solved: jpeg compression can be 5-10x, so that's actually a 20GB uncompressed dataset.

Now, to do the RGB to gray computation, we convert the dataset to floating point (to avoid precision loss; see details [here](http://scikit-image.org/docs/dev/user_guide/data_types.html)). So it goes from 8bit per pixel to 64 bit per pixel, a factor of 8. That gets us to 160GB.

Can you provide some more complete code? (Including input and output steps.) Typically for a large dataset like this one, one would prefer processing image by image or in batches. Happy to help you with that.

**Comment by hmaarrfk** [comment]
@drag1flye I've been dealing with similar issues with (sets of) large images.

My suggestion would be to cast things as float (of your desired precision), as early as possible. 

That said, it won't fix the problem because until PR #3110, any float would simply be upcast to float64 in many internal functions. This #3186 backported the fix to v0.14.1 but there is no ETA (as far as I know) about the release date.

I would suggest that you checkout the v0.14.x branch and compile it yourself.
If you use conda, make sure you install v0.14.0 first, and uninstall it, that way conda still manages all your dependencies.

Now for rgb2gray specifically, it didn't used to use matrix multiply before PR #3187 in (0.15) and  PR #3193 in (0.14.1) so you might get an added speedup for that particular function by living on the 0.14.x branch.

Note that the numpy code should do OK with float16, but many algorithms seem to be written in Cython and aren't compiled for float16, so I wouldn't try float16 unless you really need to.

I don't know of a good way to do rgb2grey without having floating point numbers. If you have an idea, I am totally interested in seeing it in action!

**Comment by drag1flye** [comment]
Thank you all for the helpful comments. I did not know that jpg files would puff up like a sponge in memory! 
Juan, below is my function to load the data, it's pretty basic.
As a workaround, I used imagemagick convert as a preprocessing step, but I'm glad to know this info because I might like to try the Haar function (in which case I will try working in batches and casting as you all suggested)

# returns a list of images and a list of labels for those images.
# the labels are the classification of each image (basically
# the directory name where it was stored)
def load_data(data_directory, file_extension):
    directories = [d for d in os.listdir(data_directory)
                   if os.path.isdir(os.path.join(data_directory, d))]
    labels = []
    images = []
    for d in directories:
        label_directory = os.path.join(data_directory, d)
        file_names = [os.path.join(label_directory, f)
                      for f in os.listdir(label_directory)
                      if f.endswith("." + file_extension)] 
        for f in file_names:
            images.append(skimage.data.imread(f))
            labels.append(int(d))
    return images, labels

Then in main I call my functions:
   images, labels = aux.load_data(train_data_directory, "jpg")
   file1.write("Images loaded!!!!\n")

   images = np.array(images)
   labels = np.array(labels)
   file1.write("Image and label np arrays created\n")

   images28 = aux.all_gray_all_same_size( images) # PROBLEM: not working for large data set

**Comment by drag1flye** [comment]
```
def load_data(data_directory, file_extension):
        directories = [d for d in os.listdir(data_directory)
                if os.path.isdir(os.path.join(data_directory, d))]
        labels = []
        images = []
        for d in directories:
                label_directory = os.path.join(data_directory, d)
                file_names = [os.path.join(label_directory, f)
                        for f in os.listdir(label_directory)
                        if f.endswith("." + file_extension)] 
        for f in file_names:
                images.append(skimage.data.imread(f))
                labels.append(int(d))
        return images, labels


def all_gray_all_same_size( images):
        # Rescale the images in the images array
        images28 = [transform.resize(image, (400, 400)) for image in images]
        # Convert `images28` to an array
        images28 = np.array(images28)
        # Convert `images28` to grayscale
        images28 = rgb2gray(images28)
        return images28
Inside main, call functions:
   images, labels = aux.load_data(train_data_directory, "jpg")
   file1.write("Images loaded!!!!\n")

   images = np.array(images)
   labels = np.array(labels)
   images28 = aux.all_gray_all_same_size( images)
```

**Comment by hmaarrfk** [comment]
@drag1flye regarding your first few questions, I don't think there is a memory leak in `rgb2grey`. To my knowledge, it is a pure python function which simply adds things together.

Transform resize calls `scipy.ndimage.guassianfilter` so if there is a memory leak, it might be in there.
But to actually prove you had a memory leak in the function, you would have to show that this function crashes your computer:

```python
import numpy as np
from skimage.transform import resize
img = np.zeros((1000, 1000))
for i in range(10000000):
     resize(img, (100, 100))
```

In this example, you are just analysing a single image, and that would indicate that everytime you call the function, a little bit more memory is allocated.


That said, your example doesn't show the memory leak as much as you are hitting your memory limit of your super computer. This is quite common!
This is because:
1. You are loading ALL your images
2. You convert ALL the images to grey
3. At the end of the script, both the original images and the grey images are in memory.

I would suggest creating a function, that looks like

```python
def load_image_as_grey_same_size(filename):
    image = skimage.io.imread(filename)
    image = transform.resize(image, (400, 400))
    image = rgb2gray(image)  # in 0.13, this always returns a 64bit float
    image = img_as_float32(image)  # Optional: set to your desired precision
    return image
```
that way, when you load your images, only one full image is kept in memory at a time. 
Your images are quickly resized, and the full image is discarded without creating a giant list of them.


PS. The correct place to import imread from is `skimage.io` and not `skimage.data`. `data` is more for the `skimage` supplied data.

**Comment by jni** [comment]
> I did not know that jpg files would puff up like a sponge in memory!

😂 

Regarding your dataset size, since you are resizing your images to a single size, it's straightforward to compute the amount of memory needed: n_images * height * width * dtype_bytes. (The last number is 1 for uint8 images, 8 for float64, and 4 for float32.) That's the *bare minimum*, and things like a machine learning model etc. will also take up space in memory and need to be accounted for. For large dataset sizes, I strongly recommend you look at incremental machine learning in batches. See this document from scikit-learn:

http://scikit-learn.org/stable/modules/scaling_strategies.html#incremental-learning

which links to a relevant example classifying text documents:

http://scikit-learn.org/stable/auto_examples/applications/plot_out_of_core_classification.html

Obviously you are in a different field, but the relevant concepts should be similar. TensorFlow, Keras, PyTorch, etc, all have facilities for incremental machine learning.

To make your life easier I would first do a single pass saving the images in the correct format to disk, then I would do a second learning pass. Note that as pointed out in the above document, for many models, you will need to make sure that your first batch of images contains all target labels.

I'm going to close this issue as I don't think we have a memory leak, but do feel free to continue the discussion here.

**Comment by hmaarrfk** [comment]
I'm just going to say, I was just bitten by the fact that some functions upconvert to the float64 today. :D fun times finding that!!!
