### ISSUE TITLE
Wrong matrix calculation for shear angle in `AffineTransform`

### ISSUE THREAD

**Issue by UlrichBernert68** [scikit-image/scikit-image#3239]
## Description

The convenience method of constructing an affine transform by providing a shear angle creates a wrong internal transform matrix - the diagonal elements should be 1.0 and in the second column it isn't. The -tan(angle) value is also wrong (apparently mis-scaled the same way as the diagola element.

## Way to reproduce

```python
import numpy as np
from skimage import transform
import math as m

angle = 0.2

shear_transform = transform.AffineTransform(shear=angle)
print("shear-convenience-constructor:")
print(shear_transform.params)
print()

matrix = np.array([[1.0, -m.tan(angle), 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]])
affine_transform = transform.AffineTransform(matrix=matrix)
print("correct matrix constructor:")
print(affine_transform.params)
```

**Comment by hmaarrfk** [comment]
Wolfram would say you are right:
http://mathworld.wolfram.com/Shear.html

This line of code and the documentation say it is explicit @ahojnnes 
https://github.com/scikit-image/scikit-image/blob/d3b8b6c296bd40ec15c23f38894156133745c6d9/skimage/transform/_geometric.py#L717-L724
https://github.com/scikit-image/scikit-image/blob/d3b8b6c296bd40ec15c23f38894156133745c6d9/skimage/transform/_geometric.py#L777-L780

Shear should not be a 1D parameter should it? I feel like you should have shear_x shear_y? or shear `(y, x)` (well `(x, y)` because the transform module is anti-python)

For reference, opencv doesn't provide a shortcut for shear
https://docs.opencv.org/3.0-beta/doc/py_tutorials/py_imgproc/py_geometric_transformations/py_geometric_transformations.html

**Comment by thomasaarholt** [comment]
I've written a notebook ([HTML](https://thomasaarholt.github.io/affine_transforms/affine.html#skimage.transform.warp) [IPYNB](https://thomasaarholt.github.io/affine_transforms/affine.ipynb) that demonstrates how the shear transform is incorrect (as well as a bunch of other peculiarities with how Affine Transforms are applied in python).

The relevant discussion is [here](https://thomasaarholt.github.io/affine_transforms/affine.html#skimage.transform.warp) (scroll up one paragraph for some discussion). The following image shows the problem, scikit-image implementation at the bottom:

![image](https://user-images.githubusercontent.com/2721423/103412216-4e7c7180-4b74-11eb-8e7c-b3ff056b6c8d.png)

**Comment by thomasaarholt** [comment]
The `matplotlib.transforms.Affine2D()` function works very well as a substitute. Since skimage has matplotlib as a dependency, maybe one should just use that library instead? As documented in my notebook above, with the exception of the erroneous `shear` function, the implementation is identical (and supports chaining operators, which is nice).
