### ISSUE TITLE
rgb2gray() and blob_dog() 

### ISSUE THREAD

**Issue by astro313** [scikit-image/scikit-image#3252]
Hi, 

I am using skimage versions 0.14.0. I am trying to use `blob_dog` inside skimage.feature. It seems like the the function works on both gray 2D or 3D arrays, so I used `rgb2gray()` before parsing the arrays into `blob_dog`.

But then the output of `rgb2gray()` is a 2D image, but I thought that one can supply 3D arrays into `blob_dog` (as in the documentation). So does that mean that the input array doesn't need to be in grayscale (but the documentation says blob_dog works on grayscale image)? 

Since I was confused, I did a quick comparison on the output of `blob_dog()`: 
```
from skimage.color import rgb2gray
from skimage.feature import blob_dog, blob_log
import matplotlib.pyplot as plt
import numpy as np
from skimage import data

blob2d = data.binary_blobs(length=128, n_dim=2)
blob3d = data.binary_blobs(length=128, n_dim=3)
print blob3d.shape
blob3d_gray = rgb2gray(blob3d)
print blob3d_gray.shape
# ok... after passing through rgb2gray, it collapsed into 2D....

# is running through rgb2gray() necessary before running skimage blob_dog?

# test dog 2d
blobs_dog = blob_dog(blob2d) 
print blobs_dog
blobs_dog = blob_dog(rgb2gray(blob2d))
print blobs_dog
# -- whether or not running rgb2gray() doesn't actually affect blob_dog() operation, at least on 2D image

# test dog 3d
blobs_dog = blob_dog(blob3d)
print blobs_dog
print blob3d.shape
blobs_dog = blob_dog(rgb2gray(blob3d))
print blobs_dog
print rgb2gray(blob3d).shape

```
In the 3D case where the input is `blob3d` and `rgb2gray(blob3d)`, an empty list is returned for the former, but a non-empty list is returned in the latter:

```
[]
(128, 128, 128)
[[  40.        127.         16.777216]
 [   0.         38.         16.777216]]
(128, 128)
```

So, I was wondering what is the proper syntax for running blob_dog() on a 3D cube? 

Thanks.

**Comment by GenevieveBuckley** [comment]
Hi @astro313 
This is the kind of question that would be great for the [scikit-image tag](https://stackoverflow.com/questions/tagged/scikit-image) on StackOverflow! You're also likely get a lot more eyes on your problem there.

The syntax to call blob_dog is the same, regardless of the number of dimensions your input grayscale image has. The input array doesn't need to be 2D but it does need to be grayscale, otherwise you might get results that weren't what you'd intended/expected.

It's not clear what kind of input image data you have. I'm guessing most likely 2D RGB images, since you ask about [`rgb2gray`](http://scikit-image.org/docs/0.14.x/api/skimage.color.html#skimage.color.rgb2gray)? Images like that would appear as a numpy array of shape `(y_dimension, x_dimension, 3)`, where the three planes are the red, green and blue channel intensities, respectively. The data you've loaded in the example above `binary_blobs` is binary (boolean type numpy array), not color or grayscale - so it doesn't make a ton of sense to apply the [`rgb2gray` function](http://scikit-image.org/docs/0.14.x/api/skimage.color.html#skimage.color.rgb2gray) on it. 

Assuming that is the case, here's an example with a 2D color image as input:
```python
from skimage import io, data
from skimage.color import rgb2gray
from skimage.feature import blob_dog

astronaut = data.astronaut()
gray_astronaut = rgb2gray(astronaut)
blobs = blob_dog(gray_astronaut)
print(blobs)
```
```
[[442.         358.          10.48576   ]
 [377.         250.          42.94967296]
 [373.         451.          16.777216  ]
 [360.           0.          26.8435456 ]
 [356.         399.          16.777216  ]
 [196.           0.          26.8435456 ]
 [194.         511.          42.94967296]
 [192.         344.          42.94967296]
 [138.         215.          26.8435456 ]
 [111.         117.          42.94967296]
 [  0.         336.          42.94967296]
 [  0.         113.          42.94967296]]
```
I also suspect you're running into issues (empty lists being returned) because you haven't figured out the best values for the [blob_dog keyword arguments](http://scikit-image.org/docs/0.14.x/api/skimage.feature.html#skimage.feature.blob_dog) appropriate for your data. It can be helpful to lower the threshold value while you troubleshoot.

**Comment by GenevieveBuckley** [comment]
Yes, `blob_dog` and `blob_log` can both handle a data cube of size (128, 128, 128). 

The docs are a little misleading here - it doesn't look like they've been updated to reflect the fact n-dimensional input is ok, not only 2D or 3D data. I'll put in a note for someone to update the docs in the next release. (FYI: they determinant of hessian algorithm, `blob_doh` is still  2D only.)

```python
>>> import numpy as np
>>> from skimage.feature import blob_dog, blob_log
>>> np.random.seed(0)
>>> array_shape = (128, 128, 128)
>>> image = np.random.random(array_shape)
>>> blobs = blob_dog(image, threshold=0.1)
>>> len(blobs)
192
>>> blobs
array([[127. , 125. ,  16. ,   1. ],
       [127. , 112. ,  91. ,   1.6],
       [127. , 110. ,  93. ,   1. ],
       [127. ,  87. ,  99. ,   1. ],
       [127. ,  74. ,  86. ,   1. ],
       [127. ,  74. ,  56. ,   1. ],
       [127. ,  71. , 107. ,   1. ],
       [127. ,  49. ,  70. ,   1. ],
       [127. ,  47. ,  99. ,   1. ],
       [127. ,  22. ,  24. ,   1. ],
       [127. ,  16. , 126. ,   1.6],
       [127. ,  10. , 119. ,   1. ],
       [127. ,   5. ,  45. ,   1. ],
       [127. ,   2. ,  21. ,   1. ],
       [127. ,   0. ,  51. ,   1.6],
       [126. , 127. ,  43. ,   1. ],
       [125. ,  54. ,  13. ,   1. ],
... data truncated, I'm not going to copy all 192 lines in here.
```
Since this image array is just random noise, it's not too suprising that the blobs we find are generally all very small (sigma = 1. or 1.6).

**Comment by GenevieveBuckley** [comment]
Hm, actually maybe I'm wrong about nd support for `blob_dog` and `blob_log`? @jni, can you confirm this? (If it's n-dimensional, I can update the docstrings)

* There is no warning raised if you feed a 5D image to either function, and
* I swear I remember having a conversation with @jni about this before
but,
* The pull request for https://github.com/scikit-image/scikit-image/pull/2854 is very specific about writing "2D or 3D" in multiple places, so I assume there is a good reason for that specificity.

**Comment by jni** [comment]
Yes, looking at the changes from #2854, our `blob_dog` and `blob_log` code is 2D or 3D only currently. That's because `_prune_blobs` computes the overlap between discs (2D) or spheres (3D) but not higher-dimensional blobs. Having said that, both should work fine with 3D grayscale blobs. It does not make sense to run `rgb2gray` on that data. It also does not make sense that `rgb2gray` doesn't complain when given a (128, 128, 128) volume!

@astro313 have we answered your question? I'm going to close this issue, but please feel free to ask us for more clarification if you need it.
