### ISSUE TITLE
tool for benchmark coverage

### ISSUE THREAD

**Issue by abarya** [scikit-image/scikit-image#3327]
## Description
As we are writing benchmarks for our project, it is quite necessary to know what parts of over code are actually covered by benchmarks, as @jni suggested at gitter.

I think a similar tool like pytest-cov would work in this situation.

@stefanv @soupault @jni. Please review. 

[If reporting a bug, attach the entire traceback from Python.]
[If proposing an enhancement/new feature, provide links to related articles, reference examples, etc.]

## Way to reproduce
[If reporting a bug, please include the following important information:]
- [ ] Code example
- [ ] Relevant images (if any)
- [ ] Operating system and version
- [ ] Python version
- [ ] scikit-image version (run `skimage.__version__`)

**Comment by abhishekarya286** [comment]
I have started working on it. Currently, I'm using `pytest` only to get the coverage. I have done this by modifying `Makefile` and adding a setup.cfg file to look at `benchmark/` directory for running the appropriate functions.

**Comment by abhishekarya286** [comment]
I have completed its implementation and will push the codes tomorrow. I just have a small doubt. After the pytest is run, it prints a summary like this`=========================== 1 passed in 0.01 seconds =========================` which is actually for tests and not for benchmarks and this thing is hardcoded in pytest and they don't offer a functionality as of now to modify this message. Can we modify our own copy of pytest to make this message look different when we run tests and benchmarks and then supply this pytest with scikit-image?

**Comment by hmaarrfk** [comment]
@abhishekarya286 does this make pytest run the benchmarks once? 

The benchmarks could be quite long since we sometimes have to test the performance on large arrays that don't fit in the cache (which today is pretty large).

Regarding `pytest`: I would bring this issue up with upstream. 
I don't think we should fork/version pytest just for an internal message. A simple message would be to print an explanation just after the output.
