### ISSUE TITLE
Request: make dask[array] an optional dependency

### ISSUE THREAD

**Issue by mdickinson** [scikit-image/scikit-image#3410]
In #2494, `dask` was made an optional dependency; in #2572, it was removed from `requirements.txt` (following #2571).

It looks as thought for version 0.14.0, `dask` is back to being a [required dependency](https://github.com/scikit-image/scikit-image/blob/master/requirements/default.txt) again. Was this an oversight when the `requirements.txt` file was refactored, or is `dask` now considered to be a required dependency of `scikit-image`?

(Background and motivation: Enthought packages `scikit-image` for EDM and Canopy, and the `dask` dependency turns `scikit-image` into quite a heavyweight package; if we can reasonably declare that `dask` is an optional dependency, we'd be quite happy to do so. :-)

**Comment by mdickinson** [comment]
From some digging, it looks as though `dask` was reintroduced as a required dependency in #2647: https://github.com/scikit-image/scikit-image/pull/2647#issuecomment-341017541

**Comment by hmaarrfk** [comment]
The depenency is on dask[array], which is 3 packages, numpy (check), dask (pure python) and toolz.

I don't think there is much dask in scikit-image today.

**Comment by mdickinson** [comment]
Ah, thank you. I'd missed that depending on `dask[array]` doesn't imply depending on all of `dask`. That's helpful.

**Comment by stefanv** [comment]
Currently we depend on it for cycle spinning and apply_parallel.

We presumed this would be a very light dependency (https://github.com/scikit-image/scikit-image/pull/2647#issuecomment-341192030).  If that assumption is wrong, we could make it optional again, but @mdickinson it sounds as though it is not problematic for you if it is only `dask[array]`?

**Comment by mdickinson** [comment]
> it sounds as though it is not problematic for you if it is only `dask[array]`?

Yes, agreed that the `dask[array]` dependency seems very reasonable. As it turns out, it _is_ problematic for us, because our build system doesn't (currently) support partial dependencies like `dask[array]`, so we end up pulling in all the `dask` dependencies. But I think that's clearly our problem, not yours. :-)

Thank you for the quick responses! My question's answered, so I'll close this.

**Comment by hmaarrfk** [comment]
@mdickinson I would reopen this, and maybe change the title to "Request: make dask[array] an optional dependency"

I think removing the dask dependency is a reasonable request. On conda for example, the scikit-image now pull in all of dask, which also makes the scikit-image package huge. 

Packaging is imperfect. I would support PRs that would aim at isolating the dask dependency from the rest of the code-base. I presume the changes would be small.

I've been trying to split off dask on conda-forge into smaller packages, but how that is done exactly seems to be tricky due to `dask[distributed]`.

https://github.com/conda-forge/dask-feedstock/pull/49

**Comment by jni** [comment]
@hmaarrfk here you go. =) Super happy for skimage to increase the pressure for partial dependencies support in conda, though. =P

**Comment by rth** [comment]
Aside from `utils.apply_parallel` which appears fairly standalone, dask seems to be currently used only in 1 place (cf #3582). +1 for making it an optional dependency.
I imagine the cloudpickle mandatory dependency (that isn't used unless I'm missing something) is also due to dask?

This would also make packaging it in pyodide easier https://github.com/iodide-project/pyodide/issues/253

Also conda dependency solver is quite slow, so these 4 dependencies (here dask-core, toolz, cloudpickle + cytoolz (on conda-forge)) is also something that might have a small impact on install time, which is particularly problematic for CI (and if other libraries start adding optional dependencies as requirements).

**Comment by hmaarrfk** [comment]
I think conda taking for ever to solve on conda forge is because it downloads the whole file list everytime. You can try adding `--offline` and most of the time, due to local caching, your commands will work.
