### ISSUE TITLE
Imsave is slow with png files

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#3419]
Hi,

I recently tried to change the library to save a massive input of images and I discovered poor performances. I moved from cv2 to imageio, and there is a factor 16 with default options on png files. I opened this issue: https://github.com/imageio/imageio/issues/387

The reason of this issue is to check the impact on skimage users.
Here is the result (similar for skimage 0.14.0) ([code to generate that](https://gist.github.com/sciunto/766ff6fd43f55b074eebd3685a4d758d))

```
imageio version  2.3.0
cv2 version  3.4.3
skimage version  0.15.dev0
imageio png (default compression level):  8.053008476999821
imageio png (3 compression level):  0.8025189930049237
imageio png (0 compression level):  0.4413930820010137
skimage png imageio plugin:  8.059267696997267
skimage png imageio plugin, compresslevel=3:  0.8436357580067124
skimage png pil plugin:  2.095269728990388
cv2 png:  0.36305642800289206
imageio jpg:  0.4091900839994196
cv2 jpg:  0.22913011600030586
skimage jpg imageio plugin:  0.4576459030067781
skimage jpg pil plugin:  0.45544222500757314

```

Two remarks that came to my mind:
* first, we do not ensure homogeneous default behavior regarding the different plugins, e.g. the compression level. As the API are very different, it is not so easy.
* we can take an action to enhance our user experience: **set a reasonable default compression level if not specified by the user.**

Any opinion?

**Comment by jni** [comment]
@sciunto I'm 100% behind the idea that both Tiff and png should have compression by default. As to jpg, iirc we have a very high quality default, but I like that, because jpg artifacts are the worst, *especially* in scientific applications.

But png and tiff compression is lossless, so we should definitely turn it on with a sensible default. Plus, my understanding is that compression + small IO can actually be much faster than large IO for some files, because CPUs are mostly sitting idle these days.

Regarding a unified API: this one is tricky, because different formats from different domains use different terminology. I don't think compress=9 works as an API for jpeg, and certainly quality=95 does not work for png/tiff.

**Comment by sciunto** [comment]
OK. I propose to [test it](https://gist.github.com/sciunto/1edd33b542ff549772cec0ab1340d73b).

First run, with `data.camera()`
```
imageio version  2.3.0
cv2 version  3.4.3
skimage version  0.15.dev0
writing duration | reading duration | filesize
skimage png imageio plugin:  0.19641820500022733 0.004123164960183203 111.55 KB
skimage png imageio plugin comp=3:  0.01676760592032224 0.004298711200244725 124.07 KB
skimage png imageio plugin comp=0:  0.007933206600137055 0.0025485366804059596 256.65 KB
```

Second run for `data.hubble_deep_field()`
```
imageio version  2.3.0
cv2 version  3.4.3
skimage version  0.15.dev0
writing duration | reading duration | filesize
skimage png imageio plugin:  0.2599139772797935 0.039727148240199316 1.58 MB
skimage png imageio plugin comp=3:  0.16205140431993642 0.043063775079790506 1.68 MB
skimage png imageio plugin comp=0:  0.0903911562007852 0.024831591559341178 2.5 MB
```
In both cases, zero compression is faster to read and to write.

**Comment by sciunto** [comment]
Closing. looks like you and upstream prefer to use massively CPU power...

**Comment by hmaarrfk** [comment]
FWIW: I also noticed that png was taking a LONG time to compress and wasn't
always giving great compression results. I was probably using imageio
directly though.
