### ISSUE TITLE
Build suggestion: add circle-CI docs preview to pull requests

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#3483]
Another suggestion from following @choldgraf on twitter, who is on :fire: :fire: :fire:.

See his blog post here for instructions: 

https://predictablynoisy.com/circle-documentation-build

We've had a couple of docs formatting issues recently so I think this would be super-valuable.

**Comment by hmaarrfk** [comment]
https://github.com/scikit-image/scikit-image/issues/2269

**Comment by choldgraf** [comment]
FWIW, using circle *only* for building documentation can keep it relatively maintenance-free. Usually I still build the documentation in Travis, so use that to make sure it builds on all the different python versions etc, and use Circle *only* to preview the built documentation (which usually is "just" a matter of copypasting the code in that blog post into the `config.yml` file, and modifying it so that it has the environment needed to build the docs)

**Comment by soupault** [comment]
Closing as a duplicate.
