### ISSUE TITLE
Cython guidelines: discouraging the word `float`

### ISSUE THREAD

**Issue by hmaarrfk** [scikit-image/scikit-image#3496]
## Description
I was going through the cython code for one reason or an other and found many places where the type `float` was being specified. The issue is that `float` in Python (64bit precision) doesn't map to the C/C++ float (32 bit precision). Cython being the bridge between these two languages means it becomes very confusing to know if this is a 32bit precision float or 64bit precision float. I'm not even able to completely understand the [Cython documentation on this matter](https://cython.readthedocs.io/en/latest/src/userguide/language_basics.html#types). It seems that `float` might even mean 32bit in a `cdef`

See for example:
https://github.com/scikit-image/scikit-image/blob/a966c99ca10eb6dfa014d961e3b576c1c4c967b3/skimage/segmentation/_felzenszwalb_cy.pyx#L16
https://github.com/scikit-image/scikit-image/blob/a966c99ca10eb6dfa014d961e3b576c1c4c967b3/skimage/segmentation/_felzenszwalb_cy.pyx#L94

The link above is only an example of what I found searching on github, and I'm not really saying that anything is `wrong` with this code, but more that we've had a few bugs in cython where there were mismatched types and avoiding this kind of word might go a long way toward fixing this kind of problem.

ccing @grlee77 since you reviewed my last cython PRs.

**Comment by grlee77** [comment]
I agree that `float` can be a bit ambiguous when working with Cython.

In a cdef statement, `float` is indeed a 32-bit C float.

To verify this, you can look at the `_felzenszwalb_cy.c` output from `cythonize` and see the generated code:
```C
  float __pyx_v_inner_cost0;
  float __pyx_v_inner_cost1;
```
corresponding to the C declarations of `inner_cost0` and `inner_cost1`. 

I don't see any corresponding declaration for `cost`, perhaps because that particular variable seems to be unused and could be removed from the cdef.

Similarly, typecasting a pointer with `<float*>` also means a 32-bit C-style float

However, one counterexample seems to be calling `float()` like in the following, where it does seem to mean a Python-style float (i.e. C `double`) precision.
https://github.com/scikit-image/scikit-image/blob/a966c99ca10eb6dfa014d961e3b576c1c4c967b3/skimage/segmentation/_felzenszwalb_cy.pyx#L53

**Comment by hmaarrfk** [comment]
Yeah, it is pretty ambiguous what happens in that case. It could be that it gets silently upcast????

I forgot to mention my suggestion: I would stick with numpy dtypes everywhere:
```
cimport numpy as cnp

cnp.float64_t
```
is pretty unambiguous

I would also consider `np.float` ambiguous.

I personally consider the words `char`, `short` and `int` pretty ambiguous when describing data types too (even in pure-C code). For counters, fine.

**Comment by stefanv** [comment]
Since we're living more in Python-land than in C-land, I think this is a sensible suggestion.  I presume `cnp.float64_t` maps directly to `double`?
