### ISSUE TITLE
visual_test.py should be run in the test suite

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#3705]
Currently, visual_test.py is explicitly ignored.  It should be run at least in Travis-CI matrix entries with matplotlib and xvfb available.

**Comment by cgohlke** [comment]
Probably it's better not to run the visual_test.py script in the test suite:

1) it requires the visvis package
2) it is interactive
3) it loads Qt libraries into the process
4) it requires decent OpenGL
5) it crashes on my system when run via RDP, probably because the OpenGL in RDP is not sufficient.
6) it looks like the donuts are already part of the [tests](https://github.com/scikit-image/scikit-image/blob/50eef35a59f3ba3d74ba773c642f3c0d2d5c5486/skimage/measure/tests/test_marching_cubes.py#L149)

> visual_test.py is explicitly ignored

It is still picked up by pytest when testing an inplace build. I'll submit a cleaned up script that will not interfere with pytest.

**Comment by stefanv** [comment]
Good points; I was frustrated at seeing a bug-fix to a piece of code not in the test suite (seems likely that it would be there, doesn't it).  But, given the 6 points above, the issue is misplaced.

**Comment by hmaarrfk** [comment]
This is the reason why the viewer was supposed to be moved out of
scikit-image isn't it?

Having the analysis and vis code seperated would enable more targetted
tested (and less backward compatibility) for this kind of GL stuff.

**Comment by stefanv** [comment]
On Tue, 05 Feb 2019 12:09:58 -0800, Mark Harfouche wrote:
> This is the reason why the viewer was supposed to be moved out of
> scikit-image isn't it?
> 
> Having the analysis and vis code seperated would enable more targetted
> tested (and less backward compatibility) for this kind of GL stuff.

Yes, and I think it is better suited for projects like Napari.

I think we still ship `skivi`, but I haven't tried using it in years.

**Comment by cgohlke** [comment]
The `visual_test.py` script is not part of skivi. I submitted #3732 such that the script will no longer interfere with running pytest on an inplace build.

**Comment by cgohlke** [comment]
> 5\. it crashes on my system when run via RDP

Looks like that is a bug in PyOpenGL
