### ISSUE TITLE
feature.blob_(log|dog) bug with 3D images

### ISSUE THREAD

**Issue by eric-czech** [scikit-image/scikit-image#3777]
## Description

When using 3D images with```feature.blog_dog``` or ```feature.blob_log``` and a sequence argument for min and max sigma, the sigmas are converted from indexes back to their original values (as in [here](https://github.com/scikit-image/scikit-image/blob/2962429237988cb60b9b317aa020ca3bab100b7f/skimage/feature/blob.py#L301)) and stacked horizontally (as in [here](https://github.com/scikit-image/scikit-image/blob/2962429237988cb60b9b317aa020ca3bab100b7f/skimage/feature/blob.py#L308)) to give an array with 3 spatial coordinates and 3 sigma values.  This is then passed to ```_prune_blobs``` which selects all but the last column for the KDTree construction (```spatial.cKDTree(blobs_array[:, :-1])```) meaning that the tree is considering 3 spatial coordinates and 2 out of 3 sigma values for distance calculations, which seems to be a mistake.

## Way to reproduce
NA

## Version information
master branch

**Comment by jni** [comment]
@eric-czech thanks for the report and sorry that it's taken us so long to respond! I imagine this bug was introduced when adding support for anisotropic sigma (#3690). Prior to that, we were discarding the unique sigma, now we are only discarding the final sigma out of `ndim`. So I guess this is failing *also* for 2D now!

The fix would be to replace that `-1` with `-ndim`, and add tests to make sure this is not repeated in the future!

**Comment by jni** [comment]
Investigating this now... The code is still correct for isotropic data, because we discard the extra columns of `sigmas_of_peaks` if `scalar_sigma` is true. So that's a relief!

**Comment by jni** [comment]
... For anisotropic data, it's a whole world of pain. We actually don't have a method for computing overlap volumes between ellipsoids, or even [overlap areas between ellipses](https://math.stackexchange.com/questions/1346903/how-to-calculate-the-surface-of-overlapping-ellipsoids). Amusingly/horrifyingly, our code for computing overlaps [uses `else:` to signify "not 2D",](https://github.com/scikit-image/scikit-image/blob/2962429237988cb60b9b317aa020ca3bab100b7f/skimage/feature/blob.py#L122-L126) then proceeds to compute the overlap between two spheres, regardless of the dimension of the input data. For LOG are also not actually blurring the image with the anisotropic sigma but rather the [mean of the sigmas](https://github.com/scikit-image/scikit-image/blob/2962429237988cb60b9b317aa020ca3bab100b7f/skimage/feature/blob.py#L426-L429), which is... a strange choice??? I think it's a bug that comes from trying to combine blurring and scaling into one loop, rather than two steps [as done in DOG](https://github.com/scikit-image/scikit-image/blob/2962429237988cb60b9b317aa020ca3bab100b7f/skimage/feature/blob.py#L278-L283).

... What a mess. Fixing this...!
