### ISSUE TITLE
incorrect ssim result?

### ISSUE THREAD

**Issue by johnnychen94** [scikit-image/scikit-image#3942]
Hi all, I'm recently playing with ssim, and find out that the ssim result is not numerically equal to the original implementation.

scikit-image: `0.13.1`
```python
In [1]: from skimage import io, measure

In [2]: img1 = io.imread("lena_gray_512.tif")

In [3]: img2 = io.imread("cameraman.tif")

In [4]: measure.compare_ssim(img1, img2, gaussian_weights=True, sigma=1.5, use_sample_covariance=False)

Out[4]: 0.35229376382502575
```

> To match the implementation of Wang et. al. [1]_, set `gaussian_weights`
to True, `sigma` to 1.5, and `use_sample_covariance` to False.

* The [original code](http://www.cns.nyu.edu/~lcv/ssim/ssim_index.m) returns `0.3526` (`Matlab R2018b`)
* [`tensorflow.image.ssim`](https://www.tensorflow.org/api_docs/python/tf/image/ssim) returns `0.35255808` (`v 1.13.1`)

Best

**Comment by stefanv** [comment]
Sounds like there is something not perfectly right; perhaps the Gaussian weights are slightly different, sigma is not squared, or something similar.  Can you help us investigate?  I consider this a bug in our implementation.

**Comment by grlee77** [comment]
I think this was fixed for the 0.15.0 release by #3802.

I tried with those images as obtained [here] ((https://github.com/JuliaImages/TestImages.jl/tree/gh-pages/images))
and get a value of 0.3525792531186188 which matches the result you reported from Matlab

**Comment by grlee77** [comment]
I am going to close the issue, but please reopen if you find there is still an inconsistency when using the latest release.

**Comment by johnnychen94** [comment]
@grlee77 that's great, thanks for the fix!

BTW, could you help check if the default return value of `measure.compare_ssim(img1, img2)` ≈ `0.3595`? I had some issue installing scikit-image from the source, saying `ImportError: cannot import name 'geometry'`

I'm making some choices in Julia-version SSIM on whether we should crop the boundary of `ssim_map` before `mean(ssim_map)`. See https://github.com/JuliaImages/ImageQualityIndexes.jl/pull/3/files#r289122499, it would be great if you could provide some feedback.

**Comment by hmaarrfk** [comment]
to help you get up and running on master, try to clean the repo. `git clean -xfd` should remove all stray files. Make sure you commit any files first.


```
In [1]: from skimage import io, measure 
   ...:                                                                                                 

In [2]: img1 = io.imread("lena_gray_512.tif")                                                           
/home/mark2/git/scikit-image/skimage/io/manage_plugins.py:210: UserWarning: The dtype argument was always silently ignored. It will be removed from scikit-image version 0.17. To avoid this warning, do not specify it in your function call.
  return func(*args, **kwargs)

In [3]: img2 = io.imread("cameraman.tif")                                                               
/home/mark2/git/scikit-image/skimage/io/manage_plugins.py:210: UserWarning: The dtype argument was always silently ignored. It will be removed from scikit-image version 0.17. To avoid this warning, do not specify it in your function call.
  return func(*args, **kwargs)

In [4]: measure.compare_ssim(img1, img2, gaussian_weights=True, sigma=1.5, use_sample_covariance=False) 
Out[4]: 0.35257925311861882

In [5]: measure.compare_ssim(img1, img2)                                                                
Out[5]: 0.31985470768239194
```

**Comment by grlee77** [comment]
> I'm making some choices in Julia-version SSIM on whether we should crop the boundary of ssim_map before mean(ssim_map) by default.
See https://github.com/JuliaImages/ImageQualityIndexes.jl/pull/3/files#r289122499, it would be great if you could provide some feedback.

I don't have a strong opinion on that. As you highlight there, it seems to vary across implementations. The skimage implementation has cropping so that it gives a value closely matching the original author's Matlab implementation (but apparently not Matlab's built-in SSIM)

**Comment by grlee77** [comment]
The default without any keyword arguments is using different filter (non-Gaussian), so I wouldn't expect it to closely match the other implementations.  We could potentially change the default to more closely match these other implementations, but that would create a backwards compatiblity issue, requiring a warning for a couple of releases prior to making the change.

**Comment by tomsan61065** [comment]
Hello, I am new to the SSIM, but I'm not sure is the default SSIM setting has a problem or just I misunderstood the SSIM.

```
from skimage import img_as_float
from skimage import img_as_ubyte
X = np.zeros((80,512, 512), dtype=np.uint8)
Y = np.zeros((80,512, 512), dtype=np.uint8)

for i in range(1, 81):
    img = cv2.imread("...", cv2.IMREAD_GRAYSCALE)
    X[i-1] = img
    img = cv2.imread("...", cv2.IMREAD_GRAYSCALE)
    Y[i-1] = img

for i in range(80): 
    #SSIM: 0.5114699011236234
    #totalSSIM += measure.compare_ssim(Y[i], X[i]) 
    #print(i+1, measure.compare_ssim(Y[i], X[i]) )
    
    #SSIM: 0.5114699011236234 
    #totalSSIM += measure.compare_ssim(img_as_ubyte(img_as_float(Y[i])), img_as_ubyte(img_as_float(X[i]))) 
    #print(i+1, measure.compare_ssim(img_as_ubyte(img_as_float(Y[i])), img_as_ubyte(img_as_float(X[i]))) ) 
    
    #SSIM: 0.6623636208041587
    #totalSSIM += measure.compare_ssim(img_as_float(Y[i]), img_as_float(X[i])) 
    #print(i+1, measure.compare_ssim(img_as_float(Y[i]), img_as_float(X[i])) )
    
    #SSIM: 0.5114699011236248
    totalSSIM += measure.compare_ssim(img_as_float(Y[i]), img_as_float(X[i]), data_range=1.0) 
    print(i+1, measure.compare_ssim(img_as_float(Y[i]), img_as_float(X[i]), data_range=1.0) )
print(totalSSIM/80)
```
but is it correct to have a different result with different datatype(change from uint8 to float)?
uint8 data range will be "255-0", to float will be converted to "1.0 - (-1.0)" but not "255/255 - 0/255"?

**Comment by grlee77** [comment]
As you have correctly identified, this is a case of bad inference of the data range. Internally `dtype_range` indicates a range of `dmax=1`, `dmin=-1` so `data_range = dmax - dmin = 2` while the actual data does not have negative values because it was converted from uint8. 

For the `uin8` case `dmax=255`, `dmin=0` and the internal conversion to float is done without rescaling to integer range, so this remains correct.

A potential fix would be to use `dmax - 0.0` instead of `dmax - dmin` for floats when the reference image does not have any values < 0. In other words:
```Python
if X.dtype.kind == 'f' and X.min() >= 0:
    data_range = dmax - 0.0
```

Manual specification of the `data_range` argument as in your last case above will avoid the issue in the meantime.

**Comment by grlee77** [comment]
Another usage which will end up being incorrect if `data_range` is not specified, is when floats are scaled to a larger or smaller amplitude range than [-1., 1.]. For example, for data in range [0, .001] the assumed data range of 2 will result in artificially high SSIM values. 

This is probably more likely to occur in recent releases where `img_as_float` no longer automatically rescales the range of floating point inputs.

```Python
import skimage
import skimage.datta
from skimage.measure import compare_ssim

c = skimage.img_as_float(skimage.data.coins())  # values within [0, 1.0]

cn = c + 0.1*np.random.randn(*c.shape) 

print(compare_ssim(c, cn, data_range=1.0))  # correct range manually specified
# 0.38001096385239175

print(compare_ssim(c, cn))  # will determine range 2.0 internally
# 0.48671320187302375

print(compare_ssim(0.001*c, 0.001*cn))  # will determine range 2.0 internally
# 0.999996706012675
```

The fix proposed in the prior comment would not address the overall scaling case or the case where the noisy input was passed as the first argument. (i.e. `cn` does have values slightly outside [0, 1.0] due to the random noise, so `X.min() >= 0.0` would be false and range 2.0 would still be used).

**Comment by johnnychen94** [comment]
I'm not familiar with skimage, but I thought the dynamic value range of float image should be `1-0` instead of `1-(-1)`? 🤔 Is there any particular reason to do so? 

https://github.com/scikit-image/scikit-image/blob/cba1798f0246ee465db2f0ab04fd4e12163ec0c8/skimage/util/dtype.py#L27-L29

It's said under eq. (7) in [1]: 

> where L is the dynamic range of the pixel values (255 for 8-bit grayscale images)

[1] Wang, Z., Bovik, A. C., Sheikh, H. R., & Simoncelli, E. P. (2004). Image quality assessment: from error visibility to structural similarity. _IEEE transactions on image processing_, 13(4), 600-612.

**Comment by UtR491** [comment]
I don't know if this is the right place to ask this question, but why do the [answers from the original MATLAB implementation](https://ece.uwaterloo.ca/~z70wang/research/ssim/) by Wang et al differ from the answers given by the current function in MATLAB? Is this because the MATLAB implementation would use truncated Gaussian filter or something else? I am sorry if I am missing something obvious. Thanks in advance!

**Comment by stefanv** [comment]
@grlee77's suggestion above on calculating a more typical data range seems like a good workaround for now.

**Comment by grlee77** [comment]
@UtR491
One apparent difference was noted in https://github.com/scikit-image/scikit-image/issues/3942#issuecomment-497692455

Basically, when computing the mean SSIM over the image, the implementations may differ in whether some pixels near the boundary are excluded from the computation.

**Comment by UtR491** [comment]
@stefanv Thank you so much for the quick response and @grlee77 thank you for the much needed clarification. I should have read the thread more carefully.
