### ISSUE TITLE
support nD arrays in skimage.filters.rank

### ISSUE THREAD

**Issue by d-v-b** [scikit-image/scikit-image#3955]
## Description

Currently the rank filters are all 2D-only; it would be great if these filters worked for nD-arrays. I don't know the underlying code well at all (if I did, this would be a PR...); is there anything blocking these filters working in higher dimensions, besides the fact that nobody has written the code?

**Comment by stefanv** [comment]
No, if anything I think the rank filters benefit you even more in 3D. We'd 
love a PR.


I also noticed that the current implementation could do with some better 
internal documentation. Eg, the "pop" variable should clearly be delineated 
as "population", not "queue pop".

**Comment by d-v-b** [comment]
Having looked at the code a bit more, the [core moving-histogram code](https://github.com/scikit-image/scikit-image/blob/master/skimage/filters/rank/core_cy.pyx#L45) is _very_ specific to the number of dimensions -- in the current code, there are several instances where 1 variable is defined per dimension; converting this to N dimensions seems tricky. Can you recommend any good examples of cythonized nD-filtering that I could use as a reference?

**Comment by grlee77** [comment]
nD support is still missing, but 3D support was added by #4435. As mentioned above, refactoring to a general nD case would be a decent amount of work. I'm not sure if there are sufficient number of use cases beyond 2D and 3D to justify this?

We will likely have an nD version of this for GPUs in [cuCIM](https://github.com/rapidsai/cucim) at some point. That is mainly because, for cuCIM, I would start by adapting kernels from out `cupyx.scipy.ndimage` rank filters code which is already nD.
