### ISSUE TITLE
Divergent results in threshold_multiotsu with 16bits images

### ISSUE THREAD

**Issue by btguilherme** [scikit-image/scikit-image#3975]
## Description
Hello,
I was testing the function with tomograph images, 16 bit (uint16), and memory error occurred:

`[...] scikit-image\skimage\filters\thresholding.py", line 1107, in <listcomp>
 momP, momS, var_btwcls = [np.zeros((nbins, nbins)) for n in range(3)]
MemoryError`

One solution found was to modify [these lines](https://github.com/scikit-image/scikit-image/blob/master/skimage/filters/thresholding.py#L1093-L1096) to `hist, bin_centers = np.histogram (image.ravel (), bins = nbins)` and `prob = hist / len (bin_centers)`, that is, use the default function in numpy to calculate the histogram.

Despite this, there is another (more important) problem where the threshold values found differ from those found in the SimpleITK and MatLAB libraries.

An example using a single image, I received the following values (3 classes, 2 thresholds):

SimpleITK: (12443, 29469)
MatLAB: (12491, 29802)
Skimage: (26629, 33177)

I was unable to upload the test image, but it is available at this link: [https://www.digitalrocksportal.org/projects/35/origin_data/85/](https://www.digitalrocksportal.org/projects/35/origin_data/85/)

 (note: although it says that the images are 8-bit, they are actually 16-bit).

## Way to reproduce
```python
# code to reproduce MemoryError

from skimage.filters import threshold_multiotsu
import numpy as np
import pytiff

names = ['AT CARB_0.7 Micron scan_recon_Export0001.tiff']

imgs = np.empty((1, 1008, 980), np.uint16)
for i, fpath in enumerate(names):
    with pytiff.Tiff(fpath) as handle:
        for page in handle.pages:
            imgs[i] = page[:]

print(threshold_multiotsu(imgs))
```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
# your output here
3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)]
Windows-10-10.0.17134-SP0
scikit-image version: 0.16.dev0
numpy version: 1.16.2
```

**Comment by sciunto** [comment]
Thank you for the detailed report. I Cc @alexandrejaguar who is the leading author of this, to bring him in the loop.

**Comment by cgohlke** [comment]
Re MemoryError: I'm not sure this algorithm is suited for 16 bit data (i.e. using 16-bit histograms). Runtime and memory usage are excessive. To work around this, convert the data to floating point first.

Runtime can be significantly improved by Cythonizing the calculation of the variance between classes, e.g.
```diff
diff --git a/skimage/filters/_multiotsu.pyx b/skimage/filters/_multiotsu.pyx
index 6e1a2668a..552840f0a 100644
--- a/skimage/filters/_multiotsu.pyx
+++ b/skimage/filters/_multiotsu.pyx
@@ -8,6 +8,44 @@ cimport numpy as cnp
 cimport cython
 from itertools import combinations

+
+def _init_var_btwcls(double [::1] prob, double [:, ::1] var_btwcls):
+    """Initialize variance between classes array."""                                                                   +    cdef:
+        ssize_t u, v
+        ssize_t nbins = prob.size
+        double [:, ::1] momP  # zeroth moments, cumulative probability
+        double [:, ::1] momS  # first moments, mean
+
+    momP = np.zeros_like(var_btwcls)
+    momS = np.zeros_like(var_btwcls)
+
+    # building the lookup tables.
+    # step 1: calculating the diagonal.
+    for u in range(1, nbins):
+        momP[u, u] = prob[u]
+        momS[u, u] = u * prob[u]
+
+    # step 2: calculating the first row.
+    for u in range(1, nbins-1):
+        momP[1, u+1] = momP[1, u] + prob[u+1]
+        momS[1, u+1] = momS[1, u] + (u+1)*prob[u+1]
+
+    # step 3: calculating the other rows recursively.
+    for u in range(2, nbins):
+        for v in range(u+1, nbins):
+            momP[u, v] = momP[1, v] - momP[1, u-1]
+            momS[u, v] = momS[1, v] - momS[1, u-1]
+
+    # step 4: calculating the between class variance.
+    for u in range(1, nbins):
+        for v in range(u+1, nbins):                                                                                    +            if (momP[u, v] != 0):
+                var_btwcls[u, v] = momS[u, v] * momS[u, v] / momP[u, v]
+            else:
+                var_btwcls[u, v] = 0
+
+
 def _find_threshold_multiotsu(double [:, ::1] var_btwcls,
                               Py_ssize_t classes,
                               Py_ssize_t bins):
diff --git a/skimage/filters/thresholding.py b/skimage/filters/thresholding.py
index a20055fa6..d2a0bc504 100644
--- a/skimage/filters/thresholding.py
+++ b/skimage/filters/thresholding.py
@@ -8,7 +8,7 @@ from ..exposure import histogram
 from .._shared.utils import assert_nD, warn, deprecated
 from ..transform import integral_image
 from ..util import crop, dtype_limits
-from ..filters._multiotsu import _find_threshold_multiotsu
+from ..filters._multiotsu import _find_threshold_multiotsu, _init_var_btwcls


 __all__ = ['try_all_threshold',
@@ -1097,35 +1097,10 @@ def threshold_multiotsu(image, classes=3, nbins=256):
     # histogram ignores nbins for integer arrays.
     nbins = len(bin_centers)

-    # defining arrays to store the zeroth (momP, cumulative probability)
-    # and first (momS, mean) moments, and the variance between classes
-    # (var_btwcls).
-    momP, momS, var_btwcls = [np.zeros((nbins, nbins)) for n in range(3)]
-
-    # building the lookup tables.
-    # step 1: calculating the diagonal.
-    for u in range(1, nbins):
-        momP[u, u] = prob[u]
-        momS[u, u] = u * prob[u]
-
-    # step 2: calculating the first row.
-    for u in range(1, nbins-1):                                                                                        -        momP[1, u+1] = momP[1, u] + prob[u+1]
-        momS[1, u+1] = momS[1, u] + (u+1)*prob[u+1]
-
-    # step 3: calculating the other rows recursively.
-    for u in range(2, nbins):
-        for v in range(u+1, nbins):
-            momP[u, v] = momP[1, v] - momP[1, u-1]
-            momS[u, v] = momS[1, v] - momS[1, u-1]
-
-    # step 4: calculating the between class variance.
-    for u in range(1, nbins):
-        for v in range(u+1, nbins):
-            if (momP[u, v] != 0):
-                var_btwcls[u, v] = momS[u, v]**2 / momP[u, v]
-            else:
-                var_btwcls[u, v] = 0
+    # defining array to store the variance between classes.
+    var_btwcls = np.zeros((nbins, nbins))
+
+    _init_var_btwcls(prob, var_btwcls)

     # finding max threshold candidates, depending on classes.
     # number of thresholds is equal to number of classes - 1.

```

**Comment by sciunto** [comment]
I looked at it briefly. So, we have a 16bits uint image. Therefore, the value of nbins is ignored (as documented) and the number of bins is huge (2^16).

Proposed fix: convert the input image to a float dtype such that the nbins value is never ignored. Otherwise, in this situation, the user might have difficulties to do so.

This raises the question to maintain or not the nbins behavior in skimage.exposure.histogram.

**Comment by hmaarrfk** [comment]
2^16 is not huge anymore. Might be worth allowing users to specify nbins, but the default set to old value?

`sqrt( 2 ^ 16) = 256`. so it is as large as a 256 x 256 image.

**Comment by alexdesiqueira** [comment]
Hi @btguilherme @cgohlke,
I am checking the code now, and it relates to #3980. I would need a little time to check how to solve this.
@hmaarrfk the algorithm I based this on is aimed to `int` images. I guess @sciunto is right: `int16` is a no-go for this one, specifically.

**Comment by rfezzani** [comment]
@hmaarrfk, the problem is that the actual implementation allocates 3 arrays of shape 2^16×2^16, and that is huge...
I refactored `threshold_multiotsu` in #4178. In this implementation, the memory use is reduced to 1 array of shape 2^16×2^16 and 2 with shape 2^16. But this is still too large and a `MemoryError` is still raised.
I then proposed to disable the LookUp table approach that requires the 2^16×2^16 array allocation. This way, only two arrays with 2^16 elements are allocated, but more computations is performed. No more `MemoryError` is raised and the result on @btguilherme use case is now `[12649, 29834]`.
May be you can have a look @alexdesiqueira at #4178 and give a review?

**Comment by hmaarrfk** [comment]
rank filters use 10 bit images. Maybe inspire from that?

**Comment by rfezzani** [comment]
Hi @hmaarrfk, I am not sure to understand what you mean :-(. `threshold_multiotsu` is an implementation of [[1]](http://ftp.iis.sinica.edu.tw/JISE/2001/200109_01.pdf) that uses lookup tables to save a large amount of floating point operations needed to compute all possible between-class  variance. This LUT will be at least of shape `(nbins, nbins)` where `nbins` is number of bins used for computing the histogram of the input image.
Infortunatly, `skimage.exposure.histogram` ignores the `nbins` parameter when the input image has integer dtype, that's why the LUT table is huge for 16bit images!
The LUT is an upper triangular, so the storage for its lower triangular part can be saved (`nbins*(nbins-1)/2` zeros) at the cost of some extra index manipulations... But I don't think that this is enough memory saving.
Some other memory optimization could be the use of single precision instead of double precision floats...

**Comment by rfezzani** [comment]
My last commits to #4178 implement the memory optimizations described above:
- use single precision instead of double precision
- remove the lower triangular part of the LUT
I did not observed any performance modification ;-)
