### ISSUE TITLE
Broken images in 0.15.x documentation of image segmentation

### ISSUE THREAD

**Issue by bebosudo** [scikit-image/scikit-image#3976]
## Description
Hi, I've noticed that some images are blank/black-filled in the documentation of image segmentation, only for release 0.15.x (stable at the time of this writing), while in 0.14.x or older they are present.
The missing images are only "Canny detector", "filling the holes" and "removing small objects".

Broken: https://scikit-image.org/docs/0.15.x/user_guide/tutorial_segmentation.html
Working: https://scikit-image.org/docs/0.14.x/user_guide/tutorial_segmentation.html

Screenshot of the missing pictures:
![Screenshot_2019-06-25_00-30-38](https://user-images.githubusercontent.com/1922124/60056312-c7c61900-96e0-11e9-932d-e2b185402a21.png)

Don't know whether is somewhat related to #3853.

**Comment by jni** [comment]
@bebosudo thank you very much for the report! Actually this was fixed in master (https://scikit-image.org/docs/dev/user_guide/tutorial_segmentation.html) and backported to 0.15, so it will be fixed in the 0.15.x page as soon as we release 0.15.1. See #3913 and #3919 for details.

I'm going to close this as it is solved in master. But again, thank you for reporting!
