### ISSUE TITLE
`skimage.filters.gaussian` doesn't use `output` parameter at all

### ISSUE THREAD

**Issue by snasibli** [scikit-image/scikit-image#4014]
## Description
`skimage.filters.gaussian` doesn't use the value of `output` parameter. It returns only the image of float64 dtype, even if explicitly specify the output dtype. 

## Way to reproduce
Simply run the code snippet:
```python
from skimage.filters import gaussian
import numpy as np

image = np.arange(25, dtype=np.uint8).reshape((5,5))

# output is not specified
filtered_0 = gaussian(image, sigma=0.25)
print(filtered_0.dtype)
# return: float64

# output is specified
filtered_output = gaussian(image, output = np.uint8, sigma=0.25)
print(filtered_output.dtype)
# return: float64
```
This function is a wrapper around `scipy.ndi.gaussian_filter`. But the scikit-image `gaussian` doesn't pass the `output` to `scipy.ndi.gaussian_filter`.

**Comment by hmaarrfk** [comment]
Indeed this is a bug. Would you like to provide the patch in a PR that would:
1. Remedy this issue?
2. Add a test so that it doesn't get reintroduced as a bug in the future?

**Comment by snasibli** [comment]
Yes, I would. I think i can investigate it

**Comment by rfezzani** [comment]
I think that this bug has some subtleties: first of all, the example provided by @snasibli, is not  really correct since `gaussian`'s [doc]( https://scikit-image.org/docs/dev/api/skimage.filters.html?highlight=gaussian#skimage.filters.gaussian) specifies that `output` should be an `array`, and this is not checked.
Moreover, `gaussian` uses the `preserve_range` parameter, which is used by the `convert_to_float` function, meaning that internally, the input image will converted to float what ever output dtype is.
One fix would be, if `output` is provided, to first check if it is an array, then, according to input image `dtype` check if `output` dtype is compatible with `convert_to_float` output type, and finally to pass `output` as argument to `ndi.gaussian_filter`.

**Comment by samir-nasibli** [comment]
@rfezzani Thank you for your review. My changes were based on [previously](https://github.com/scikit-image/scikit-image/pull/4026#discussion_r351067796) agreed requirements.
I have update my PR according your comments.

**Comment by samir-nasibli** [comment]
@stefanv @soupault @jni @hmaarrfk. I was working on this #4329 [PR](https://github.com/scikit-image/scikit-image/pull/4329) for fixing this bug. Please review.
