### ISSUE TITLE
Documentation: signatures at the top (table of contents) of draw module missing parameters

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#4046]
## Description

I don't know whether this is by design, but if you look at the table of contents of the draw module (and I presume others), the signature for `draw.circle_perimeter` is missing parameters such as `shape`. Perhaps it is by design, but imho there should at least be a ... to indicate that there are more parameters:

https://scikit-image.org/docs/dev/api/skimage.draw.html#module-skimage.draw

**Comment by sciunto** [comment]
I think the ... means that some args are not displayed, but kwargs are always hidden in the TOC.

**Comment by jni** [comment]
@sciunto that sounds like a terrible thing as we move to more keyword-only arguments. Also, not entirely accurate, as `draw.circle` does show the `shape` optional keyword argument in square brackets.

**Comment by lagru** [comment]
With #6714 merged, the table of contents no longer includes signatures (e.g. see [`skimage.draw`](https://scikit-image.org/docs/dev/api/skimage.draw.html)). I disabled signatures there, because in my opinion it didn't really help with readability and much of the signature was truncated anyway. 

I'm closing this issue for now. But feel free to reopen if you would like to re-enable signatures.
