### ISSUE TITLE
travis has random failures on rank filters

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#4052]
## Description

See for ex: https://travis-ci.org/scikit-image/scikit-image/jobs/563363217

## Way to reproduce
```python
# Place the full code we need to recreate your issue here
# upload all necessary images to github too!
```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
# your output here

```

**Comment by jni** [comment]
@sciunto this is incredibly surprising behaviour???? But I have now seen it with my own eyes so I have no choice but to believe it. Does anyone @scikit-image/core have any ideas???

**Comment by hmaarrfk** [comment]
Yeah. I think it is because warning filters are not thread safe. 

There is something about filters being added on a stack, and that the stack can get wildly out of control if multiple threads are touching it.

We may want to use a fixture to disable warnings all together during the multithreaded tests ( I think rank uses that crazy multi threaded stuff right)
