### ISSUE TITLE
Local Otsu - Challenges in getting it to work with Lenna

### ISSUE THREAD

**Issue by sdg002** [scikit-image/scikit-image#4058]
## Description
I was trying out the region based segmentation using the Local Otsu algorithm described here
https://scikit-image.org/docs/stable/auto_examples/applications/plot_thresholding.html#sphx-glr-auto-examples-applications-plot-thresholding-py

Everything works fine with the inbuilt demo pictures. When I tried on the Lenna sample image, I faced some challenges.

![Lenna](https://user-images.githubusercontent.com/20245330/61981467-b29b1d80-aff1-11e9-99f4-95b3b02144bd.png)

![image](https://user-images.githubusercontent.com/20245330/61982087-8bdde680-aff3-11e9-8f34-13158b0f6d8d.png)

## Way to reproduce

Download the sample code from here https://scikit-image.org/docs/stable/auto_examples/applications/plot_thresholding.html#sphx-glr-auto-examples-applications-plot-thresholding-py

Replace the 

```python
#
#Load inbuilt sample image
#
img = img_as_ubyte(data.page())
```

```python
#
#Load from external file
#
filename="C:\\Lenna.png"
imagefromfile=io.imread(filename)
img= rgb2gray(imagefromfile)`
```

The resulting picture in the Matplotlib is a black window. Global works well. But, region based failed.

## Workaround
I found that rescaling the gray scale image to 255 works well.

```python
#
#Rescale the pic to 255 if already normalized 
#
filename="C:\\Lenna.png"
imagefromfile=io.imread(filename)
img= rgb2gray(imagefromfile)`
if image.max() <= 1:
    image=image * 255

```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
# your output here
3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
Windows-10-10.0.17134-SP0
scikit-image version: 0.15.0
numpy version: 1.16.1
Backend TkAgg is interactive backend. Turning interactive mode on.
```

I have solved my problem. However, I would really appreciate if somebody from the team could kindly explain what was going wrong and why scaling the pixel intensities from 1.0 to 255 solved the problem? 

Thanks,
Sau

**Comment by jni** [comment]
Hi @sdg002!

First, let me note that we removed Lena from our examples gallery because of concerns that some contributors might find its origin off-putting. (It is a crop from a Playboy magazine, if you didn't know.) Since sexism in tech and especially in open source is a massive problem (see e.g. [here](https://www.wired.com/2017/06/diversity-open-source-even-worse-tech-overall/)), it is worth being mindful of this history and using other test images to experiment. There is nothing magical about the Lena picture that requires its use to demonstrate image processing problems!

In your case, the problem arises because of the `offset=10` parameter in the example. You should always note parameter values and how they might affect your particular problem. Rescaling the image, as you did, is equivalent to setting `offset=10/255`, which is the correct approach for float (0-1) images. You could also leave out the offset parameter altogether for this image, I think. See the [documentation for threshold_local](https://scikit-image.org/docs/stable/api/skimage.filters.html#skimage.filters.threshold_local) for more info.
