### ISSUE TITLE
SKIP: use black to format our code?

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#4111]
## Description

[black](https://github.com/psf/black) is a recent but robust tool for code formatting. There is a conference available from [pycon](https://youtu.be/esZLCuWs_2Y).

* black is compliant with PEP8. 
* It can be [automatized](https://github.com/psf/black#version-control-integration) on our repository
* black is available in many editors as well.
* black has been adopted by several projects already like [these](https://github.com/psf/black#used-by)
* you can [**test it**](https://black.now.sh/)

I like the default format except the systematic transformation of single quotes to double quote. This can be avoided with an option. Besides that, I'm happy with it.

The **main advantage** I see is to avoid comments during code reviews about formatting.

**Comment by hmaarrfk** [comment]
> It can be automatized on our repository

I don't even know what a pre-commit hook is. This is something that contributors needs to install on their cloned repo right?

**Comment by sciunto** [comment]
it's a way to run a script before the commit is effective. Black must be installed by the contributor.

**Comment by JDWarner** [comment]
Juan brought up Black at SciPy as well.  There are some good ideas in Black but I'm not sure Black is ready for us/we are ready for Black.  Black seems more for general purpose Python, not as ideally suited to scientific Python (also supported by the projects currently using it).  Juan entertained forking Black and improving it in a few ways to make it more palatable; not sure how serious he was about that.

As exhibit A: Have you tried to apply it to our repository?  There are an incredible number of changes, many of which are in tests (larger embedded arrays with nonstandard formatting basically required so they appear correct in the file for maintainability).  

We have long equations and more complex code routinely found where we actually follow PEP8 where PEP8 [tells you to ignore its own rules where doing so improves readability](https://www.python.org/dev/peps/pep-0008/#id15). Ergo despite claiming PEP8 compatibility Black has no provision for this part of PEP8, which I personally consider to be at the core of the very spirit of PEP8.

I also personally find inline call chains more readable and easier to follow than the multiple enforced line breaks Black requires, but recognize that may be more a personal style than a truism.  NumPy equation style sometimes results in more than one `.dot()` or similar call in a chain, and I think Black would decrease readability by breaking that into a bunch of lines.

Bigger picture it seems like a solution in search of a problem.  PEP8 fixes are trivial for even the newest of contributors, and are already automatically pointed out, so I'm not convinced Black would reduce barriers or maintainer burden significantly.

**Comment by hmaarrfk** [comment]
> Black must be installed by the contributor.

This is basically a non starter for me.

**Comment by tacaswell** [comment]
> This is basically a non starter for me.

black is a small pure-python package and is much simpler to install than the build dependencies of skimage.

That said, my general thinking is running black enmasse on existing projects will put in huge code-churn (and there are ways to make git preserve the blame) for not much gain.

It also has the idea of formatting the code to make future diffs as readable as possible which is quite interesting.

**Comment by hmaarrfk** [comment]
But I think there is some magical command to install pre commit hooks. Which adds quite a bit of complexity. 

I tried black, but it would require the whole code base to be passed through the linter. Gets very annoying considering the code base is quite large.

Some things like white line spacing might be a good idea though, if somebody wants to set it up.

**Comment by sciunto** [comment]
Thank you all for your good and constructive criticism!

> 
> Some things like white line spacing might be a good idea though, if somebody wants to set it up.

What do you mean by white line spacing?

**Comment by hmaarrfk** [comment]
blank line spacing.

**Comment by jni** [comment]
Hi everyone,

We are using black over at https://github.com/napari/napari. See the relevant part of the development instructions:

https://github.com/napari/napari/blob/master/CONTRIBUTING.md#setting-up-a-development-installation

Essentially:

- add the `black` and `pre-commit` packages to the development requirements
- run the command `pre-commit install`

Then, if you try to commit code that is not properly black formatted, it will not commit, and add the black modifications to the commit. Then you have to either `git add` those modifications or `git commit -a` to get a commit in. It's definitely an adjustment, and I agree with @hmaarrfk that it's a significant enough deviation from "standard" SciPy development to warrant careful thinking.

I *definitely* don't think we should run the whole repo through it, despite @stefanv's jokes to me (in a private conversation) that "it would be a no-op" for our already excellently-formatted repo. ;) I believe the pre-commit hook can be set up to only run on new code, so that we could progressively migrate.

I also dislike that black does not allow formatting of NumPy arrays to be readable. It is *not* designed for scientific Python code.

At napari, we have noticed that some formatting for example code (rather than production code) is super ugly and doesn't match at all what one would write when writing Python, and also, that it doesn't *quite* get rid of formatting discussion because you sometimes end up wanting to rework code so that black doesn't make such a mess of it. But I must admit that those cases are in the minority, and overall it *does* free up brainpower from ever thinking about how to make code look pretty, which is nice.

Anyway, all this to say, I'm a weak :-1: for using it until more of the SciPy ecosystem is doing so, and a strong :-1: for applying it to past code, rather than just going forward. And a strong :-1: for applying it to examples in the gallery.

**Comment by sciunto** [comment]
ok, someone has to write gray, [and not grey...](https://github.com/scikit-image/scikit-image/issues/2604)

**Comment by NelleV** [comment]
How about we write gray and grey and make them slightly different? :grin:

**Comment by grlee77** [comment]
@jni said
> I also dislike that black does not allow formatting of NumPy arrays to be readable. It is not designed for scientific Python code.

It seems it is possible to bracket existing arrays/lists using comments to disable the formatting in those blocks:

```Python
# fmt: off

my_list = [0, 1, 2,
           3, 4, 5,
           6, 7, 8]

# fmt: on
```

I think that is overall less annoying than everything being reformatted to one element per line. This solution was suggested in psf/black#440.

**Comment by sciunto** [comment]
This SKIP is a NOGO. I close it.
