### ISSUE TITLE
Define standard common argument's names

### ISSUE THREAD

**Issue by rfezzani** [scikit-image/scikit-image#4154]
## Description

It is important for a library to be consistent in arguments naming. The issue #4003 points out such problem.
I noticed for example that the argument for the _"maximum number of iterations"_ has at least 5 names over `skimage` functions:
- `max_iter` in `slic`,
- `max_iterations` in `active_contour`,
- `iterations` in `richardson_lucy`,
- `n_iter_max` in `denoise_tv_chambolle`,
- `niter` in `optical_flow_tvl1`.

What about defining standards for such common argument names and fixing the code base in the same spirit as #4152?

**Comment by rfezzani** [comment]
I didn't knew `wabisabi`, thank you @hmaarrfk for pointing it. You also are right, the decorator defined in this [gist](https://gist.github.com/rfezzani/002181c8667ec4c671421a4d938167eb) can be used for this issue. The PR #4158 is an example of function's signature modification using such a decorator.
@jni, I also vote for `max_num_iter` and `num_iter` ;-)

**Comment by rfezzani** [comment]
For [ref](https://github.com/scikit-image/scikit-image/pull/4209#discussion_r355546849).

**Comment by rfezzani** [comment]
Concerning the `selem`  argument name  consistency identified in #4209, I found:

- `selem` in `skimage.filters.rank` module's functions,
- `selem` in `skimage.morphology` module's functions,
- `structure` in `skimage.morphology._util._offsets_to_raveled_neighbors`,
- `footprint` in `skimage.feature.peak.peak_local_max` and `skimage.feature.peak._get_peak_mask`

**Comment by jni** [comment]
Thanks for the investigation!

Since we have all those uses, I think it makes sense to find the one we like most and use it, since something will have to be deprecated whatever we choose. (Even though of course some deprecations are more panful than others.) Again, imho selem is really the worst of them.

**Comment by anntzer** [comment]
fwiw you may be interested in using https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/cbook/deprecation.py#L258 (a renaming decorator that handles the deprecation `@rename_parameter(version_number, old_name, new_name)`) rather than manually going through all of them.
It uses some other matplotlib internal deprecation machinery but should be easy enough to adapt for skimage...

**Comment by rfezzani** [comment]
Thank you @anntzer, I didn't knew this one! I already proposed #4158 a decorator in the same spirit ;-)

**Comment by rfezzani** [comment]
You may also be interested in @hmaarrfk [wasibisi](https://github.com/hmaarrfk/wabisabi) package.

**Comment by emmanuelle** [comment]
My two cents regarding selem / structure / footprint (/ neighbourhood as proposed by @jni / kernel or element as used in opencv). `selem` is what we use the most throughout `morphology` in particular. Nevertheless "structuring element" is mathematical morphology jargon, therefore it is quite obscure for most users. I like `footprint` the most I think, then neighbourhood and kernel. Having a simple word which is easy to understand is important I think.

**Comment by grlee77** [comment]
One issue with neighborhood/neighbourhood is potential confusion due to differing american/british spellings. For that reason, I like `footprint` a bit better.

**Comment by emmanuelle** [comment]
Another point is that we should try to reduce the number of possible keyword arguments throughout the library in order to decrease the cognitive load. For example, all arguments which are a small patch/neighbourhood/kernel etc. could have the same name. The actual name whether its kernel, footprint, structure or neighbourhood is not that important -- except for the fact that if we can be consistent with another major library, it's a bonus.

**Comment by JDWarner** [comment]
I'm on board with `footprint` (`patch` actually seems pretty good to me as well).  I agree with @jni that `selem` is probably the worst of the bunch for a new user.  Paradoxically it's also what anyone coming from Matlab would expect and look for first (probably why it got used early on), and pretty well understood/assumed in mathematical morphology circles.

If we change away from `selem`, all places where it was previously should probably continue to mention the term `selem` in the docs.  Especially in `skimage.morphology`.

**Comment by rfezzani** [comment]
Cross-ref #5359

**Comment by grlee77** [comment]
To summarize the above, it looks like the current consensus is:

Myself, @emmanuelle and @JDWarner seem on board with `footprint` in the `selem`/`structure`/`footprint` case (also @lagru and @sciunto via emoji)

For iterations, @jni and @rfezzani [expressed a preference](https://github.com/scikit-image/scikit-image/issues/4154#issuecomment-531064682) for `num_iter` and `max_num_iter` (also @sciunto and @mkcor via emoji)

**Comment by grlee77** [comment]
Both the `footprint` and `num_iter` cases have been addressed for 0.19, so this issue was resolved (I deleted the discussion topic that had been created)
