### ISSUE TITLE
Release notes tool does not correctly attribute authorship in backports

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#4264]
## Description

Running `tools/generate_release_notes.py v0.16.1 v0.16.2rc1 --version v0.16.2 > release_notes_0.16.2.rst` does not include Jarrod Millman even though he authored our migration to networkx 2.x, which is in this release. It also does not include @sciunto even though he fixed our active contour docs.

Finally, the final mergers in PRs don't get credited as reviewers, even though they typically are.

**Comment by lagru** [comment]
Adding to this, the script also doesn't pick up at least one PR it should have. See https://github.com/scikit-image/scikit-image/pull/6766#issuecomment-1443680765.

**Comment by lagru** [comment]
I am removing this from the 0.22 milestone; I don't think this issue is specific to that release. I'll also close it for now because this should be raised on changelist if the problem remains. Currently we don't really do backporting for patch releases.

Also, with the switch to changelist, most of these issues remain, because there isn't a mapping from backport PR to original PR. Also, in the case of https://github.com/scikit-image/scikit-image/pull/4262, @soupault doesn't show up as a reviewer, because [he is listed as "author" and not "committer"](https://api.github.com/repos/scikit-image/scikit-image/commits/2b1d8494c6e65db8d7dc1c0d5f037297f5e93db1). I think that's because it isn't a squashing merge commit.
