### ISSUE TITLE
Add Python 3.8 to CI tests

### ISSUE THREAD

**Issue by justinkterry** [scikit-image/scikit-image#4336]
Python 3.8 has been out for 6 weeks, and your CI tests for pull requests are still only testing for 3.6 and 3.7. This should be fixed.

**Comment by hmaarrfk** [comment]
Thanks for bringing this up.

Since this is well underway, I am going to close this issue. 

Just as a note. scikit-image, as well as many other compiled packages do care about getting builds out as fast as possible. 

Generally, it makes sense to wait until downstream packages fix their incompatibility issues.

Matplotlib, a big dependency of ours, just released important patches for 3.8 and compatibility fixes so it didn't really make sense for us to test things rigorously before that.

**Comment by hmaarrfk** [comment]
https://github.com/scikit-image/scikit-image/pull/4331

Note that these builds are failing since scikit-learn needs to finish releasing 0.22.
