### ISSUE TITLE
Builds failing due to new tifffile release

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#4451]
## Description

Example failure: https://travis-ci.org/scikit-image/scikit-image/jobs/651311082#L2729

```pytb
_____________________ ERROR at setup of test_imread_uint16 _____________________
    def setup():
>       use_plugin('tifffile')
../../venv/lib/python3.6/site-packages/skimage/io/tests/test_tifffile.py:14: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../venv/lib/python3.6/site-packages/skimage/io/manage_plugins.py:253: in use_plugin
    _load(name)
../../venv/lib/python3.6/site-packages/skimage/io/manage_plugins.py:297: in _load
    fromlist=[modname])
../../venv/lib/python3.6/site-packages/skimage/io/_plugins/tifffile_plugin.py:4: in <module>
    from tifffile import TiffFile, imsave, parse_kwargs
../../venv/lib/python3.6/site-packages/tifffile/__init__.py:3: in <module>
    from .tifffile import __doc__, __all__, __version__, main
../../venv/lib/python3.6/site-packages/tifffile/tifffile.py:524: in <module>
    import imagecodecs
../../venv/lib/python3.6/site-packages/imagecodecs/__init__.py:5: in <module>
    from .imagecodecs import __doc__, __version__, __getattr__, __dir__
../../venv/lib/python3.6/site-packages/imagecodecs/imagecodecs.py:804: in <module>
    _load_all()
../../venv/lib/python3.6/site-packages/imagecodecs/imagecodecs.py:347: in _load_all
    __getattr__(name)
../../venv/lib/python3.6/site-packages/imagecodecs/imagecodecs.py:371: in __getattr__
    module = importlib.import_module('._' + module_, 'imagecodecs')
../../venv/lib/python3.6/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
>   ???
E   AttributeError: type object 'imagecodecs._aec.array' has no attribute '__reduce_cython__'
```

I forget where the `has no attribute '__reduce_cython__'` error comes from but we've seen it before...

**Comment by cgohlke** [comment]
> `AttributeError: type object 'imagecodecs._aec.array' has no attribute '__reduce_cython__'`

This exception is misleading and a known Cython issue. The AttributeError is raised instead of a proper error when an import of a module from within a Cython extension module fails. 

In this case the numpy version seems too old:

`ERROR: tifffile 2020.2.16 has requirement numpy>=1.15.1, but you'll have numpy 1.14.1 which is incompatible.`

Tifffile and imagecodecs follow NEP 29 and now require numpy  >= 1.15.1. Not sure, but the [linux and mac builds of imagecodecs](https://github.com/Czaki/imagecodecs) may require even later versions of numpy.

**Comment by hmaarrfk** [comment]
Why do you think that the minimum version is 1.15.1?

https://gist.github.com/hmaarrfk/0e2a01d57f07f55eb99d177da92691b6

1.14 is the version of numpy that is 24 months old.

**Comment by hmaarrfk** [comment]
Don't take this the wrong way, you should be allowed to set the minimum version of numpy to whatever you want for tifffile. NEP 29 was set as a guideline because people were reluctant to updated the numpy pinning. We fall in that camp (for better or for worse).

Our build system pins the minimum versions for that particular build to what we believe is a set of minimal compatible versions. Without having set one for tifffile, it was using `newest tifffile` and `numpy 1.14` which is our minimum version. #4453 attempts to set a minimum version of tifffile which should fix that particular build.

**Comment by rfezzani** [comment]
> Why do you think that the minimum version is 1.15.1?

NEP29 [drop schedule](https://numpy.org/neps/nep-0029-deprecation_policy.html#drop-schedule) and [support table](https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table)...

**Comment by hmaarrfk** [comment]
i see, my calculator is wrong then ;). 

It should be from the date of releasing the X.X.0 version. 

Thanks for the clarification.

**Comment by hmaarrfk** [comment]
FYI: I don't think our two approaches are contradictory, they are more "symbiotic".

**Comment by rfezzani** [comment]
I fully agree, I am :+1: your PR :wink:
