### ISSUE TITLE
Add definitions to glossary for disk and perimeter

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#4455]
## Description

See [here](https://github.com/scikit-image/scikit-image/issues/4406) for the ambiguity we had in the library and [here](https://github.com/scikit-image/scikit-image/pull/4428#issuecomment-587132159) for the suggestion to add definitions to the glossary.

**Comment by emmanuelle** [comment]
The glossary is https://scikit-image.org/docs/stable/glossary.html

**Comment by sciunto** [comment]
I have some words overlapping over here... :/

**Comment by emmanuelle** [comment]
Sorry @sciunto I don't understand what you mean here?

**Comment by sciunto** [comment]
![Glossary — skimage v0 17 2 docs](https://user-images.githubusercontent.com/335370/86779555-01ec2980-c05c-11ea-90d7-be9750f5e72f.png)

**Comment by rajpratyush** [comment]
Is this issue still open for work??

**Comment by mkcor** [comment]
@rajpratyush for sure! Otherwise the issue would be closed and/or `disk` and `perimeter` would appear in https://scikit-image.org/docs/dev/glossary.html and/or further conversation would say otherwise.

**Comment by rajpratyush** [comment]
Thanx this is my first time contributing to scikit learn could you point me to file needed to be changed

**Comment by mkcor** [comment]
@rajpratyush this is scikit-image, not scikit-learn ;-)
Well, the time that you might think you will 'waste' looking for the right file to edit... is actually useful in the longer run, because this way you will gradually become familiar with the codebase and its organization. Are you familiar with any recursive grep tool?

**Comment by rajpratyush** [comment]
@mkcor sorry for typo 

I am familiar with the grep tool
I know it will be highly useful

**Comment by ovynnej** [comment]
Hello! I tried searching through pull requests and didn't find any for this issue, and since there hasn't been any activity in this discussion since April, I'd like to give it a try.

Based on the links in the description, I will try to add these definitions to the glossary:

circle: The perimeter of a disk.
disk: A filled-in circle.

@mkcor do you think that sounds like a good plan?

**Comment by jni** [comment]
Closed by #5590
