### ISSUE TITLE
ImportError for skimage.draw.disk

### ISSUE THREAD

**Issue by AhmetCanSolak** [scikit-image/scikit-image#4504]
Hi everybody,

I wanted to drop a small bug report in an example.
Following line is trying to import disk:

https://github.com/scikit-image/scikit-image/blob/88af67f1d2222dac21edd4548bfa50bdf76d0b4f/doc/examples/edges/plot_shapes.py#L24

and it crashes with `scikit-image-0.16.2` from pypi:
```
Traceback (most recent call last):
  File "skimage-test.py", line 5, in <module>
    from skimage.draw import (line, polygon, disk,
ImportError: cannot import name 'disk' from 'skimage.draw'
```

I thought about making a fix PR with `skimage.morphology.disk` but I am not sure if you guys want to fix this example in another way. 
Thank you!

**Comment by sciunto** [comment]
Thanks for the report. I think this issue is invalid.

The documentation indicates that for 0.16, the valid function is circle : https://scikit-image.org/docs/0.16.x/auto_examples/edges/plot_shapes.html#sphx-glr-auto-examples-edges-plot-shapes-py

The function disk has been introduced in master to replace circle. This is not released yet in a tagged version. It will show up in 0.17.

I'm closing the issue. Feel free to reopen if the answer is not appropriate.

**Comment by oo92** [comment]
Can't import circle either

```
    from skimage.draw import circle
ImportError: cannot import name 'circle' from 'skimage.draw' (/home/onur/.local/lib/python3.9/site-packages/skimage/draw/__init__.py)
```

**Comment by ksemanur8** [comment]
> Can't import circle either
> 
> ```
>     from skimage.draw import circle
> ImportError: cannot import name 'circle' from 'skimage.draw' (/home/onur/.local/lib/python3.9/site-packages/skimage/draw/__init__.py)
> ```

@oo92 Were you able to solve this issue?

**Comment by 1702609** [comment]
> Can't import circle either
> 
> ```
>     from skimage.draw import circle
> ImportError: cannot import name 'circle' from 'skimage.draw' (/home/onur/.local/lib/python3.9/site-packages/skimage/draw/__init__.py)
> ```

Me too! What is the solution to this?

**Comment by Skalwalker** [comment]
@1702609 @oo92 It is not very highlighted in the previous comment, but the **function 'circle' has been replaced by 'disk'** in recent versions. Therefore, the solution is to use disk.
