### ISSUE TITLE
exposure.equalize_adapthist changes output datatype

### ISSUE THREAD

**Issue by rdaniels5** [scikit-image/scikit-image#4516]
* **[ORIGINAL TITLE] Setting clip-limit to 1 does not return original image.**

## Description
In the _clahe function, it says setting the clip limit to one will return the original image. That is not true because before it is passed through to that function, clip limit is multiplied by "nbins".

**Comment by alexdesiqueira** [comment]
Hi @rdaniels5 ,
thank you for opening this issue! Could you please send us some code exemplifying it? We will try to reproduce based on that.
Thanks again!

**Comment by rdaniels5** [comment]
import matplotlib.image as mpimg
    from skimage.exposure import equalize_adapthist

    img = mpimg.imread('hist_eq.png')
    start = time()
    img_t = torch.tensor(img)
    new = equalize_adapthist(img_t, clip_limit=1, kernel_size=(32, 32))

**Comment by alexdesiqueira** [comment]
Hey @rdaniels5,
I'm sorry, I haven't expressed myself very clearly :) could you please send us a _fully reproducible_ example, with the image you used, if possible?
Thank you again!

**Comment by rdaniels5** [comment]
````
from skimage import data, exposure
import matplotlib.pyplot as plt

plt.imshow(exposure.equalize_adapthist(data.moon(), clip_limit=1))
````

Is this good enough? It does the same thing with this code.

**Comment by alexdesiqueira** [comment]
Hey @rdaniels5,
thank you for the example!
I checked it here, and it actually does return the original image back. It indeed [multiplies `clip_limit` by nbins](https://github.com/scikit-image/scikit-image/blob/786adad0da9b399c9c4689bf43b44b95011c13ac/skimage/exposure/_adapthist.py#L85), but before that, it [converts the image to `uint`](https://github.com/scikit-image/scikit-image/blob/786adad0da9b399c9c4689bf43b44b95011c13ac/skimage/exposure/_adapthist.py#L73) — currently necessary for the algorithm to work. I think your issues come because the algorithm [returns a float image](https://github.com/scikit-image/scikit-image/blob/786adad0da9b399c9c4689bf43b44b95011c13ac/skimage/exposure/_adapthist.py#L86) no matter what input it had, modifying the original image.
One small example showing they are indeed the same, with a different data type:
```
from skimage import data, exposure, util
import numpy as np

image = data.moon()  # dtype('uint8')
image_clahe = exposure.equalize_adapthist(image, clip_limit=1)  # dtype('float64')
image_clahe_uint8 = util.img_as_ubyte(image)  # dtype('uint8')
np.array_equal(image, image_clahe_uint8)
```
In this case, `np.array_equal` returns `True`, indicating the arrays have the same values.
Thank you for pointing that out! Let's see what we can do to solve this issue.

**Comment by alexdesiqueira** [comment]
@jni some context: is there a way to retrieve the input image datatype and return the same dtype on the output image, for `exposure.equalize_adapthist`? Thank you!

**Comment by rfezzani** [comment]
A simpler solution would be to check for `clip_limit == 1` in `equalize_adapthist` before converting to `uint`...

**Comment by rfezzani** [comment]
Please see #4519.

**Comment by alexdesiqueira** [comment]
> A simpler solution would be to check for `clip_limit == 1` in `equalize_adapthist` before converting to `uint`...

This only solves the situation when `clip_limit == 1` :blush:

**Comment by rfezzani** [comment]
For sure, but it solves the described bug ;-). It makes the documentation and the function behavior concordant...

**Comment by alexdesiqueira** [comment]
Nevermind! :sweat_smile:

**Comment by alexdesiqueira** [comment]
@rdaniels5 thank you again for pointing that out! Our proposed solution will return a `float` image always, though (see #4519); if you would like to get the original image back, you would need to convert back to your datatype — for now.
