### ISSUE TITLE
Info for venv activation on CONTRIBUTING.txt does not suit Windows

### ISSUE THREAD

**Issue by csharp489** [scikit-image/scikit-image#4520]
* **[ORIGINAL TITLE] Changes required in Contributing.txt file**

Please change the Virtual environment activate command of window in Contributing.txt file 
**Incorrect command**
 **`source skimage-dev/bin/activate`**

**Correct Command**
 **`skimage-dev\Scripts\activate`**

**Comment by alexdesiqueira** [comment]
Hey @csharp489, thank you for reaching out!
The command works properly on Linux and Mac.
I assume you are using Windows, right? I will leave a comment on that file.
Thank you again!

**Comment by csharp489** [comment]
Yes , I am using window but  It(**source skimage-dev/bin/activate**) is a path. And according to this there is no **bin** folder in **skimage-dev** folder. Please don't mind , I am just curious know that how can this command run on LINUX or MAC. As we know that there is no bin folder in it.

**Comment by alexdesiqueira** [comment]
The command ` python -m venv skimage-dev` creates a different structure depending on the system you have:
- on Linux/Mac, `venv` will create the path `skimage-dev/bin/activate`.
- on Windows, `venv` will create the path ` skimage-dev\Scripts\activate`.

That's why you don't see the folder `bin` on Windows, @csharp489 :)

**Comment by sciunto** [comment]
The instructions have been modified. Feel free to reopen this issue it the problem is not solved.
