### ISSUE TITLE
Slic

### ISSUE THREAD

**Issue by Chokerino** [scikit-image/scikit-image#4542]
## Description
I was trying to use Slic to segment tumours from MRI images and the output images just lose the color intensities which makes it impossible to use the images for further segmentation.

## Way to reproduce
```python
    label = slic(image,n_segments=150,compactness=0.005,multichannel=False,sigma=1,slic_zero=True)

```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
>3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)]
import platform; print(platform.platform())
>Windows-10-10.0.18362-SP0
import skimage; print("scikit-image version: {}".format(skimage.__version__))
>scikit-image version: 0.16.2
import numpy; print("numpy version: {}".format(numpy.__version__))
>numpy version: 1.17.4
```

```python
# your output here
```
![one](https://user-images.githubusercontent.com/43617111/78039766-274a0700-738c-11ea-9580-a23c89ea83ab.png)
![two](https://user-images.githubusercontent.com/43617111/78039769-287b3400-738c-11ea-9d8d-f726c25c6123.png)
Attached you can see first is the original image and the second is the output after slic. Slic is able to segment the tumor but since the colors not deviate from the original I cannot further use it in Multi-otsu which I was trying to do. Any solutions for this would be greatly appreciated.

**Comment by rfezzani** [comment]
Hi @Chokerino, and thank you for your interest in skimage. I just edited your post to make your images appear.
This is the skimage development tracker. For general questions on the library use, please, consider posting to https://forum.image.sc/tag/scikit-image where you may find more help.
Btw, [`slic`](https://scikit-image.org/docs/dev/api/skimage.segmentation.html#skimage.segmentation.slic) returns labels corresponding to the result of a k-means clustering based segmentation.

**Comment by Chokerino** [comment]
Thanks for the response and I will post it on the forums.
I know that labels are returned after kmeans segmentation but should it be
preserving colors? For example in my images, the part of the image above
and below the brain are of the same colour and after labelling they are 2
totally different shape and lose out on their meaning.

Coordinator | BioBytes
Btech Undergrad '22 IIITD

**Comment by jni** [comment]
@Chokerino labels don't have any idea of "colour": they are different integers for different regions of the image. Their ordering and value is arbitrary. If you want to create color from the labels, you can use [`skimage.color.label2rgb`](https://scikit-image.org/docs/dev/api/skimage.color.html#skimage.color.label2rgb).

At any rate, multi-Otsu would typically be something you apply to the input image, rather than to the result of SLIC...

To learn more about the scikit-image segmentation data model, you might want to have a look at our [segmentation tutorial](https://github.com/scikit-image/skimage-tutorials/blob/master/lectures/4_segmentation.ipynb).

I hope this helps! I'll close this issue for now, and we can continue the discussion on image.sc. Thanks!
