### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape' in windows

### ISSUE THREAD

**Issue by ajitjohnson** [scikit-image/scikit-image#4552]
## Description
Hi, I am trying to load an OME-TIF image using the following command.

```
from skimage.external.tifffile import imread
idx = [29,25]
image = imread (image_path, key = idx)
```
It works in MacBook but fails in a Windows machine. In both cases, I am working inside a conda environment. 

Below is the error that I get.

```
Traceback (most recent call last):

  File "<ipython-input-35-1981b1315213>", line 1, in <module>
    image = imread(image_path, key = [29,25])

  File "C:\Users\ajn16\AppData\Local\Continuum\anaconda3\envs\mipy\lib\site-packages\skimage\external\tifffile\tifffile.py", line 1241, in imread
    return tif.asarray(**kwargs)

  File "C:\Users\ajn16\AppData\Local\Continuum\anaconda3\envs\mipy\lib\site-packages\skimage\external\tifffile\tifffile.py", line 1522, in asarray
    result = numpy.empty(series.shape, series.dtype).reshape(-1)

AttributeError: 'NoneType' object has no attribute 'shape'
```
Can you offer me help with this? Thank you.

**Comment by jni** [comment]
@ajitjohnson we need a more complete use case, with an example data file and complete script, to be able to help properly. But, as a preliminary investigation, here is the relevant part of the tifffile source code:

https://github.com/scikit-image/scikit-image/blob/v0.16.x/skimage/external/tifffile/tifffile.py#L1510-L1523

From what I can tell, `series` can be None here, and that is a bug. This code doesn't exist in more recent versions of tifffile, so my first recommendation is that you `pip install tifffile`, which will prevent scikit-image from using its bundled version and use the installed version.

Please let me know if this fixes your problem so that we can close the issue!

**Comment by ajitjohnson** [comment]
Thank you @jni. I updated the `tifffile` package and If I load the image directly using `tifffile`, it works as below. 

```
import tifffile as tiff
idx = [1,5,10]
image = tiff.imread (image_path, key = idx)
```
However, if I use skimage, it still gives me the same error. 

```
from skimage.external.tifffile import imread
image = imread (image_path, key = idx)
```
Also note, if I do not pass the `key` argument or if I just pass a single value like, `key=2`, it works.

Thank you.


However
