### ISSUE TITLE
Signatures in dev API have backslashes before *

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#4566]
## Description

Compare 

https://scikit-image.org/docs/dev/api/skimage.metrics.html#adapted-rand-error
https://scikit-image.org/docs/stable/api/skimage.metrics.html#adapted-rand-error

**Comment by emmanuelle** [comment]
Thanks for the report @sciunto. This is weird because it's not in the source code...

I found it in a couple of other places like 
https://scikit-image.org/docs/dev/api/skimage.metrics.html#skimage.metrics.contingency_table
https://scikit-image.org/docs/dev/api/skimage.metrics.html#normalized-root-mse
https://scikit-image.org/docs/dev/api/skimage.metrics.html#peak-signal-noise-ratio

In https://scikit-image.org/docs/dev/api/skimage.measure.html#compare-ssim there is the "\*\*" for kwargs which is very ugly.

Maybe something changed in sphinx?

**Comment by emmanuelle** [comment]
New major version of sphinx released a few days ago, this might explain... https://pypi.org/project/Sphinx/3.0.0/#history

**Comment by sciunto** [comment]
I'm building the doc with two different sphinx versions to check.

**Comment by sciunto** [comment]
I can reproduce by updating sphinx from 2.4.4 to 3.0.0
