### ISSUE TITLE
imread published wheels, consider to revert a workaround in travis?

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#4584]
## Description

Upstream action:
https://github.com/luispedro/imread/issues/36#issuecomment-613346141

Should we revert #3898?

**Comment by sciunto** [comment]
Cc @hmaarrfk

**Comment by jni** [comment]
I'm agnostic about this. Which translates into: if someone submits a PR and it passes, I'll approve it. =)

**Comment by hmaarrfk** [comment]
I saw this, and unfortunately only wheels for linux were published.

![image](https://user-images.githubusercontent.com/90008/79463385-a2770400-7fad-11ea-879f-e99d026cb24d.png)

I am still opposed to building imread ourselves due to the C dependencies which we at scikit-image don't have a good way to manage

**Comment by sciunto** [comment]
OK

**Comment by hmaarrfk** [comment]
it could be fair to ask that issue to be reopened

**Comment by sciunto** [comment]
Yes. It would rather be  the issue 35 on imread's tracker
