### ISSUE TITLE
Reintroduce `dtype.convert`

### ISSUE THREAD

**Issue by hmaarrfk** [scikit-image/scikit-image#4680]
## Description

`dtype.convert` used to be a very useful function in older versions of scikit-image.

In 0.17 it was decided that it should be removed without a deprecation cycle.

Not fun.

Could we get it back in 0.17.2 with a deprecation cycle?
https://github.com/scikit-image/scikit-image/pull/4590
If so, i can make the PR.

**Comment by emmanuelle** [comment]
As I was saying in #4590 we did not deprecate because the function was not public (in the sense of not being exposed in the public API). @sciunto's first intent was to make it public (as you say it's a useful function, although most people don't know about it I guess since it's not public and we don't use it in any of the doc examples), but then we thought that it was not the right time to make this function public since the function will likely change a lot when we drop range rescaling.

That said, it does not hurt if we have a deprecation cycle for a non-public function, so if you make the PR I'll be happy to accept and backport if merged. Thoughts anyone?

**Comment by hmaarrfk** [comment]
ah the chronological orders were not clear to me. I get that it might be useless in the near future.

Since there is at least 1 person supporting this, I can make the PR.
