### ISSUE TITLE
how to mark object centroid in the video

### ISSUE THREAD

**Issue by liang-minhui** [scikit-image/scikit-image#4790]
## Description

i use regionprops to get segments information in every frame, the input is 100 frame array, but regionprops only provide segments info in one frame. how can I use the centroid in regionprops to mark segments in each frame?

## Way to reproduce
```

def edgedetect (vadd):
 cap = cv2.VideoCapture(vadd)
 fgbg = cv2.createBackgroundSubtractorMOG2()

 while (1):
    ret, frame = cap.read()

    fgmask = fgbg.apply(frame)

    retthre,fgthre = cv2.threshold(fgmask,0,255,cv2.THRESH_BINARY+cv2.THRESH_OTSU)

    fgclose = skm.closing(fgthre, square(4))
    fgopen = skm.opening(fgclose, square(4))
    fgclose = skm.closing(fgopen, square(15))

    fglabel = skmeas.label(fgclose)
    overlay = label2rgb(fglabel, image=fgclose, bg_label=0)

    ## above is for image segementation, here begin to get infor for every segmentation in current frame
    fgregoin = skmeas.regionprops(fglabel)
    for props in fgregoin:
        cent.append(props.centroid)
  ##the input fglabel include 100 frames, how to mark in each frame?


    cv2.imshow('fgmask', overlay)

    k = cv2.waitKey(30) & 0xff
    if k == 27:
        break

 cap.release()
 cv2.destroyAllWindows()

 return

```

**Comment by jni** [comment]
@liang-minhui can you provide a *complete* code snippet? `cent` from `cent.append` is not defined, for example. Nor do you do anything with it. Ideally, you should also provide an example video so that we could run the code.

In the future, for this kind of usage question, rather than a bug report, StackOverflow or the image.sc forum are better places to post. I am going to close this as it is not a scikit-image bug, but please continue to discuss below.
