### ISSUE TITLE
Another missing attribute '__reduce_cython__'

### ISSUE THREAD

**Issue by olebole** [scikit-image/scikit-image#4791]
## Description

After I successfully made the python3-tifffile package available for Debian, I want to upgrade our skimage package to 0.17.2. However, the build fails now with 

```
/usr/lib/python3/dist-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
skimage/feature/__init__.py:23: in <module>
    from .orb import ORB
skimage/feature/orb.py:12: in <module>
    from .orb_cy import _orb_loop
stringsource:105: in init skimage.feature.orb_cy
    ???
E   AttributeError: type object 'skimage.feature.orb_cy.array' has no attribute '__reduce_cython__'
```
on several places. From some earlier issues of a similar type (like #4451), this may be due to dependency versions too old; however, all versions match, except for PyWavelets. It looks however not like connected toPyWavelet (how important is that anyway? Must In delay the upload until the latest version is in Debian?)

## Way to reproduce

Try to build skimage on a Debian sid with all required packages installed from Debian itself (i.e. no pip).

## Version information

Package | required | actual
----------|---------|--------
Cython | >=0.29.13 | 0.29.14
numpy | >=1.15.1 | 1.18.4
scipy | >=1.0.1 | 1.4.1
matplotlib | >=2.0.0 | 3.2.1
networkx | >=2.0 | 2.4
pillow | >=4.3.0,!=7.1.0,!=7.1.1 | 7.0.0
imageio | >=2.3.0 | 2.4.1
tifffile | >=2019.7.26 | 20200603
PyWavelets | >=1.1.1 | 0.5.1

Python versin is 3.8.3.

**Comment by hmaarrfk** [comment]
> After I successfully made the python3-tifffile package available for Debian, 

Definitely a hard package to get going....
If you didn't get it going, I would have probably worked with you to make it an optional dependency because it gave me too much trouble on conda-forge.
Do note that ultra-recent changes in the build system of tifffile might make your life easier.


I think this has to do to the fact that we moved around a few binary files

https://github.com/scikit-image/scikit-image/commit/bad916ddb999c8c6562f8bba2ac1ba130e87ad29#diff-4b981cbde8358fb1de9da88c420e989dL16

Can you make sure you are packaging 
https://github.com/scikit-image/scikit-image/commit/bad916ddb999c8c6562f8bba2ac1ba130e87ad29#diff-ff4a6938a4288fc9bda2368df8382b03R8

**Comment by olebole** [comment]
Ahh, this brought me to the right track: we do the test on the newly built package (which is built with `setup.py build`). This one however does not copy the data files (at least not when called from within the Debian "pybuild" tool), so I have to copy them manually later. This was not done for `feature/orb_descriptor_positions.txt`, which lead to a first error message that I have just overseen.

Copying this file fixed this problem, and the only problem I have now is the old qwt package, which leads to a number of failures in `restoration/tests/test_denoise.py` and `restoration/tests/test_j_invariant.py`. I will probably have to push for an update of PyWavelets.

Thank you for the help!

**Comment by hmaarrfk** [comment]
Glad you got things working.

Hoenstly, error messages are often non-sensical.

No issue with asking question with detailed build specs !
