### ISSUE TITLE
dev doc is not deployed when pre build is failing on Travis

### ISSUE THREAD

**Issue by emmanuelle** [scikit-image/scikit-image#4805]
It happens often that the pre build fails on Travis (at the moment due to Matplotlib's RC, which is ok because RCs are meant for this). However, when one of the Travis builds fail then the docs are not deployed by Travis, which is a problem. We should change the Travis configuration so that a failing pre build does not block the rest of the builds and deployment.

**Comment by hmaarrfk** [comment]
I recall that this was by design.

We felt that silent failure on pre would go ignored by many core devs, and as such, kept failing on it.

**Comment by emmanuelle** [comment]
Sure this makes sense. However in a lot of cases fixing the pre build does not depend on us and there can be weeks where we cannot have Travis deploy the docs. This happened with the Cython rc during the two weeks before the 0.17 release and as a result one doc bug went unnoticed.

**Comment by jni** [comment]
I guess the problem is that `--pre` should not go into "allowed failures" overall because we don't want a green light when pre builds are failing. But we *do* want the ability to merge *and* to deploy the docs when `--pre` is failing. My preference would be that we use GitHub Actions to deploy the docs on each merge on master. So this would be dependent on merges (which are triggered by a human) and not on CI state.

**Comment by emmanuelle** [comment]
This can be a good first issue for someone who wants to contribute to scikit-image but is more familiar with CI and deployment rather than image processing.

**Comment by jvkersch** [comment]
I'm thinking of picking up this issue as part of the SciPy 2020 sprint. I'll hand it off again if I can't make progress or come up with a reasonable plan.

**Comment by jvkersch** [comment]
Based on @jni's comments above, I wrote a small GitHub Actions to build and deploy the docs on master merge (or direct commit to master, which I imagine is rare). In fact, I looked at the Napari Github Actions for inspiration :) 

I did not make a PR against scikit-image yet, but you can see a proof of concept in action here:

- https://github.com/jvkersch/doc-builder-action/blob/master/.github/workflows/build-docs.yml contains the workflow. This installs the package and then builds the docs. The docs are uploaded to my GitHub pages account, and the script to do this is essentially the `tools/travis/deploy_docs.sh` script (without the checks that we're running on Travis). 
- Finished docs appear here: https://jvkersch.github.io/doc-builder-output/dev/. This is backed by the repo https://github.com/jvkersch/doc-builder-output. 

My main question is basically, is this on the right track for what you guys were considering? I'm happy to rework and polish if not.

Other than that, there are some things that need further investigation. For example, looking at the gallery in the finished docs, I see some visual artifacts (eg. the [immunohistochemical staining](https://jvkersch.github.io/doc-builder-output/dev/auto_examples/color_exposure/plot_ihc_color_separation.html#sphx-glr-auto-examples-color-exposure-plot-ihc-color-separation-py) is very blue). I don't have any of the special Matplotlib setup that I see in `.travis.yml` -- I'll try to add that.

**Comment by jni** [comment]
@jvkersch actually the immunohistochemical staining [on *our* master](https://scikit-image.org/docs/dev/auto_examples/color_exposure/plot_ihc_color_separation.html) is very blue! 😬 I know there was a PR that updated these functions recently... @alexdesiqueira I know you are going to hate me pinging you on this but you are the expert now... 😬 

Other than that, for me this looks super great, @jvkersch!

Personally I have literally never understood how secrets work with all this autodeploy stuff, so if you know of a quick tutorial on it I would very much appreciate it!

**Comment by jvkersch** [comment]
Thanks @jni!

My (basic) understanding of secrets is that you as the repo admin configure them in the GitHub settings for the repo. Github then does some black magic and passes them on to your workflow in encrypted form, and decrypts them for the steps that explicitly request a secret via `${{ secrets.MY_SECRET }}`. I also read https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets diagonally. 

Your comment caused me to worry a bit about how secrets are handled in the case of an error. If I try to make the git push fail, can I see the deploy token in the error logs? Fortunately, that seems to be not the case. On an unsuccessful push, the logs show
```
  git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" gh-pages
  shell: /bin/bash -e {0}
  env:
    GH_REF: github.com/jvkersch/doc-builder-output
    GH_TOKEN: ***
error: src refspec gh-pages does not match any
error: failed to push some refs to 'https://github.com/jvkersch/doc-builder-output'
```
If we don't do too much with the deployment token, then this feel reasonably safe to me.

I will open a PR against this repo with the workflow, so that we can comment on there.
