### ISSUE TITLE
skimage.segmentation.slic crashes when passed NaNs

### ISSUE THREAD

**Issue by rdinner** [scikit-image/scikit-image#4883]
## Description

When the image array passed to skimage.segmentation.slic() is a float array containing NaNs, the routine frequently crashes (most of the time, in my case). In Spyder, this causes a silent failure, with the print statement below failing to execute and the environment being reset. I've observed this behavior under both Windows and Linux.

## Way to reproduce
```python
import numpy as np
import skimage.segmentation as seg
im_slic = seg.slic(np.array([[np.nan, 0], [0, 0]]))
print(im_slic)
```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
Windows-10-10.0.17763-SP0
scikit-image version: 0.16.2
numpy version: 1.18.1
```

**Comment by jni** [comment]
Thanks @rdinner for raising this! Seems like a serious bug. We'll investigate solutions.

**Comment by jni** [comment]
@stefanv @hmaarrfk we've generally held off from

- automatically checking for nan's because it can be expensive. This would be even more of a concern with SLIC because one of the things it's known for is its speed.
- adding `nansafe=` or similar to the API because it would clutter an already cluttered API.

In this case, it's unclear what to do, then! One idea is to check whether any reduced representation can find the nans. In this case, perhaps, the initial cluster centroids, which is a set much smaller than the original pixels, could be checked for nan before proceeding further.

**Comment by rdinner** [comment]
Thanks @jni ! A nansafe option would be nice. But even without modifying the code, documenting that the input image needs to be nan-free or that nans must be masked out (by adding a note to the docstring "image" parameter) would help others avoid this issue. Thank you!

**Comment by emmanuelle** [comment]
I added a "good first issue" label for the task of adding a note in the docstring, which would already be an improvement. A further improvement would be to check if nans can be detected in the centroids as suggested by @jni.

**Comment by RonakSharma1** [comment]
Hey there, I'm looking for first issues to get involved with as I foray into the world of open-source :)
Is the issue about adding a note in docstring still available? Thanks!

**Comment by emmanuelle** [comment]
Hi @RonakSharma1, thank you for your interest in scikit-image! Yes it still available. You can take a look at our contributing guidelines to get started https://scikit-image.org/docs/dev/contribute.html

**Comment by RonakSharma1** [comment]
Hi @emmanuelle , thank you for this! I will have a read through the guidelines now and will let you know if I need any help as I progress.

**Comment by RonakSharma1** [comment]
Hey @emmanuelle 
Based on my basic understanding, I believe that only the docstring for the following files needs updating. Can you please confirm before I make any changes? Sorry to bother you with such trivial questions.

1. scikit-image/skimage/segmentation/slic_superpixels.py: Update 'image' docstring 
![slic_python](https://user-images.githubusercontent.com/34181525/90221975-119d2180-de03-11ea-9404-1638f50e083a.png)

2. scikit-image/skimage/segmentation/_slic.pyx: I think that this error might exist in Cython file as well and so I think 'image_zyx' docstring should be updated. What do you think?
![slic_cython](https://user-images.githubusercontent.com/34181525/90221957-0a761380-de03-11ea-97d1-c57f6076baa5.png)
Thank you for your help!

**Comment by emmanuelle** [comment]
Hi @RonakSharma1 sorry I never got back to you. Don't hesitate to ping people (like @emmanuelle) in such a case since we are drowning in notifications :-). 

To answer your question: yes this is the docstring of the `.py` file, in the part you highlighted. As for the cython file, the function is not part of the public API so no need to change its docstring.

**Comment by RonakSharma1** [comment]
Hey @emmanuelle ,
Thank you for letting me know. I will make the changes and issue a PR. Will try it to it this weekend

**Comment by RonakSharma1** [comment]
Hey @emmanuelle 
I have now created a PR. Could you please review and provide me with feedback?

**Comment by RonakSharma1** [comment]
@emmanuelle and @jni should we close this issue now as the work is done I believe?

**Comment by stefanv** [comment]
Thanks for following up @RonakSharma1!  Closing.

**Comment by jni** [comment]
My intuition though was that we should keep it open in case we want to address this at the implementation level later.

**Comment by stefanv** [comment]
Err, yikes, yes---it is a crash!

**Comment by Larkinnjm1** [comment]
Hey folks, I'd be interested in looking at coming up with some error catching nan check on the inputted array for this as I have burned by this previously. Are you guys happy for me to take this on?

**Comment by SimonHeybrock** [comment]
Had a look into this with @lagru during a sprint at EuroSciPy. Here is what we found:

As it stands, it would be straightforward to add a check for NaN (and INF) pixels with essentially zero extra cost, since a `min` and `max` are computed over the entire image, and we could simply check the result of that (and raise a `ValueError`): https://github.com/scikit-image/scikit-image/blob/f0a3fd10edc7626baa220cd9977cdee25233ac5f/skimage/segmentation/slic_superpixels.py#L259-L262

However, there are two problems here: The image is scaled using the `image.min()` and `image.max()`, but:
- This includes the masked pixels, probably scaling should be done based on min and max after masking? This is the case even when there are no NaNs.
- `image.min()` (and `max`) will include NaNs from masked pixels so the entire image will be NaN, *even if all NaN pixels have been masked, as recommended in the docstring*.

Conclusion (probably?):

- "Apply" mask somehow (`numpy.ma`?), compute `min` and `max` after that.
- Check that for NaN (and INF) (cheaply, since single value, not array), then raise `ValueError`.

**Comment by SimonHeybrock** [comment]
For reference, here are minor code changes with tests (but not addressing the two masking-related issues discussed above): [changes.txt](https://github.com/scikit-image/scikit-image/files/9476666/changes.txt)

**Comment by lagru** [comment]
Looks promising. Thank you @SimonHeybrock for the update. Would you like to turn you patch into a pull requests? :grin: We can address the mask issue separately in another issue or there if an easy solution comes to mind.

**Comment by SimonHeybrock** [comment]
I don't think it makes sense to address the NaN-crash without fixing the mask issue first, since the code for the fix would have to change, depending on the solution of the mask issue. That is, fixing this here first would mean more work in total.

**Comment by lagru** [comment]
Fair. However, I don't think we really have to fuss around with `numpy.ma`. We might get away with indexing like `image[mask].max()` and similar if the `mask` is given. Do you want to try a PR? :slightly_smiling_face:

**Comment by SimonHeybrock** [comment]
Sorry but I am very busy currently. I have not tried, but my guess is that `image[mask].max()` is slower than using `numpy.ma`, since with indexing you have to make a copy.

**Comment by lagru** [comment]
No worries. I just wanted to make sure not to step on your toes. I'm happy to take over. :wink:
