### ISSUE TITLE
CI failure, path issue for windows in gallery

### ISSUE THREAD

**Issue by sciunto** [scikit-image/scikit-image#4958]
## Description

See https://dev.azure.com/scikit-image/scikit-image/_build/results?buildId=4299&view=logs&j=31eb6c88-23c5-50ae-eda4-a7f72508e1eb&t=f7291549-81f8-5748-7064-2be81963872c&l=164

@mkcor @hmaarrfk Is this due to one of your recent contributions?

**Comment by mkcor** [comment]
@sciunto today I cannot troubleshoot for real (away from PC), but could it be the addition of `lily` in doc/examples/data/plot_scientific.py?
Since the CI failure occurs around doc/examples/data/plot_specific.py, which is nearby (referring to the order followed by Sphinx-Gallery), and `lily` gets fetched in a different way (i.e., with Pooch) wrt the other scientific images in that list (well, tuple).

**Comment by sciunto** [comment]
I don't have windows, I'm running a test over here: #4959

**Comment by hmaarrfk** [comment]
how did the windows builds even get fixed? was it just time?

**Comment by hmaarrfk** [comment]
maybe we can add :

- `export SKIMAGE_DATADIR=${AGENT_BUILDDIRECTORY}/.cache/scikit-image`

Around the other cache export

**Comment by hmaarrfk** [comment]
It seems that it fails on the BUILD_DOCs build. other builds don't build docs on windows. got it.

**Comment by lucyleeow** [comment]
Hi, this should be fixed in Sphinx Gallery 0.8.1 now, thanks!

**Comment by emmanuelle** [comment]
Thank you @lucyleeow :-) !
