### ISSUE TITLE
0.18.0 : Doc error for skimage.filters.prewitt_h/v

### ISSUE THREAD

**Issue by chacha21** [scikit-image/scikit-image#5075]
The documentation tells that skimage.filters.prewitt_h and skimage.filters.prewitt_v are using 3x3 filters
[[1 1 1] [0 0 0 ] [-1 -1 -1]] and [[1 0 -1][1 0 -1][1 0 -1]]
Actually, the implementation seems to only use [1 0 1] and [[1][0][-1]], which give different results.

For instance :
```
I = np.array([[4., 4., 4.],[3., 3., 3.],[2., 2., 2.]])
J = skimage.filters.prewitt_h(I) //returns unexpected [[-1. -1. -1.], [-2. -2. -2.], [-1. -1. -1.]]
```

**Comment by grlee77** [comment]
Can you specify how this differs from your expected results? For such a small input, the result will vary a lot depending on which boundary `mode` is selected. Only the center pixel in your example does not involve inclusion of any boundary elements within the filter kernel and it appears correct to me.

At least since release 0.17.0, the `prewitt` function is a general n-dimensional implementation, that builds up an n-d difference kernel by broadcasting 1d kernels appropriately. In 2d this ends up being [1/3, 1/3, 1/3] along one axis and [1, 0, -1] along the other to give exactly the 3x3 kernel you have listed above (albeit scaled by 1/3). It is true that this factor 1/3 scaling is not reflected in the `prewitt_h` or `prewitt_v` docstrings, so I think that could be improved. 

For reference, the [n-dimensional kernel construction code is here](https://github.com/scikit-image/scikit-image/blob/v0.17.2/skimage/filters/edges.py#L173-L181).

**Comment by chacha21** [comment]
I talked about the center element to exclude border effect and discussion about edges stategies.
But according to the doc, the center element should be (-1*4)+(-1*4)+(-1*4)+(0*3)+(0*3)+(0*3)+(1*2)+(1*2)+(1*2), aka -12+6=-6

[https://scikit-image.org/docs/dev/api/skimage.filters.html#prewitt-h](https://scikit-image.org/docs/dev/api/skimage.filters.html#prewitt-h)

**Comment by grlee77** [comment]
Okay, so it is the factor of 3 difference you are referring to. It looks like it is just a matter of updating the docstring, to include the normalization factor. I checked and it looks like the Prewitt functions were introduced in release `0.14` and extended to n-dimensional in 0.17, but have always had this scaling since that time.

Let me know whether or not you want to make a documentation fix PR for that. If not, we can take care of it. Thanks

**Comment by chacha21** [comment]
I am not a regular user, so I would not be very good at following the style.
I prefer that you write it the good way.

**Comment by grlee77** [comment]
Sure, no problem. Thanks for reporting the issue

**Comment by grlee77** [comment]
I have reopened this until #5076 is merged.
