### ISSUE TITLE
transform.resize uses anti_aliasing as default and fails to correctly clip values when anti_aliasing is used

### ISSUE THREAD

**Issue by abouysso** [scikit-image/scikit-image#5202]
## Description

The function transform.resize applies anti_aliasing as default when downsizing images, which is misleading as the default value for kwarg *anti_aliasing* is None.
Moreover, when applying anti_aliasing, when *scipy.ndimage.gaussian_filter* produce values outside the given input range, the algorithm fails to correctly clip the values while clip=True (default).

## Way to reproduce

```python
img = np.ones((208, 208))
transform.resize(img, (128, 128), anti_aliasing=None, clip=True).max()
```
>>> 1.0000000000000004

```python
img = np.ones((208, 208))
sigma = (208 / 128 - 1) * 0.5
ndi.gaussian_filter(img, sigma).max()
```
>>> 1.0000000000000004

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print("scikit-image version: {}".format(skimage.__version__))
import numpy; print("numpy version: {}".format(numpy.__version__))
```

```python
3.8.4 | packaged by conda-forge | (default, Jul 17 2020, 15:16:46) 
[GCC 7.5.0]
Linux-5.4.0-65-generic-x86_64-with-glibc2.10
scikit-image version: 0.17.2
numpy version: 1.19.5
```

**Comment by rfezzani** [comment]
Hi @abouysso, happy to see you here :wink:. Thank you for the report.
I confirm the `clip` bug: version 0.18 and current master branch is also affected.
I agree with you, the documentation concerning the `anti_aliasing` parameter must specify clearly that it is applied by default only in case of down-scaling.
Your analysis seems also valid, the clipping is applied after filtering,  it is the root cause of the bug.

**Comment by abouysso** [comment]
I will come with a PR soon. :)
