### ISSUE TITLE
y_idxs, x_idxs in the implementation of _hough_line

### ISSUE THREAD

**Issue by MTandHJ** [scikit-image/scikit-image#5570]
Hi,
I try to reproduce the hough line transform when reading the book of digital image processing.
However, I notice one strange detail, the line 312 in _hough_transform.pyx:
```
y_idxs, x_idxs = np.nonzero(img)
```
I think np.nonzero(img) should return a tuple of (x_idxs, y_idxs). 
Will it make any difference ?
Best.

**Comment by jni** [comment]
@MTandHJ hello!

NumPy coordinate conventions are a bit weird and that is not a mistake. See this page in the documentation:

https://scikit-image.org/docs/dev/user_guide/numpy_images.html#coordinate-conventions

So, ideally, that should be `r_idxs, c_idxs`, which would make it a bit more clear. But otherwise I think the code is right.

I'm going to close this issue but feel free to keep commenting on it or create new ones as you come across them!
