### ISSUE TITLE
Build process hard-requires pythran

### ISSUE THREAD

**Issue by ahesford** [scikit-image/scikit-image#6094]
## Description

The latest release (0.19.0) of `scikit-image` notes the option to use pythran instead of cython, but `pyproject.toml` lists pythran as a hard build requirement and setup scripts unconditionally try to import objects from `pythran.dist`. As a result, it is not possible to build `scikit-image` without installing pythran.

## (Partial) Fix
I don't know how to coerce `pyproject.toml` into what you need, but [a simple patch](https://github.com/scikit-image/scikit-image/files/7654087/no-pythran.patch.txt) will fix the import issues when building with setuptools.

**Comment by grlee77** [comment]
I think perhaps I just phrased this in a confusing way in the release notes. This is **supposed** to be a hard requirement at build time. Given that, I will close this as "won't fix" (although a PR to update the wording in the release notes may be appropriate).

The "optional" part was referring to **contributors** to scikit-image having the option to use either Cython or Pythran for compiled code. Both Cython and Pythran are required to build the library since it has a mixture of both types of implementations. In other words, Pythran support is not replacing Cython support but is in addition to it.
