### ISSUE TITLE
A new perspective on providing example galleries.

### ISSUE THREAD

**Issue by kolibril13** [scikit-image/scikit-image#6135]
## My idea in short:
A Jupyter cell magic, that takes the code of a cell and the corresponding example output image.
The cell magic then generates a html website, where one can see a gallery of all examples. 
When one clicks on an image on the website, the code pops up.
I've already written a prototype, here is a screen recording where you can see this idea in action:

https://user-images.githubusercontent.com/44469195/146995849-7a0edab8-281b-4cf4-95ba-9afb8e79ebde.mov

This can be extremely useful for all libraries that produce image cell output. 
With this cell magic, one can always keep code and output image close together and has a nice overview without the need to open the Jupyter notebooks. 
Projects where this might be useful, can be e.g. scikit-image, matplotlib, scipy, napari, or manim.
 
And now the cool thing:
This gallery can then simply be uploaded as a static website, e.g. at Github pages.
As I am quite active in the manim project, I've already built a gallery:
https://kolibril13.github.io/mobject-gallery/

And even cooler:
This gallery can also be used as a VS Code extension, you just click on one image, and the code snippet gets directly pasted to your VS Code jupyter-notebook, this VS Code extension also already exists for Manim, you can find an impression in this tweet: https://twitter.com/FlyingFramesIO/status/1469732058532618249

What happens under the hood:
The jupyter cell magic `capture_png`, that I developed together with  @krassowski_m saves the output image in a separate folder.
Furthermore, a json file is generated, that has the image path as a key, and the python code block as a value.
To the front end:
There is a html page which is the canvas.
A JavaScript file checks for the json file and when it finds content in it, it reads the image path and the corresponding code-string.
Lastly, there is some css involved to display the gallery correctly.
This was build as a prototype, therefore the code still looks like a mess, but it everything works as expected.

Pinging @jni and @tupui, as it was pleasant to be reviewed by you in my recent pull requests where I made some small contributions to the example galleries, you might be interested in this idea.

I think this has big potential: not only can package developers use this feature to create cheat sheet like overview galleries of their libraries, but also python users can use this feature to build their own personal snippet gallery. 
I know that there are already popular snippet tools, but I think this tool is special:
Normally, snippets work in a way that text is mapped to text. 
But here, we have text, that is mapped to images, and from my experience, the human association works better for images than for text files. Looking forward to your replies!  

EDIT: I've just published the gallery from the screen recording here: https://kolibril13.github.io/okapi/

**Comment by tupui** [comment]
This looks really cool! Thanks @kolibril13! I would suggest to move this discussion to the PyData Sphinx theme as this is the common theme we use in the projects.
Cc @jorisvandenbossche

**Comment by kolibril13** [comment]
I am a big fan of visuals, they make it so much easier to quickly get the idea of a function.
Thanks for the suggestion, I am closing this issue here, and we can discuss the idea in the PyData Sphinx repo.

**Comment by jni** [comment]
Hi @kolibril13! Thanks for the cool demo!

Yeah I'm not sure where this discussion belongs but it's not scikit-image. :joy: 

Anyway, my perspective on this, especially from the scikit-image and napari sides, is that it suffers from what I think is the main disadvantage of notebooks, which is the cell-cell and order execution dependence. The code snippets displayed for each cell may or may not be self-sufficient, because the necessary imports or even data definitions might come from an earlier cell — or even from a later cell, if I choose to execute the notebook out of order!

Meanwhile, sphinx-gallery comes with a lot of amazing features like each bit of the code linking back to the API documentation for that function, which we would not want to give up. And each of our gallery examples is completely self-contained and can be run as an independent Python script.

The idea of more tightly packing the images so that one can "at a glance" see all of the examples more easily is super great though, I agree with you that it makes it easier to find what you're interested in. I agree with @tupui that you should work with the PyData theme folks to get that working well for sphinx/sphinx-gallery.

Very happy to keep discussing and collaborating though, @kolibril13!

**Comment by kolibril13** [comment]
Thanks for the feedback, I've split this issue now into two other issues, one at pydata-sphinx-theme and one at https://github.com/napari/napari/issues/3864. @jni, to your first point, I sketched some ideas in the napari issue, 
and regarding the second point:
> Meanwhile, sphinx-gallery comes with a lot of amazing features like each bit of the code linking back to the API documentation for that function, which we would not want to give up. And each of our gallery examples is completely self-contained and can be run as an independent Python script.

Yes, the sphinx-gallery is amazing! I definitely don't want to replace it, these full independent Python scripts should still be there.  The jupyter generated gallery can be seen more as a supplement "cheat sheet" like gallery, as you said, all features  "at a glance" on one page.
