### ISSUE TITLE
Inconsistent default parameters for pyramid_reduce

### ISSUE THREAD

**Issue by hndgzkn** [scikit-image/scikit-image#6190]
## Description

The behavior of `pyramid_reduce` in https://github.com/scikit-image/scikit-image/blob/eaf9982ce7600c6a5e1371d98661a286680db153/skimage/transform/pyramids.py is different for versions `0.18.x` and `0.19.1`.

In `0.19.1` default parameters are inconsistent in that `multichannel=False` and `channel_axis=-1`. Setting `channel_axis=None` could fix the issue.

## Way to reproduce
```python
img = np.random.rand(256, 256)
print(img.shape)

img = skt.pyramid_reduce(img)
print(img.shape)
```

## Version information
```python
# Paste the output of the following python commands
3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0]
Linux-4.19.0-14-amd64-x86_64-with-glibc2.28
scikit-image version: 0.19.1
numpy version: 1.22.1
```

```python
Python 3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0] :: Anaconda, Inc. on linux

```

**Comment by mkcor** [comment]
Dear @hndgzkn,

You are absolutely right! Thanks for reporting.

A `multichannel=False` default should correspond to a `channel_axis=None` default, indeed. On the contrary, the `channel_axis=-1` default corresponds to the `multichannel=True` default.

I can see that we are missing a test where the `pyramid_reduce()` call would specify neither `multichannel` nor `channel_axis`. That's why this bug wasn't caught!

Would you mind submitting the bug fix and a corresponding test in `skimage/transform/tests/test_pyramids.py`? You might as well write the test before (TDD), based on your example if you like. :wink: 

Feel free to reach out, should you run into any roadblock!

**Comment by hndgzkn** [comment]
Dear @mkcor,

I'll submit a fix with the test. Thanks for the answer!
