### ISSUE TITLE
I have an image and I have generated contours for it using skimage.contour. How do I save the part of the image within each contour as an individual image file?

### ISSUE THREAD

**Issue by yashpansari** [scikit-image/scikit-image#6268]
## Way to reproduce
```python
def contourimage(image, image_gray, levels):
    fig, ax = plt.subplots(ncols=2, figsize=(10, 5))
    qcs = ax[1].contour(image_gray, levels = levels, origin='image')
    ax[1].set_title('Contour plot')
    ax[0].imshow(image)
    ax[0].set_title('Original')
    ax[0].axis('off')
    ax[1].axis('off')
    plt.show()
    return qcs
contourimage(imgs[0], imgs_gray[0], [1])
```

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print(f'scikit-image version: {skimage.__version__}')
import numpy; print(f'numpy version: {numpy.__version__}')
```

```python
3.8.8 (default, Apr 13 2021, 12:59:45) 
[Clang 10.0.0 ]
macOS-10.16-x86_64-i386-64bit
scikit-image version: 0.18.1
numpy version: 1.19.5
```

**Comment by mkcor** [comment]
Dear @yashpansari,

In the sample code you provided, you are using [matplotlib.pyplot.contour](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.contour.html). There is no module nor function named `skimage.contour`. Please see this [tutorial](https://scikit-image.org/docs/dev/auto_examples/edges/plot_contours.html) for finding contours with scikit-image.

I'll close this issue because your question is not related to scikit-image. Please post your question on a [matplotlib forum](https://discourse.matplotlib.org/) or on [image.sc](https://forum.image.sc/), a forum dedicated to image processing in general.
