### ISSUE TITLE
Problem with pillow: Closes the python program

### ISSUE THREAD

**Issue by Zazz96** [scikit-image/scikit-image#6282]
#Hello all, I recently started image analysis using python. I am learning basics and trying various tools to learn the image analysis and quantification. I think I have problem with pillow. Even running a small code like this it just stops python:

```
from PIL import Image

img = Image.open("Images/image002_ICC.TIF")

cropped_img = img.crop((0,0, 300, 300))
cropped_img.save("images/cropped_img.TIF")

```
I am getting notification that Python has stopped working.
After closing that notification, something like this appears on kernal:

runfile('S:/GENERAL/Shazeb/Image Analysis/Python/untitled13.py', wdir='S:/GENERAL/Shazeb/Image Analysis/Python')
Restarting kernel...

![image](https://user-images.githubusercontent.com/101566766/158336965-eb4500c5-2e34-4b58-87ba-a153282fa4ae.png)

## Version information
```python
# Paste the output of the following python commands
from __future__ import print_function
import sys; print(sys.version)
import platform; print(platform.platform())
import skimage; print(f'scikit-image version: {skimage.__version__}')
import numpy; print(f'numpy version: {numpy.__version__}')
```

```python
#runfile('S:/GENERAL/Shazeb/Image Analysis/Python/untitled14.py', wdir='S:/GENERAL/Shazeb/Image Analysis/Python')
3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
Windows-10-10.0.18363-SP0
scikit-image version: 0.18.3
numpy version: 1.20.3
```

The pillow version that I have is: PIL 8.4.0

I will be grateful for your inputs.

**Comment by hmaarrfk** [comment]
I hate bouncing you around, but it would be good if you could:

1. Include the file here as an attachment.
2. Post the issue to https://github.com/python-pillow/Pillow/issues


While we depend on pillow, it is important for us to offload this responsibility to ensure we can delegate resolving these bugs.

I would suggest looking into tifffile (with 3 f) while you work with pillow to get your issue resolved.

I think once you give them the image, they will be able to resolve it quickly because your example is so clear

**Comment by Zazz96** [comment]
Hey, Its working now. Thanks for your comment.

**Comment by hmaarrfk** [comment]
Do you mind sharing the details of what happened?

**Comment by Zazz96** [comment]
I think there was issue with the version of Pillow.

**Comment by hmaarrfk** [comment]
Nice find
