### ISSUE TITLE
measure.regionprops_table does not have num_pixels as a property

### ISSUE THREAD

**Issue by mehran66** [scikit-image/scikit-image#6337]
measure.regionprops_table does not have num_pixels as a property:

props = measure.regionprops_table(label_image, image,
                          properties=['label', 'num_pixels',
                                      'area', 'bbox', 'coords',
                                      'mean_intensity', 'solidity'])

AttributeError: '<class 'skimage.measure._regionprops.RegionProperties'>' object has no attribute 'num_pixels'

## Version information
3.9.5 (default, May 18 2021, 14:42:02) [MSC v.1916 64 bit (AMD64)]
Windows-10-10.0.19044-SP0
scikit-image version: 0.19.2
numpy version: 1.22.3

**Comment by grlee77** [comment]
Hi @mehran66, if you are seeing `num_pixels` in the docs, you must be looking at a development version of the docs rather than those for a released version. Please see the [stable version](https://scikit-image.org/docs/stable/api/skimage.measure.html) for docs corresponding to the most recent release.

`area` should be just the number of pixels in v0.19.x releases. In a future release, `area` will take into account the pixel spacings so that it is not necessarily the same as the number of pixels (see #6296).
