### ISSUE TITLE
skimage.metrics.structural_similarity work fine with batch of 32 grayscale image but got error for a batch of 2 or 3

### ISSUE THREAD

**Issue by MegaCreater** [scikit-image/scikit-image#6388]
## Description
When I try to calculate ssim (using  skimage.metrics.structural_similarity) for a batch of 32 grayscale (black and white) images it is working fine (even work for 16 , 8 or 7 images batch). But when the batch is of 3 or 2 images it is throwing an error - `ValueError: win_size exceeds image extent.  If the input is a multichannel (color) image, set multichannel=True.` 

## Code - skimage.metrics.structural_similarity
```python
# Working fine for batch of 32 grayscale images 
skimage.metrics.structural_similarity(np.random.randint(0,255,size=(32,256,256)).astype('uint8'),
                np.random.randint(0,255,size=(32,256,256)).astype('uint8'),multichannel=False)
# work fine 
```
```python
# But got error for 2 or 3 images batch (for all batch sizes from 1 to 6) 
structural_similarity(np.random.randint(0,255,size=(2,256,256)).astype('uint8'),
                      np.random.randint(0,255,size=(2,256,256)).astype('uint8'),multichannel=False)
# Got --->
# ValueError: win_size exceeds image extent.  If the input is a multichannel (color) image, set multichannel=True.
```

Question : Can be calculate ssim, using  skimage.metrics.structural_similarity with batch of image? Does we have a correct result?

#### Version information
```python
3.7.13 (default, Apr 24 2022, 01:04:09) 
[GCC 7.5.0]
Linux-5.4.188+-x86_64-with-Ubuntu-18.04-bionic
scikit-image version: 0.18.3
numpy version: 1.21.6
# Environment - Google Colaboratory 
```

**Comment by rfezzani** [comment]
Hello @MegaCreater and thank you for your interest in `skimage`.

In the version 0.19 of `skimage`, the raised error message is more explicit:
> ValueError: win_size exceeds image extent. Either ensure that your images are at least 7x7; or pass win_size explicitly in the function call, with an odd value less than or equal to the smaller side of your images. If your images are multichannel (with color channels), set channel_axis to the axis number corresponding to the channels.

In the example you provided, the image batches are considered as 3D volumes. In this case, the images are filtered over the all 3 dimensions. If the individual images composing your batches are independent, this may give some strange outputs...

If the individual images are independent, I recommend you set `channel_axis` to 0 or (`multichannel` to `True` in your case) so that the SSIM is computed as the average the SSIM of each pair of corresponding images in the batch.

**Comment by grlee77** [comment]
I agree with @rfezzani except that `multichannel=True` assumes that channels (or batch in this case) are along the last axis. You will either have to transpose so that the batch dimension is last or upgrade to v0.19 so that you can specify `channel_axis=0`.

**Comment by MegaCreater** [comment]
Thanks. @rfezzani and @grlee77
