### ISSUE TITLE
Tests are failing with NumPy 1.23rc

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#6397]
## Description

Our tests are failing with the latest NumPy pre-release, example failure here:

https://github.com/scikit-image/scikit-image/runs/6701244383

All the failures appear to be of the form:

```pytb
scikit-image/skimage/feature/__init__.py:23: in <module>
    from .orb import ORB
scikit-image/skimage/feature/orb.py:12: in <module>
    from .orb_cy import _orb_loop
skimage/feature/orb_cy.pyx:13: in init skimage.feature.orb_cy
    ???
scikit-image/skimage/feature/_orb_descriptor_positions.py:8: in <module>
    POS = np.loadtxt(os.path.join(this_dir, "orb_descriptor_positions.txt"),
/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/numpy/lib/npyio.py:1301: in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/numpy/lib/npyio.py:979: in _read
    arr = _load_from_filelike(
E   ValueError: could not convert string '8.000000000000000000e+00' to int8 at row 0, column 1.
```

And can presumably be fixed by updating the load function or (preferably, I think?) the txt files.

**Comment by hmaarrfk** [comment]
did they add a casting keyword? I feel like this is somewhat a breaking change that we can plea to reconsider. we likely exported as floating point, but are trying to read as int, and it is complaining about it.

**Comment by seberg** [comment]
Stumbled on this.  There are the converters which are more convenient now (no casting), but that hardly matters... ?

First thing (IMO) is just fixing it:  There is no point storing integers as floats whether NumPy likes it or not.  And I will *definitely* want to deprecate it if we put it back, and you want to avoid that warning.

The other question is whether you think NumPy can't get away with the change.  Either generally, or because skimage can't get away with it (easily).

For `skimage` that means asking whether: 
1. a `0.19.3` release will happen soon (~1 month) – it would not be nice if upgraing skimage is not a valid fix.   (seems plausible to me for Python 3.11 support?)
2. usage is a niche enough that its OK to tell the couple of users that they can't use a brand new NumPy without also using a brand new skimage if they run into it.

On the plus side, loading the file will be much faster ;).

**Comment by hmaarrfk** [comment]
> Either generally, or because skimage can't get away with it (easily).

Releases are tricky. I can't guarantee that we will get it out in time. But yeah... we could fix it.

**Comment by hmaarrfk** [comment]
Looking at the numpy documentation, i think the issue will be more widespread than you think. The default formatter was that of a floating point number. THerefore, everybody has been saving by default as `'%.18e'`.

I'm not sure it is so smart to not fix this on the numpy side.
