### ISSUE TITLE
Why graycomatrix gives same results between 1px and 2px distances at 45 or 135 degrees orientation? 

### ISSUE THREAD

**Issue by statcom** [scikit-image/scikit-image#6424]
## Description

As title says, graycomatrix gives the same results between 1px and 2px distances at 45 or 135 degrees orientation. Accordingly all GLCM features are the same between 1px and 2px distances with the specific orientation. I don’t understand why. Here is an example. Is this a bug or am I missing something? I don’t have this issue with 0 and 90 degrees orientations.

## Way to reproduce
```from skimage.feature import graycomatrix
image = np.array([[0, 0, 1, 1],
                  [0, 0, 1, 1],
                  [0, 2, 2, 2],
                  [2, 2, 3, 3]], dtype=np.uint8)
g = graycomatrix(image, [1, 2], [np.pi/4, 3*np.pi/4], levels=4,
                 normed=True, symmetric=True)
contrast = graycoprops(g, 'contrast')
print(contrast)
```

## Version information
```python
3.9.11 (tags/v3.9.11:2de452f, Mar 16 2022, 14:33:45) [MSC v.1929 64 bit (AMD64)]
Windows-10-10.0.19042-SP0
scikit-image version: 0.19.2
numpy version: 1.22.3
```

## My output
```python
[[1.77777778 0.44444444]
 [1.77777778 0.44444444]]
```

**Comment by jni** [comment]
That's because on the diagonal the distance between pixels is `sqrt(1**2 + 1**2)` = `sqrt(2)` ≈ 1.41. With nearest-neighbor interpolation, you get that pixel value between `sqrt(2) ± sqrt(2)/2` ≈ [0.707, 2.12]. This interval contains both 1 and 2, so that's why you get the same value. If you want to measure "one pixel along the diagonal" and "two pixels along the diagonal", then multiply your distances by `sqrt(2)`.

I hope this helps clarify!
