### ISSUE TITLE
morphology.remove_small_objects do not worked as expect

### ISSUE THREAD

**Issue by shevawen** [scikit-image/scikit-image#6471]
## Description

morphology.remove_small_objects do not work as expect.

## Way to reproduce

[input.txt](https://github.com/scikit-image/scikit-image/files/9374061/input.txt)

```python
import numpy
from skimage import morphology

input = numpy.loadtxt("input.txt")
# small objects not removed as expect.
out = morphology.remove_small_objects(input.astype(int), 6)

input = input[20:, :]
# small objects removed.
out = morphology.remove_small_objects(input.astype(int), 6)

```

## Version information
```python
3.7.7 (default, May  6 2020, 04:59:01) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
Darwin-21.5.0-x86_64-i386-64bit
scikit-image version: 0.19.2
numpy version: 1.19.5
```

**Comment by lagru** [comment]
Hello @shevawen. `morphology.remove_small_objects` expects the holes to be labeled if the input image is not of type `bool`. However you provide an input only containing 1 and 0 which causes all pixels with a 1 to be counted as the same object which incidentally is 6 pixels large. Just enough to satisfy your given requirement of `min_size=6`. You can either turn the input into a boolean array so that `remove_small_objects` labels the object itself 
```python
out = morphology.remove_small_objects(input.astype(bool), 6)
out.sum()  # returns 0
```
or do so yourself:
```python
import scipy.ndimage as ndi
labeled, _ = ndi.label(input)
out = morphology.remove_small_objects(labeled, 6)
out.sum()  # returns 0
```

You can find this documented in the [function's docstring](https://scikit-image.org/docs/dev/api/skimage.morphology.html?highlight=remove_small_objects#remove-small-objects).

**Comment by shevawen** [comment]
Hi @lagru , thanks for replying. That helps me a lot.
