### ISSUE TITLE
Installing scikit-image on Python 3.11

### ISSUE THREAD

**Issue by emadyounan** [scikit-image/scikit-image#6598]
### Description:

I have python 3.11 on windows 11 Yesterday I tried to install scikit-image but I faced some issues belong to c++ i installed it and windows sdk 10 and that issue disappeared but I got another one that I don't really what is it? at the screenshot please help me 

https://ibb.co/9vpw86L

**Comment by hmaarrfk** [comment]
Python 3.11 just got released Oct 24th 2022. Please be patient in expecting software like scikit-image to be installed on there "smoothly"

Please follow the tracking issue on making it easier to install scikit-image on python 3.11 here https://github.com/scikit-image/scikit-image/issues/6517

I think you would be best served by using Python 3.9 or Python 3.10.

It is not that I don't think you question is valid, but the level of detail you provided in the bug report hints that you would prefer to use scikit-image (which a stable version of python would help with), rather than develop scikit-image (which you would be forced to do on Python 3.11).

Please let me know if using Python 3.10  or 3.9 resolves your issues.

**Comment by jarrodmillman** [comment]
See https://pypi.org/project/scikit-image/0.20.0rc8/#files

**Comment by stefanv** [comment]
We're about to publish the next release, so closing this to clear the milestone.
