### ISSUE TITLE
SSIM should fail unless data_range specified (especially for float)

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#6602]
### Description:

See https://github.com/scikit-image/scikit-image/pull/6595

**Comment by mcourteaux** [comment]
Nice, working on this, I find places in the tests where the SSIM is already incorrectly calculated. Amazing. :P

**Comment by mcourteaux** [comment]
Here is an example:
https://github.com/scikit-image/scikit-image/blob/e68ff347ab6ce7bace14c911aed752c2323b65c0/skimage/metrics/tests/test_structural_similarity.py#L157-L168

My question is: ideally, this test checks if all SSIMs are close, instead of just "statistically low enough". But that requires to compare the results of different parameterizations. I would then just delete this parameterization and make it a single test, I guess?
