### ISSUE TITLE
Incorrect order of code and output in rendered applications/plot_thresholding.py

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#6618]
See https://forum.image.sc/t/incorrect-order-of-code-and-output-on-doc-page/73749

Gallery example images are not being placed in the right order. Could be a sphinx-gallery bug?

### Way to reproduce:

- Navigate to https://scikit-image.org/docs/dev/auto_examples/applications/plot_thresholding.html
- Note that the plot underneath the first code snippet is switched with the one for the next

Thanks to @pamitabh for reporting :pray:

**Comment by lagru** [comment]
Ha, solved it! It's because we have two gallery examples that use the same name. Renaming either [`applications/plot_thresholding.py`](https://github.com/scikit-image/scikit-image/blob/main/doc/examples/applications/plot_thresholding.py) ([HTML](https://scikit-image.org/docs/dev/auto_examples/applications/plot_thresholding.html)) or  [`segmentation/plot_thresholding.py`](https://github.com/scikit-image/scikit-image/blob/main/doc/examples/segmentation/plot_thresholding.py) ([HTML](https://scikit-image.org/docs/dev/auto_examples/segmentation/plot_thresholding.html)) fixes this behavior. 

This is because Sphinx Gallery uses only the file name of each example to name the output images, so those two clash and the output images are scambled. In this case `segmentation/plot_thresholding.py` takes preceedence over `applications/plot_thresholding.py`. We should have noticed, as the first plot contains three columns while the code only declares two. 

Honestly, this bug was kind of rewarding to figure out! :smile:

The quickest fix for the release is probably to rename one of the files; I'll do the PR tomorrow if nobody beats me to it. But long term we should probably make those examples more distinct from each other or merge them.

**Comment by stefanv** [comment]
Yikes! Is it even possible for Sphinx gallery to identify this problem? Should we add a manual check for duplicate filenames?

**Comment by lagru** [comment]
Not sure. I've opened an issue over at sphinx-gallery to discuss this. Otherwise, we could maybe add a check somewhere on our side. But I'd prefer to avoid such custom patches.
