### ISSUE TITLE
Off-centre markers for watershed

### ISSUE THREAD

**Issue by rijobro** [scikit-image/scikit-image#6632]
### Description:

The watershed gives sub-optimal results when the marker is off-centre relative to the maximum of the distance map. I am unsure as to whether this is a bug or to be expected.

If a marker is close to (but not on top of) the maximum of the distance map, I would expect the water to flow towards the max of the distance map, and then continue fill up as normal. However, this is not the case. I have taken the code from the watershed example and offset the markers by 6 pixels in the y-direction. The resulting segmentations are incorrect as shown in the attached image.

### Way to reproduce:

```Python
import numpy as np
import matplotlib.pyplot as plt
from scipy import ndimage as ndi

from skimage.segmentation import watershed
from skimage.feature import peak_local_max

# Generate an initial image with two overlapping circles
x, y = np.indices((80, 80))
x1, y1, x2, y2 = 28, 28, 44, 52
r1, r2 = 16, 20
mask_circle1 = (x - x1)**2 + (y - y1)**2 < r1**2
mask_circle2 = (x - x2)**2 + (y - y2)**2 < r2**2
image = np.logical_or(mask_circle1, mask_circle2)

# Now we want to separate the two objects in image
# Generate the markers as local maxima of the distance to the background
distance = ndi.distance_transform_edt(image)

fig, axes = plt.subplots(ncols=4, figsize=(9, 3), sharex=True, sharey=True, facecolor="white")
ax = axes.ravel()

ax[0].imshow(image, cmap=plt.cm.gray)
ax[0].set_title('Overlapping objects')
ax[1].imshow(-distance, cmap=plt.cm.gray)
ax[1].set_title('Distances')

# shift by 0 or 6 pixels to demonstrate what happens when the markers
# don't perfectly align with the distance map
for i, dy in enumerate((0, 6)):
    coords = peak_local_max(distance, footprint=np.ones((3, 3)), labels=image)
    coords[:, 0] += dy
    mask = np.zeros(distance.shape, dtype=bool)
    mask[tuple(coords.T)] = True
    markers, _ = ndi.label(mask)
    labels = watershed(-distance, markers, mask=image)
    ax[i+2].imshow(labels)
    ax[i+2].imshow(markers, alpha=(markers>0).astype(float))
    ax[i+2].set_title(f'watershed. dy={dy}')

for a in ax:
    a.set_axis_off()

fig.tight_layout()
plt.show()
```

### Traceback or output:

![image](https://user-images.githubusercontent.com/33289025/204031760-946d5859-a13b-4503-816c-dfcb683e2175.png)

### Version information:

```python
>>> import sys; print(sys.version)
3.9.7 (default, Sep 16 2021, 08:50:36) 
[Clang 10.0.0 ]
>>> import platform; print(platform.platform())
macOS-10.16-x86_64-i386-64bit
>>> import skimage; print(f'scikit-image version: {skimage.__version__}')
scikit-image version: 0.19.3
>>> import numpy; print(f'numpy version: {numpy.__version__}')
numpy version: 1.21.2
```

**Comment by jni** [comment]
@rijobro sorry that this fell through the cracks. I think you're absolutely right that this is a bug, and a critical one at that. I've encountered it myself a few times but never had time to investigate.

@lagru do you think you could look at this sometime soon? 🙏

**Comment by lagru** [comment]
Okay, I think this is what is happening: For `dy=6`, the green marker has the starting "depth" -10, and the yellow marker -14. Therefore the the yellow basin is filled up first until the depth -10 is reached. However, if you look closely at the distance map, the connection between both basins seems to have a value of -10.82, barely below the depth of the second marker! This makes the "yellow water" spill over into the second basin until the level -10 is reached. At some point the neighborhood of the green marker is evaluated. If I stop the algorithm at that point, this is the output we get

![image](https://github.com/scikit-image/scikit-image/assets/20140352/03933ce7-23c0-4800-b72e-11886817d8bc)

Now, when the next item is drawn from the heap (to evaluate its neighborhood), this will be a yellow item due to both value and age. This will further the yellow watershed until it's reached the height of the green marker: 

![image](https://github.com/scikit-image/scikit-image/assets/20140352/fb54a765-9ab4-4171-92f3-865a8cde8ab2)

After this the next item is part of the green watershed, however by that point there is only one pixel left to fill up:

![image](https://github.com/scikit-image/scikit-image/assets/20140352/c62572fe-0a99-4e97-af9d-8ada024b64ce)

This process repeats until we get the result we see above. For `dy<6` the behavior is different, because in that case the green marker has a depth of -11, which is below the channel that connects both basins. Therefore the spilling over doesn't happen.

(To inspect and debug this I used this patch [Use_Python_version_of_watershed_raveled.patch.txt](https://github.com/scikit-image/scikit-image/files/11614388/Use_Python_version_of_watershed_raveled.patch.txt))

---

Now, I am not yet sure if this is a bug or just a how the watershed is expected to work as we don't take the gradient into account at all.

**Comment by lagru** [comment]
Oh and @rijobro, thanks so much for the perfect reproducing example! That made it very easy to investigate. :)
