### ISSUE TITLE
Dilation and erosion image boundary extension

### ISSUE THREAD

**Issue by crisluengo** [scikit-image/scikit-image#6665]
### Description:

Currently, `skimage.morphology.dilation` calls `scipy.ndimage.grey_dilation` with the default `mode` value (boundary extension, this is what the filter does outside the image bounds). The default is `'reflect'`, which fills in values outside the image using values from inside the image. The same applies to `erosion` and other morphological filters.

With dilations and erosions, if the structuring element is compact, this will not matter at all. It samples some of the pixels twice. But if the structuring element is not compact, then it will sample some pixels we didn't intend to sample. See for example [this Stack Overflow answer I just posted](https://stackoverflow.com/a/75049306/7328782), where the structuring element doesn't include the central pixel.

Ideally, we'd extend the boundary with the minimum allowed value for the data type (or the maximum in the case of the erosion). This way, pixels outside the image will not influence the result at all. This can be accomplished by setting the `mode` and `cval` arguments to `scipy.ndimage.grey_dilation` appropriately:
```python
ndi.grey_dilation(image, footprint=footprint, output=out, mode="constant", cval=np.iinfo(image.dtype).min)
```
(to be tested that this works OK in ndimage with 64-bit integer arrays and so forth).

Alternatively, one could consider allowing the user to select a boundary extension method.

BTW: I'm happy to send a PR, but I didn't know which solution this community preferred.

**Comment by lagru** [comment]
Thanks @crisluengo for the detailed description. 

To be honest, I'm not really sure what value our wrapper for `scipy.ndimage.grey_dilation` is really adding besides the `shift_` parameters. We could easily just expose the `_shift_footprint` function if necessary. As it's mainly a wrapper I'm in favor of letting the user chose the mode rather than changing our default. In any case, we should document the behavior at the edges properly in the docstring. 

Feel free to make a PR and tag me if nobody raises any other concerns in the meantime.

**Comment by lagru** [comment]
Linking https://github.com/scikit-image/scikit-image/issues/7238.
