### ISSUE TITLE
No module named 'skimage.feature._canny_cy

### ISSUE THREAD

**Issue by salvarezaie** [scikit-image/scikit-image#6748]
### Description:

ModuleNotFoundError: No module named 'skimage.feature._canny_cy
When I test the skimage I encounter 31 errors, all involving the above error.

**Comment by stefanv** [comment]
We need some more information, please. Version, how installed, etc.

**Comment by salvarezaie** [comment]
I think I figured it out. In the new version, the watershed is under segmentation, and in previous ones it was under morphology. Thank you

**Comment by stefanv** [comment]
👍

**Comment by stefanv** [comment]
No, wait, that error still shouldn't appear, unless you're importing a private module explicitly.

**Comment by salvarezaie** [comment]
yeah my other packages were searching for watershed under morphology.

**Comment by mkcor** [comment]
Pardon me if I'm hijacking this thread... Personally, the `ModuleNotFoundError` I'm getting is `No module named 'lazy_loader'` after trying to follow https://github.com/scikit-image/scikit-image/blob/main/meson.md from a fresh clone.

I ditched my good old virtualenv and decided to start anew with Meson. Following https://github.com/scikit-image/scikit-image/blob/main/meson.md#developer-build, after installing `devpy` (no big deal),  I couldn't run `./dev.py build` because there was no `build` directory at that point:
```
$ meson setup ${PWD}/build --prefix=/usr
[Errno 2] No such file or directory: 'meson'; aborting.
```
So I went for the [explicit route](https://github.com/scikit-image/scikit-image/blob/main/meson.md#developer-build-explicit), encountered this [issue](https://github.com/mesonbuild/meson/issues/7345), installed `pytest`, and here I am.

I'm running Python 3.9.15 on Debian GNU/Linux 11 (bullseye) and I haven't created an isolated environment...

**Comment by stefanv** [comment]
@mkcor I'm not sure why your system is asking for root permissions; nothing we do requires that!

You absolutely should build in a virtual env, but I presume when you say "I haven't created an isolated environment" you don't mean you're using the system Python env.

And are you seeing the same issue reported here? If not, let's start a new issue to track your case.

**Comment by mkcor** [comment]
Thanks for the quick reply, @stefanv!

> @mkcor I'm not sure why your system is asking for root permissions; nothing we do requires that!

Apparently this 'feature' comes straight from `meson` and it is currently being 'fixed' (or, rather, [handled better](https://github.com/mesonbuild/meson/pull/11366)). 

> You absolutely should build in a virtual env, but I presume when you say "I haven't created an isolated environment" you don't mean you're using the system Python env.

I am testing these [instructions](https://github.com/scikit-image/scikit-image/blob/main/meson.md#building-with-meson) as if I were a brand new contributor (e.g., an intern :wink:). Also, I used to use `pip install -e .` and, for docs, the old `make html`, so I would like to update my own setup, to use the `dev.py` tool, etc.

Are the `meson` build instructions supposed to become a replacement for [these](https://scikit-image.org/docs/dev/install.html#installing-scikit-image-for-contributors)?

Oh, so, to answer the question, I haven't created a new, dedicated virtual or conda env yet, because it wasn't explicitly mentioned in the `meson` build instructions: But maybe these are not ready as in {self-contained, self-sufficient, ready to be published}?

> And are you seeing the same issue reported here? If not, let's start a new issue to track your case.

It's a ModuleNotFoundError but it's not the same... I'm not sure how I should name my issue, because maybe I'm doing something which is not meant to be in the first place: Trying to set up a dev env from current the meson build instructions? :pray:

**Comment by mkcor** [comment]
@salvarezaie were you able to resolve this issue?

**Comment by stefanv** [comment]
Unable to replicate; please try the latest release.
