### ISSUE TITLE
`measure.regionprops` assumes input is a numpy array

### ISSUE THREAD

**Issue by IanButterworth** [scikit-image/scikit-image#6812]
### Description:

`skimage.measure.regionprops` appears to assume the input is a numpy array, and directly accesses the dtype attribute.

Instead it should coercing its input to one with `numpy.asarray`

This was observed on the interface with Julia & Python at https://github.com/cjdoris/PythonCall.jl/issues/280

### Way to reproduce:

```Python
julia> labelled_frame = zeros(Int, 10, 10); labelled_frame[5:6, 5:6] .= 1;

julia> using PythonCall

julia> skimage = pyimport("skimage")
Python module: <module 'skimage' from '/Users/ian/Documents/GitHub/Foo.jl/.CondaPkg/env/lib/python3.11/site-packages/skimage/__init__.py'>

julia> skimage.measure.regionprops(labelled_frame)
ERROR: Python: AttributeError: Julia: type Array has no field dtype
Python stacktrace:
 [1] __getattr__
   @ ~/.julia/packages/PythonCall/dsECZ/src/jlwrap/any.jl:189
 [2] regionprops
   @ skimage.measure._regionprops ~/Documents/GitHub/Foo.jl/.CondaPkg/env/lib/python3.11/site-packages/skimage/measure/_regionprops.py:1253
Stacktrace:
 [1] pythrow()
   @ PythonCall ~/.julia/packages/PythonCall/dsECZ/src/err.jl:94
 [2] errcheck
   @ ~/.julia/packages/PythonCall/dsECZ/src/err.jl:10 [inlined]
 [3] pycallargs(f::Py, args::Py)
   @ PythonCall ~/.julia/packages/PythonCall/dsECZ/src/abstract/object.jl:210
 [4] pycall(f::Py, args::Matrix{Int64}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ PythonCall ~/.julia/packages/PythonCall/dsECZ/src/abstract/object.jl:228
 [5] pycall
   @ ~/.julia/packages/PythonCall/dsECZ/src/abstract/object.jl:218 [inlined]
 [6] #_#11
   @ ~/.julia/packages/PythonCall/dsECZ/src/Py.jl:352 [inlined]
 [7] (::Py)(args::Matrix{Int64})
   @ PythonCall ~/.julia/packages/PythonCall/dsECZ/src/Py.jl:352
 [8] top-level scope
   @ REPL[35]:1
```
```


### Traceback or output:

_No response_

### Version information:

_No response_

**Comment by stefanv** [comment]
To be fair, the documentation states:

````
    label_image : (N, M[, P]) ndarray
```

So, I don't think we /have/ to coerce to a numpy array.

@scikit-image/core Still, a question we want to answer, do we want to call `np.asarray` consistently on inputs throughout the library?

**Comment by jni** [comment]
Yeah, I agree that "should" is too strong a word here. 😅 But it's useful to have the discussion.

My own personal preference is that scikit-image should one day be able to take any input compliant with the [array-api](https://github.com/data-apis/array-api), and coerce to NumPy only if needed. In the case of regionprops we definitely do need a NumPy array because of all the cython code. So it would be good to coerce.

Having said *that*, array-api does specify a .dtype attribute. ;)

**Comment by IanButterworth** [comment]
Didn't mean to be so strong worded. Thanks for considering

**Comment by stefanv** [comment]
Since we often send images to Cython/Pythran (i.e., we access memory directly), I don't think we have the option of only relying on the Array API. If you call `np.asarray` on a dask or a GPU array, presumably you'll copy that array to the local machine / CPU side, which can be disastrous. We can do it, it just won't benefit most users of those objects.

But @grlee77 and @jakirkham would know better.

**Comment by soupault** [comment]
I have faced so many issues with implicit type conversion in scientific Python code over the past years, that my preferences shifted towards stricter flavours of typing and a clear communication thereof. From my perspective, since the documentation says in multiple places that `skimage` expects data to be in NumPy ndarrays (https://scikit-image.org/docs/stable/user_guide/getting_started.html, https://scikit-image.org/docs/stable/user_guide/numpy_images.html, regionprops) and having concerns voiced by @stefan above, I would keep things unchanged.

P.S. When/if we decide to implement the support for array-api, that should also go through a SKIP process (and following the spirit of https://github.com/scikit-image/scikit-image/pull/7159#issuecomment-1741742564).

**Comment by lagru** [comment]
Agreed. Longterm I'd rather see this resolved via something like the [Python array API standard ](https://data-apis.org/array-api/latest/).

So for now slightly in favor of closing this as won't fix.

**Comment by lagru** [comment]
Closing this for now. Everyone please feel welcome to reopen and disagree.

**Comment by lagru** [comment]
@IanButterworth thanks for raising this issue. :)
