### ISSUE TITLE
Analyzing the Drosophila Embryo Development using Scikit image(Contribution for outreachy)

### ISSUE THREAD

**Issue by anushka-png** [scikit-image/scikit-image#6845]
### Analyzing the Drosophila Embryo Development  using Scikit image

Using scikit image for the analysis of embryo development in drosophila , I  took three screenshot from two movies ,the first one is the early stage of drosophila and second one is showing the dorsal and ventral view so by some image analysis and tried to compare the two images (early stage and ventral image).

Second one as by suggestion, I tried to analyze the zebrafish (figure 6 and 9 of https://www.science.org/doi/10.1126/science.1162493) and drosophila DV curves . This is the link which contains the jupyter book , html file for code and output and finally one pdf containing the comparison ,
link : https://drive.google.com/drive/folders/1RDkkn0HiPoSV9v6HitidSL99Smvb7oeM?usp=share_link

### Comparison
[Drosophila(scikit image).pdf](https://github.com/scikit-image/scikit-image/files/11016020/Drosophila.scikit.image.pdf)

Requesting you to please check if this satisfies the task to some extent as I tried this for the first time.
Thank you

**Comment by mkcor** [comment]
Dear @anushka-png,

Would you like me to review your work here (on GitHub) or should I continue in private (over Zulip)?

Thanks,
Marianne

**Comment by mkcor** [comment]
Dear @anushka-png,

Actually, GitHub issues are not the right place to have this kind of conversation. From https://github.com/scikit-image/scikit-image/issues/new/choose, you should typically post on the [user forum](https://forum.image.sc/tag/scikit-image) (where you can tag me with the same handle). Otherwise, we can continue the conversation in private.

Thank you,
Marianne
