### ISSUE TITLE
<Watershed not using local minima as markers by default, contradicting documentation.>

### ISSUE THREAD

**Issue by samyblusseau** [scikit-image/scikit-image#7117]
### Description:

When running the watershed function without markers (markers = None), the function does not use local minima as markers contrary to what the documentation says.

The result with markers = None is clearly different than with markers = local_minima, while it is supposed to be the same.

With markers=None, the number of returned regions is way larger than the number of local minima, at least on several examples.

### Way to reproduce:

``` python

import skimage
from skimage.data import camera
from skimage.morphology import local_minima, label
from skimage.segmentation import watershed

print('\nSkimage version:', skimage.__version__,'\n')

im = camera()
locMin = label(local_minima(im)) # local minima

# Markers = None, supposedly local minima taken as markers
imWs1 = watershed(im, watershed_line = True)
print('Watershed with markers=None (supposedly local minima used as markers):')
print('There are '+str(imWs1.max())+ ' basins, and '+str(locMin.max())+' local minima.\n')


# Markers explicitely chosen as local minima
imWs2 = watershed(im, markers = locMin, watershed_line = True)
print('Watershed with local minima as markers:')
print('There are '+str(imWs2.max())+ ' basins, and '+str(locMin.max())+' local minima.')

```

### Version information:

```Shell
3.9.16 (main, May 15 2023, 23:46:34) 
[GCC 11.2.0]
Linux-5.4.0-150-generic-x86_64-with-glibc2.27
scikit-image version: 0.21.0
numpy version: 1.24.3
```

**Comment by mkcor** [comment]
Hi @samyblusseau,

Thank you for reporting. From looking at the source code, it turns out that the default markers are somehow computed as the local minima, but *not* just through `ski.morphology.label(ski.morphology.local_minima(image))`. Instead:

https://github.com/scikit-image/scikit-image/blob/2ac3e141e8d2e31aa0ec10afc3a935396b0618fc/skimage/segmentation/_watershed.py#L65-L68

Running this code with your example (`image = ski.data.camera()`, `connectivity = 1`, `mask = np.ones(image.shape, bool)`) yields 22963 markers (and, hence, basins, as you reported).

Now, if you just change `connectivity = 2` in the above, you end up with 13563 markers / basins (which, as you reported, is also the result obtained from `ski.morphology.label(ski.morphology.local_minima(image))`).

We should definitely improve the documentation, indeed...

@ana42742 fyi :eyes:

**Comment by mkcor** [comment]
Hi @samyblusseau,

It is a matter of computing the local minima differently, as I wrote in my initial reply https://github.com/scikit-image/scikit-image/issues/7117#issuecomment-1712530226. By running the code I highlighted there, you can break down this computation as carried out in the `watershed` function. For example, just the `label` function from `scipy.ndimage` behaves differently from the `label` function from `skimage.morphology`!

Otherwise, you can find `_watershed_cy.watershed_raveled` in the codebase:
https://github.com/scikit-image/scikit-image/blob/2ac3e141e8d2e31aa0ec10afc3a935396b0618fc/skimage/segmentation/_watershed_cy.pyx#L70

But, again, the discrepancy arises at
https://github.com/scikit-image/scikit-image/blob/2ac3e141e8d2e31aa0ec10afc3a935396b0618fc/skimage/segmentation/_watershed.py#L199

which happens way before hitting
https://github.com/scikit-image/scikit-image/blob/2ac3e141e8d2e31aa0ec10afc3a935396b0618fc/skimage/segmentation/_watershed.py#L215

Best,
Marianne

**Comment by samyblusseau** [comment]
Thanks again @mkcor , sorry I did not understand earlier.
It seems the discrepancy is precisely in the difference in `label` functions between  `skimage.morphology` and `scipy.ndimage`, as you point out.

I hope I'll have a chance to have a look at the latter some day.

Best,
Samy

**Comment by mkcor** [comment]
> We should definitely improve the documentation, indeed...

Done with ac0009bea20191f2a8cc023214d271e00552cac8 for now.

Replacing the code I highlighted in https://github.com/scikit-image/scikit-image/issues/7117#issuecomment-1712530226 with `ski.morphology.label(ski.morphology.local_minima(image))` would be a backwards-incompatible API change. This move would be towards more consistency; @scikit-image/core do we want it for `skimage2`?

**Comment by lagru** [comment]
Replacing with `ski.morphology.label(ski.morphology.local_minima(image))` would certainly be something for skimage2. It certainly feels a bit more like an expected default. But it'd be still an additional breaking change to document. I feel like users that would really care about this detail are gonna use explicit markers anyway so I am leaning towards it not being worth the effort?

**Comment by mkcor** [comment]
@lagru thanks for sharing your perspective; I see what you mean (e.g., in a research setting). To expand on the consistency argument, there's a second level I see: We wouldn't need `ndimage` there anymore. I can't remember exactly, but do we want to stop depending on `ndimage` ultimately / in skimage2?

**Comment by mkcor** [comment]
I've added an [entry](https://github.com/scikit-image/scikit-image/wiki/API-changes-for-skimage2#skimagesegmentation) to the wiki so it doesn't fall in the cracks of the skimage2 transition.

**Comment by lagru** [comment]
> I can't remember exactly, but do we want to stop depending on ndimage ultimately / in skimage2?

Probably a topic for our forum. But my 2cts: which version to use is probably a case by case decision. If there are two similar versions of a function there is probably a reason for it (otherwise we should simply deprecate our version).

> I've added an [entry](https://github.com/scikit-image/scikit-image/wiki/API-changes-for-skimage2#skimagesegmentation) to the wiki so it doesn't fall in the cracks of the skimage2 transition.

Thanks! In this case I am happy with using and teaching our `label` function in skimage2.
