### ISSUE TITLE
Applying iRadon then Radon does not return array to original shape

### ISSUE THREAD

**Issue by GeorgeWebber** [scikit-image/scikit-image#7222]
### Description:

Would expect applying the functions `iradon` and then `radon` would return an array to its original shape. However, with the particular shape of (400,168), an array of shape (399, 168) is returned. 

This bug does not occur for arrays of shape (n, 168) for n != 400 (as far as observed so far)

### Way to reproduce:

```
from skimage.transform import radon, iradon
import numpy as np

sino = np.zeros((400, 168))
azi_angles = np.linspace(0.0, 180.0, 168)

bp_image = iradon(sino, filter_name=None, circle=False)

new_sino = radon(bp_image, azi_angles, circle=False)

assert new_sino.shape == sino.shape
```

### Version information:

```Shell
3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)]
Windows-10-10.0.19045-SP0
scikit-image version: 0.20.0
numpy version: 1.26.0
```

**Comment by lagru** [comment]
Hey @GeorgeWebber, thank you for the report. From a quick glance and poke with a loop it seems like there are quite a few other cases for which the shapes differ. 

Maybe I am stating the obvious but it could very well be a property of the algorithms or parameters rather than a bug. But I agree that one would expect to be able to round-trip data, or at the very least the shape.

**Comment by lagru** [comment]
At the very least, our tests cover [a scenario for the radon-iradon case](https://github.com/scikit-image/scikit-image/blob/4bbf2c60e46bfb53488592eefec31c845070c229/skimage/transform/tests/test_radon_transform.py#L156). So it's curious why that doesn't work in the other direction.

**Comment by mkcor** [comment]
Hi @GeorgeWebber,

echoing @lagru, I'm not sure this is a bug. Because you used `circle=False` without providing any `output_size`, the size of `bp_image` was estimated according to
https://github.com/scikit-image/scikit-image/blob/441fe68b95a86d4ae2a351311a0c39a4232b6521/skimage/transform/radon_transform.py#L267
(282 in this case).

If you leave `circle=True` instead (which is the default), the size of `bp_image` is 400 and the shape of `new_sino = radon(bp_image, azi_angles)` is (400, 168), i.e., the same as `sino`'s.

Please relabel this issue as you see fit.

**Comment by lagru** [comment]
I think only maintainers can assign labels. Let's keep an eye on how the discussion develops. ;)

**Comment by mkcor** [comment]
> I think only maintainers can assign labels.

Hmm, I wouldn't think so, since (see above)
![label_issues](https://github.com/scikit-image/scikit-image/assets/2227806/fbc397d5-2054-4bc1-92dd-515becefe4ce)

> Let's keep an eye on how the discussion develops. ;)

Yup :+1:

**Comment by GeorgeWebber** [comment]
Ok, thank you both for clearing this up. It seems to be a feature not a bug so I'll close this issue
