### ISSUE TITLE
BLD: Build nightly wheels using  NumPy nightlies

### ISSUE THREAD

**Issue by seberg** [scikit-image/scikit-image#7249]
There may be a bit of a long tail here with dependencies, but it would be nice if we can build skimage nightlies with the NumPy nightlies.

Not sure there is agreement that this is OK, but the very quick thing would be to add:
```
CIBW_BUILD_FRONTEND: 'pip; args: --pre --extra-index-url "https://pypi.anaconda.org/scientific-python-nightly-wheels/simple"'
```
to the `scikit-image/workflows/nightly_wheel_build.yml`.  That allows pre-release of all build requirements, including e.g. cython.  If that is a problem/not desirable, the other path is to use the pre-build hook, manually install all requirements and then use `pip; args: --no-build-isolation`.

---

I am hoping the long tail of enabling nightlies here, isn't too annoying :(.

**Comment by lagru** [comment]
Hey, thanks for reaching out. :) 

I don't see an immediate problem with using other nightlies to build our own... That said, I honestly don't have a lot of context on what you are suggesting. What does the "simple" at the end of the URL signify? Would this affect only build time or runtime dependencies or both? By long tail, do you mean that we still have to wait until our dependencies work with NumPy 2.0 (assuming that's what this is about).

Cc @jarrodmillman

**Comment by seberg** [comment]
>  Do you mean packages need to be build against NumPy 2.0 for it to work with NumPy 2.0? And that is why we need to enable NumPy 2.0 which is available as a "nightly pre-release"?

Yes, exactly.

**Comment by stefanv** [comment]
So other packages, like astropy, who now depend on numpy 2 cannot depend on us until we compile against numpy 2.

That said, @seberg, I thought there were some backward compatibility guarantees when compiling against later numpy versions. Do those hold, so that we can work with np 1 and 2, or should we restrict numpy to >2?

**Comment by seberg** [comment]
You need to compile with 2, but the build will work with 1.x then.  Just not the other way around building with 1.x is incompatible with 2.x.  Clearly you need a way to build and be compatible with both.
Forcing the new one allows API (and thus ABI) changes.  Even just simple ones like removing a function nobody uses.

**Comment by lagru** [comment]
Trying to address this in https://github.com/scikit-image/scikit-image/pull/7251.

**Comment by lagru** [comment]
https://github.com/scikit-image/scikit-image/pull/7251 was merged recently which should trigger a nightly build of scikit-image with NumPy 2.0 next Sunday at 11:27 UTC. I'll leave this open until https://anaconda.org/scientific-python-nightly-wheels/scikit-image has been updated.

**Comment by lagru** [comment]
Okay, looks like the action ran and uploaded successfully. Though, running our test suite throws quite a bunch of new errors which look related to NumPy 2.0! 

I am a bit surprised by this because I assumed that our "Nightly Wheel builder" would test the wheels or that our regular test "Test nightly" workflow would have flagged those. But it turns out that one only builds with NumPy 2.0 but tests with NumPy 1.26.2. :see_no_evil: In the [last run of "Test nightly"](https://github.com/scikit-image/scikit-image/actions/runs/7304226903/job/19906105367#step:5:90) it looks like matplotlib is (indirectly) forcing the downgrade to 1.26? Or maybe its a dependency of matplotlib? Haven't yet figured out what precisely is causing that but it looks like the current setup may not be very reliable in using the actual nightlies from https://anaconda.org/scientific-python-nightly-wheels/ :thinking:

**Comment by pllim** [comment]
Yeah, matplotlib pulls in contourpy and contourpy pins `numpy<2` unapologetically.

* https://github.com/matplotlib/matplotlib/issues/26847

I use one of these 2 strategies to force numpy 2 on both the build and the test:

* Do not install matplotlib at all.
* Install matplotlib but then have an extra command after that to re-upgrade numpy to 2.

**Comment by lagru** [comment]
@pllim, thanks for the very quick feedback and context! That's unfortunate. I'll see how we can address this from the skimage's side.

**Comment by seberg** [comment]
> but tests with NumPy 1.26.2. 
From the perspective of ensuring that the build works with older NumPy versions, that is actually somewhat nice, although I guess if this would be the only run testing with 2.0, then maybe that is better.

**Comment by pllim** [comment]
> ensuring that the build works with older NumPy versions

I think that naturally happens when a package is about to release anyway, if you do RC and such?

**Comment by lagru** [comment]
Yes, we usually do release candidates.

**Comment by pllim** [comment]
I think this is no longer a problem? At least I don't see error from this package anyone running a job with numpy 2.0.dev. Thanks!

**Comment by lagru** [comment]
Yeah, building it with NumPy 2.0 seems to work, so closing this issue. However, we need to update some things to get scikit-image ready for 2.0. That'll happen in https://github.com/scikit-image/scikit-image/issues/7282.
