### ISSUE TITLE
Error installing botright due to scikit_image-0.21.0.tar.gz metadata preparation

### ISSUE THREAD

**Issue by 0nEoNi1** [scikit-image/scikit-image#7279]
### Description:

I am facing an issue while trying to install the botright Python module, which requires the installation of various dependencies. During the installation process, it encounters an error specifically related to the preparation of metadata for scikit_image-0.21.0.tar.gz.

Error Message:
[Error.txt](https://github.com/scikit-image/scikit-image/files/13767017/Error.txt)

Expected Behavior:
I expected the installation of botright to proceed smoothly without encountering errors related to the preparation of metadata for scikit_image-0.21.0.tar.gz.

Environment:
Python Version:  3.12.0
Pip Version: 23.3.2
Additional Information:

I can successfully install the latest version of scikit_image without any issues.
Provide any other relevant information that might help identify and resolve the issue.

Thank you for your assistance in resolving this issue.

**Comment by jeevithakannan2** [comment]
Try installing using python v3.10

**Comment by lagru** [comment]
Thanks for reaching out and sorry for the late reply.

It looks like it's trying to compile scikit-image itself instead of downloading a pre-built version from PyPI. From your description its very hard to debug this and would probably require a lot of effort on our side. So you might have more success inquiring with the botright project.

For that reason I'm closing this for now. But feel free to provide more context or reopen.
