### ISSUE TITLE
some query about skimage.transform.resize

### ISSUE THREAD

**Issue by tanjia123456** [scikit-image/scikit-image#7344]
### Description:

Hello, @lagru I want to resample my mri datasets, it's nifti format， my aim is accelerate network training. Because some slices have lesions, but if I specify spacing directly, some lesions will disappear after size changes. Can I modify size directly without changing spacing? Or can I only resize each two-dimensional slice, convert nifti to dicom, them change the size on the slice?
`
import nibabel as  nb
import skimage

def resample(data, ori_space, header, spacing):
    ### Calculate new space
    new_width = round(ori_space[0] * header['pixdim'][1] / spacing[0])
    new_height = round(ori_space[1] * header['pixdim'][2] / spacing[1])
    new_channel = round(ori_space[2] * header['pixdim'][3] / spacing[2])
    new_space = [new_width, new_height, new_channel]
    print(new_space)
    new_space = [256, 256, 240]

    data_resampled = skimage.transform.resize(data, new_space, order=1, mode='reflect', cval=0, clip=True,
                                              preserve_range=False, anti_aliasing=True, anti_aliasing_sigma=None)
    return data_resampled

for i in range(1, 2):
    for j in range(2):

        mri_file = "regis/regis_PA"+ str(i)+ "_SE" + str(j) + ".nii.gz"
        img = nb.load(mri_file)  # 读取nii格式文件

        img_affine = img.affine
        data = img.get_fdata()
        header = img.header
        print(header['pixdim'][1], header['pixdim'][2], header['pixdim'][3])  # 0.48913044  0.48913044  0.5

        width, height, channel = img.dataobj.shape
        print(width, height, channel)
        ori_space = [width, height, channel]

        # Resample to have 1.0 spacing in all axes
        spacing = [0.5, 0.5, 0.5]
        data_resampled = resample(data, ori_space, header, spacing)

        nb.Nifti1Image(data_resampled, img_affine).to_filename("resample_PA"+ str(i)+ "_SE" + str(j) + ".nii.gz")
`

**Comment by soupault** [comment]
@tanjia123456 

>Can I modify size directly without changing spacing?

In your case, one cannot be done without another. Changing the image size implies that the data is resampled and, thus, the voxels get different size/spacing.

I am not sure I fully understand the exact issue you are facing, but one thing you may look into is updating the affine matrix. In your code, you use the original one (`img_affine = img.affine`, `nb.Nifti1Image(data_resampled, img_affine)`), which is incorrect, since the voxel size is different after the resampling. Here is an excellent reference on the meaning of the matrix - https://nipy.org/nibabel/coordinate_systems.html .

I am going to close this issue for now, since it is connected with the library development. For general questions on image processing and data analysis, as well as questions regarding the use of `scikit-image`, please, consider this community forum - https://forum.image.sc/tag/scikit-image .
