### ISSUE TITLE
Import error with Homebrew installation

### ISSUE THREAD

**Issue by 99YyLi** [scikit-image/scikit-image#7351]
### Description:

MacOS: Using python3.12 installed via brew. I use the command: 
**brew install scikit-image**
but when I try to import skimage: **from skimage.measure import block_reduce**  there is an error: No module named 'skimage'
I checked the installation with: **brew -list**  and there scikit-image exists
But when I search in the path /opt/homebrew/lib/python3.12/site-packages there is no skimage
What should I do?

**Comment by mkcor** [comment]
Hi @99YyLi,

Are you trying to install scikit-image just to use it or also to contribute changes to the package? I'd like to redirect you to the [user forum](https://forum.image.sc/tag/scikit-image) and/or the [developer forum](https://discuss.scientific-python.org/c/contributor/skimage). Thank you!

**Comment by 99YyLi** [comment]
Hi @mkcor, please redirect me to the user forum, thanks!

**Comment by lagru** [comment]
Also this installation problem seems related to brew so you might be better off asking on their [Homebrew community forum](https://github.com/orgs/Homebrew/discussions) instead.

@99YyLi, since this question is probably better asked elsewhere I'm closing this. Feel free to reach out on the suggested forums if you encounter more problems with scikit-image. :)
