### ISSUE TITLE
measure.find_contours Key Error Stacktrace/fail

### ISSUE THREAD

**Issue by apiszcz** [scikit-image/scikit-image#817]
measure.find_contours failing with a KeyError message.

I can provide the image file (png) if needed. Note the image is inverted prior to this call.

image = Image.open(imgpath)
image_inv = PIL.ImageOps.invert(image)
npai = image_inv
npaif = np.array(npai, dtype='float')
npaif_contours = measure.find_contours(npaif,level=128.0,fully_connected='low',positive_orientation='low')

Traceback (most recent call last):
  File "lib\skimagelearn.py", line 44, in <module>
    npaif_contours = measure.find_contours(npaif,level=128.0,fully_connected='low',positive_orientation='low')
  File "E:\p\pythonlib64\lib\skimage\measure\find_contours.py", line 120, in find_contours
    contours = _assemble_contours(_take_2(point_list))
  File "E:\p\pythonlib64\lib\skimage\measure\find_contours.py", line 170, in _assemble_contours
    del ends[tail[-1]]
KeyError: (0.0, 396)

**Comment by stefanv** [comment]
@JDWarner Did you by any chance figure out what was happening here?

**Comment by JDWarner** [comment]
Honestly I never investigated further, but will dive into this over the next few days. Should be interesting!

**Comment by apiszcz** [comment]
Stefan: No, I provided a sample image which should reproduce the issue, I
hope that you observe the same failure. I chose to 'live' with it, however
I am interested in any updates. Josh appears to have a good handle on the
area causing the error.

**Comment by stefanv** [comment]
I cannot reproduce this under Python 3.  @JDWarner Are you able to?

**Comment by blink1073** [comment]
I can reproduce under Python 3.

**Comment by stefanv** [comment]
Right, does not happen when I load the image but it does when I load the numpy file.  Datafile can now be found here:

https://www.dropbox.com/s/22am3de09ogdaa7/npaif.npz?dl=0

**Comment by stefanv** [comment]
I think there is a corner case not accounted for in the logic.

**Comment by JDWarner** [comment]
@scikit-image/core I've gone round in circles on this one for about a week. The line that's failing is 
```python
del ends[tail[-1]]
```
which is supposed to snip out the `tail` contour from the `ends` dict. This presupposes that the `tail` counter is actually already in the `ends` dict - but it isn't. The trouble in tracking this back is that the exception happens later, when the deletion is attempted, rather than at the point where this entry was supposed to be added to `ends` in the first place.

However.

The purpose of that line is to remove the tail from `ends`. Except... it isn't there to be deleted. From a pragmatic perspective what happens if we just ignore this? The goal was to remove that entry - it's not there - mission complete? All of the other commands work, *including what really matters* which is that `head` is extended by `tail` and then that result gets appended to `ends`. So, the contour is preserved and all is well if this specific line is wrapped in a `try: ... except`.

I've run it this way with a custom warning printed, and the result is as expected. Tests pass. The contour in question is correctly present. While this might not be the most intellectually satisfying solution, it certainly seems like a user would prefer getting perfectly good results from working code. 

If this sounds like a reasonable short-term fix to bridge into 0.11, I'll make a PR with the minor fix. Otherwise we may need another set of eyes on this one.

**Comment by apiszcz** [comment]
Thank you for following up and digging into the corner case.

**Comment by stefanv** [comment]
@JDWarner FWIW, I came up with the same workaround, except that I didn't have nearly such a nice description as to why it would be a good one!

**Comment by zachrahan** [comment]
Hmm, though this workaround seems to work, I suspect that it MUST be masking some deeper bug. The loop invariant here is:
  - There is exactly one entry in `starts` and one entry in `ends` for every open contour in `contours`. (Open contours are those for which `contour[0] != contour[-1]`.)
  - For each open contour, `contour[0]` is in `starts` and `contour[-1]` is in `ends`.

Plugging in a quick test that this invariant holds at each iteration would very rapidly pinpoint when things change that there is a contour that can't be indexed as `ends[contour[-1]]`. This would then be "the point where this entry was supposed to be added to `ends` in the first place" that Josh was looking for. My suspicion is either there's some floating-point-comparison bizarreness going on (though I'm not sure how that would work), or there's some degenerate case that I hadn't previously thought of. (E.g. where a contour makes some kind of lariat structure and gets closed too early? But I'm not sure how that would work either.)

Sorry I don't have time right now to sort this out in more detail myself, but I at least wanted to note my thoughts quickly. Probably this should be left as an open issue of some sort, even with the workaround in place. 

Also, note also that as symmetric as the code is, there's probably an equivalent issue with `del starts[head[0]]` on [_find_contours.py:182](https://github.com/scikit-image/scikit-image/blob/master/skimage/measure/_find_contours.py#L182).
