### ISSUE TITLE
Add text rendering to `skimage.draw`

### ISSUE THREAD

**Issue by stefanv** [scikit-image/scikit-image#877]
This issue is based on an email I received after EuroSciPy 2013 from Nicolas Rougier, who writes:

---

I saw the topic on the antialiased text and since I've made the freetype bindings (using c-type), maybe this can be of some help:

http://code.google.com/p/freetype-py/

It's pure python and fairly well documented (I included freetype documentation within the bindings). There is also an example directory to show how to render text into a numpy array.

Last, there is also a very nice article at http://www.antigrain.com/research/font_rasterization/ that explain how to render text properly. The "agg_trick.py" demo does just that.

---

Since AGG has been mentioned in this post, I'd like to offer my condolences to the family of Maxim Shemanarev, the author of AGG, who passed away recently.  During my PhD, I struggled for days to address certain corner cases of well-known polygon intersection algorithms, only to look at Maxim's code to find elegant workarounds already in place.  Whenever you see a beautifully rendered Matplotlib figure, Maxim's work is at the heart of it.

**Comment by nizamov** [comment]
It seems that freetype-py is actually a python wrapper around libfreetype and therefore needs some extra binaries. Moreover, the last binary from libfreetype for windows is dated 2008 and does not mention even Win7 as supported. Therefore adding freetype to skimage does not seem to be worthwhile.

**Comment by stefanv** [comment]
After discussions with @pelson, I think the easiest route forward is using matplotlib to render to canvas.  Phil, do you have the latest version of your rendering code lying around?

**Comment by tacaswell** [comment]
@mdboom is working on pulling the freetype wrappers out of mpl https://github.com/matplotlib/freetypy

**Comment by mdboom** [comment]
I developed freetypy because freetype-py is ctypes based, and we have a no ctypes policy in matplotlib for reasons of portability to secure platforms.  Also, some things are just really hard to do with freetype and ctypes (like outline decomposition) that we needed to do for matplotlib.

While the work to integrate this back into matplotlib is ongoing, I think freetypy is ready for use by others without too much pain.  If you just want to render a string to a numpy array, the pieces are all there.

Of course, unless you want to hardcode the font, you also need a font lookup mechanism, which freetype doesn't provide.  There are more nascent wrappers for fontconfig at http://github.com/matplotlib/fcpy that we also plan to use for matplotlib in the near future.

That said, all this is fairly low-level and may not be necessary if you just want basic text layout and your font lookup requirements are simple.  As much as I'd like to promote my own stuff, for simple uses, cairo/pango may be a better option, and is also cross platform.  You can get an image buffer out and reinterpret it as a numpy array and you're golden.

@nizamov: As for your concerns about freetype being dead on Windows, that's not the case.  I suspect you found the freetype package from the GnuWin32 project which is a fairly inactive, if not dead, project.  Christoph Gohlke, MSYS2 and Anadonda all provide newer versions of FreeType, and FreeType is still officially supported on Windows and should be for the forseeable future.  It's the linchpin of much cross-platform software (including Firefox), so I don't think it's going away.

**Comment by bebosudo** [comment]
Hi! Any news about this feature? The lack of it forces me to use opencv, which makes me sad :(

**Comment by jni** [comment]
@bebosudo this is not currently in the roadmap. The thread above suggests several promising avenues, but imho they should preferably live outside of scikit-image (with perhaps some documentation on their use within the gallery). Others at @scikit-image/core might have a different perspective to offer!

**Comment by sciunto** [comment]
I'm +1 with @jni. Not the sort of thing I want to maintain in scikit-image. BTW, we must update this list also... https://github.com/scikit-image/scikit-image/wiki/Requested-features#drawing-directly-on-an-ndarray

**Comment by zpincus** [comment]
Hi all: you may be interested to note a project that I had a minor hand in getting started (but which is really the main effort of @jwiggins): [celiagg](https://github.com/celiagg/celiagg), a wrapper for agg that draws directly to numpy arrays. It's fast, it has (optional) antialiasing, it does text if you have freetype installed, and you can draw to G, GA, RGB, and RGBA arrays in a variety of dtypes. It's also on [conda-forge](https://anaconda.org/conda-forge/celiagg).

It's another dependency, but a lot faster and more bulletproof than most of the other rasterization options out there, especially for drawing to numpy arrays. So that may be a good option for some users.

**Comment by sciunto** [comment]
Thanks for sharing this @zpincus This is extremely valuable. If there is no difficulties to add this dependency, using this library sounds like a good idea.

**Comment by jwiggins** [comment]
Thanks for the plug @zpincus. I'd also mention [blend2d](https://github.com/jwiggins/blend2d-python). It's quite a bit less mature, but it provides font rendering without freetype. The only runtime dependency is numpy.

**Comment by zpincus** [comment]
Ooh, blend2d looks like the future. That library would appear much easier to interface with and extend than Agg. Thanks for the tip @jwiggins!

**Comment by jni** [comment]
Hi everyone, just wanted to note that we have considered celiagg before in #3129. It still seems quite heavyweight to me (anything requiring compilation is), so I would say that we can point to it in the docs, rather than implement text rendering and take it on as a dependency.

**Comment by zpincus** [comment]
Oh yeah - don’t take celiagg as a dependency! Sorry I wasn’t more clear. Celiagg is a good option to point people at who need text rendering or other fast rasterization to numpy arrays, but I wouldn’t recommend making it part of skimage per se. 

Blend2d might eventually make sense. But honestly skimage may not need an internal text renderer if good 3rd party options exist that can interoperate with numpy arrays. And definitely not at the cost of adding complex dependencies.

**Comment by FirefoxMetzger** [comment]
Figured that it is about time to necromance this thread and share a snippet that uses matplotlib to do the job:

```python
import numpy as np
import imageio.v3 as iio
import matplotlib.pyplot as plt
from matplotlib.figure import figaspect

img = iio.imread("imageio:chelsea.png")
fig, ax = plt.subplots(figsize=figaspect(img), dpi=75)
ax.imshow(img)
ax.text(5, 5, "I am stefan's cat.", fontsize=32, va="top")
ax.set_axis_off()
ax.set_position([0, 0, 1, 1])
fig.canvas.draw()
annotated_img = np.asarray(fig.canvas.renderer.buffer_rgba())
plt.close(fig)
iio.imwrite("annotated_cat.png", annotated_img)
```

Which produces the following image:

![annotated_cat](https://user-images.githubusercontent.com/4402489/177327553-e9b4a4c6-57e2-48e6-af40-a6d51620e8f7.png)

The big disclaimer here is that matplotlib's `draw` call will resample the image. This means that this isn't particularly performant, will change the total number of pixels (unless you know the DPI). For pure visualizations, however, this should be sufficient, so maybe it could be a useful workaround for now.

**Comment by jni** [comment]
Good stuff @FirefoxMetzger! So, my suggestion would be, could you add that to the gallery (with @tacaswell's suggested improvement) and then we can close this issue?

**Comment by FirefoxMetzger** [comment]
@tacaswell I just gave `fig.figimage` a shot. It also offers `resize=True` which is nice because it removes the need to manually scale the figure. However, I can't seem to get a text to show up on top of the figure. I'm not sure if this a zorder issue or something else related to `figimage`. Do you have any idea?

Here is the updated snippet:

```python
import numpy as np
import imageio.v3 as iio
import matplotlib.pyplot as plt

img = iio.imread("imageio:chelsea.png")
fig = plt.figure()
fig.figimage(img, resize=True)

ax = fig.add_axes([0, 0, 1, 1])
ax.text(0, 0, "I am stefan's cat.", fontsize=32, va="bottom")

fig.canvas.draw()
annotated_img = np.asarray(fig.canvas.renderer.buffer_rgba())
plt.close(fig)
iio.imwrite("annotated_cat.png", annotated_img)
```

@jni Sure, I already have it in a gallery example. The main holdup for now is figuring out why `fig.figimage` prevents the axis from showing up in the final result.

**Comment by FirefoxMetzger** [comment]
Here is a link to the current gallery example (without `fig.figimage`): https://output.circle-artifacts.com/output/job/286839b3-59f7-42ad-b5c4-e6f73d392472/artifacts/0/doc/build/html/auto_examples/applications/plot_text.html#sphx-glr-auto-examples-applications-plot-text-py

**Comment by pelson** [comment]
> The main holdup for now is figuring out why `fig.figimage` prevents the axis from showing up in the final result.

I would suggest against using ``Axes.text``, and instead use ``Figure.text``. If you do so, it works as expected.


```python

import numpy as np
import imageio.v2 as iio
import matplotlib.pyplot as plt

img = iio.imread("imageio:chelsea.png")
fig = plt.figure()
fig.figimage(
    img,
    resize=True,  # Resize the figure to the image to avoid any interpolation.
)

fig.text(0, 0, "I am stefan's cat.", fontsize=32, va="bottom")

fig.canvas.draw()
annotated_img = np.asarray(fig.canvas.renderer.buffer_rgba())
plt.close(fig)
iio.imwrite("annotated_cat.png", annotated_img)
```
